clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found: %s', configurationFile);
end

configuration = load(configurationFile);

dataDirectory = configuration.dataDirectory;
resultsDirectory = configuration.resultsDirectory;

subjectIDs = configuration.subjectIDs;
groupA = configuration.groupA;
groupB = configuration.groupB;

targetFrequencies = configuration.targetFrequencies;
targetIndices = configuration.targetIndices;

samplingFrequency = configuration.samplingFrequency;
numberOfChannels = configuration.numberOfChannels;
numberOfTargets = configuration.numberOfTargets;
numberOfBlocks = configuration.numberOfBlocks;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);

expectedNumberOfTimeSamples = ...
    configuration.trialDurationSeconds * samplingFrequency;

cueDurationSeconds = 0.5;
stimulationDurationSeconds = ...
    configuration.stimulationDurationSeconds;

stimulusStartSample = ...
    round(cueDurationSeconds * samplingFrequency) + 1;

numberOfStimulusSamples = ...
    round(stimulationDurationSeconds * samplingFrequency);

stimulusEndSample = ...
    stimulusStartSample + numberOfStimulusSamples - 1;

if stimulusEndSample > expectedNumberOfTimeSamples
    error('The stimulation window exceeds the trial length.');
end

channelLocationFile = fullfile( ...
    dataDirectory, ...
    '64-channels.loc' ...
);

if ~isfile(channelLocationFile)
    error('Channel-location file was not found.');
end

fileID = fopen(channelLocationFile, 'r');

if fileID == -1
    error('Unable to open 64-channels.loc.');
end

channelInformation = textscan( ...
    fileID, ...
    '%f %f %f %s', ...
    'MultipleDelimsAsOne', true ...
);

fclose(fileID);

channelNumbers = channelInformation{1};
channelLabels = channelInformation{4};

ozRow = find( ...
    strcmpi(strtrim(channelLabels), 'Oz'), ...
    1 ...
);

if isempty(ozRow)
    error('The Oz channel was not found in 64-channels.loc.');
end

ozChannelIndex = channelNumbers(ozRow);

fprintf('Oz channel index: %d\n', ozChannelIndex);
fprintf('Full trial samples: %d\n', expectedNumberOfTimeSamples);
fprintf( ...
    'Stimulus samples: %d:%d\n', ...
    stimulusStartSample, ...
    stimulusEndSample ...
);
fprintf( ...
    'Stimulus duration: %.2f seconds\n\n', ...
    numberOfStimulusSamples / samplingFrequency ...
);

ozFullTrials = zeros( ...
    expectedNumberOfTimeSamples, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

ozStimulusTrials = zeros( ...
    numberOfStimulusSamples, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

numberOfTrials = ...
    numberOfSubjects * numberOfClasses * numberOfBlocks;

subjectColumn = zeros(numberOfTrials, 1);
groupColumn = strings(numberOfTrials, 1);
classColumn = zeros(numberOfTrials, 1);
frequencyColumn = zeros(numberOfTrials, 1);
targetIndexColumn = zeros(numberOfTrials, 1);
blockColumn = zeros(numberOfTrials, 1);
subjectArrayIndexColumn = zeros(numberOfTrials, 1);
classArrayIndexColumn = zeros(numberOfTrials, 1);

metadataRow = 0;

for subjectArrayIndex = 1:numberOfSubjects

    subjectID = subjectIDs(subjectArrayIndex);

    subjectFile = fullfile( ...
        dataDirectory, ...
        sprintf('S%d.mat', subjectID) ...
    );

    fprintf( ...
        'Loading subject S%d (%d of %d)...\n', ...
        subjectID, ...
        subjectArrayIndex, ...
        numberOfSubjects ...
    );

    loadedSubject = load(subjectFile);

    if isfield(loadedSubject, 'data')
        eegData = loadedSubject.data;
    else
        loadedVariableNames = fieldnames(loadedSubject);
        eegData = [];

        for variableIndex = 1:numel(loadedVariableNames)

            candidateVariable = loadedSubject.( ...
                loadedVariableNames{variableIndex} ...
            );

            candidateSize = size(candidateVariable);

            if isnumeric(candidateVariable) && ...
               ndims(candidateVariable) == 4 && ...
               isequal( ...
                   candidateSize, ...
                   [ ...
                       numberOfChannels, ...
                       expectedNumberOfTimeSamples, ...
                       numberOfTargets, ...
                       numberOfBlocks ...
                   ] ...
               )

                eegData = candidateVariable;
                break;
            end
        end
    end

    if isempty(eegData)
        error( ...
            'A valid EEG variable was not found in S%d.mat.', ...
            subjectID ...
        );
    end

    actualSize = size(eegData);

    expectedSize = [
        numberOfChannels, ...
        expectedNumberOfTimeSamples, ...
        numberOfTargets, ...
        numberOfBlocks
    ];

    if ~isequal(actualSize, expectedSize)
        error( ...
            ['Unexpected dimensions in S%d.mat.\n' ...
             'Expected: [%s]\n' ...
             'Actual:   [%s]'], ...
            subjectID, ...
            num2str(expectedSize), ...
            num2str(actualSize) ...
        );
    end

    if ismember(subjectID, groupA)
        currentGroup = "A";
    elseif ismember(subjectID, groupB)
        currentGroup = "B";
    else
        error('Subject S%d does not belong to Group A or B.', subjectID);
    end

    for classArrayIndex = 1:numberOfClasses

        targetIndex = targetIndices(classArrayIndex);
        stimulusFrequency = targetFrequencies(classArrayIndex);

        for blockIndex = 1:numberOfBlocks

            fullTrial = squeeze( ...
                eegData( ...
                    ozChannelIndex, ...
                    :, ...
                    targetIndex, ...
                    blockIndex ...
                ) ...
            );

            fullTrial = double(fullTrial(:));

            stimulusTrial = fullTrial( ...
                stimulusStartSample:stimulusEndSample ...
            );

            ozFullTrials( ...
                :, ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = fullTrial;

            ozStimulusTrials( ...
                :, ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = stimulusTrial;

            metadataRow = metadataRow + 1;

            subjectColumn(metadataRow) = subjectID;
            groupColumn(metadataRow) = currentGroup;
            classColumn(metadataRow) = classArrayIndex;
            frequencyColumn(metadataRow) = stimulusFrequency;
            targetIndexColumn(metadataRow) = targetIndex;
            blockColumn(metadataRow) = blockIndex;
            subjectArrayIndexColumn(metadataRow) = subjectArrayIndex;
            classArrayIndexColumn(metadataRow) = classArrayIndex;
        end
    end
end

trialMetadata = table( ...
    subjectColumn, ...
    groupColumn, ...
    classColumn, ...
    frequencyColumn, ...
    targetIndexColumn, ...
    blockColumn, ...
    subjectArrayIndexColumn, ...
    classArrayIndexColumn, ...
    'VariableNames', { ...
        'SubjectID', ...
        'Group', ...
        'ClassLabel', ...
        'StimulusFrequencyHz', ...
        'TargetIndex', ...
        'Block', ...
        'SubjectArrayIndex', ...
        'ClassArrayIndex' ...
    } ...
);

if height(trialMetadata) ~= numberOfTrials
    error('The number of extracted trials is incorrect.');
end

if any(isnan(ozStimulusTrials(:)))
    error('NaN values were detected in the extracted data.');
end

featureResultsDirectory = fullfile( ...
    resultsDirectory, ...
    'features' ...
);

if ~isfolder(featureResultsDirectory)
    mkdir(featureResultsDirectory);
end

outputMatFile = fullfile( ...
    featureResultsDirectory, ...
    'step02_oz_trials.mat' ...
);

outputCsvFile = fullfile( ...
    featureResultsDirectory, ...
    'step02_trial_metadata.csv' ...
);

save( ...
    outputMatFile, ...
    'ozFullTrials', ...
    'ozStimulusTrials', ...
    'trialMetadata', ...
    'ozChannelIndex', ...
    'stimulusStartSample', ...
    'stimulusEndSample', ...
    'numberOfStimulusSamples', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies', ...
    'targetIndices', ...
    '-v7.3' ...
);

writetable(trialMetadata, outputCsvFile);

fprintf('\n----------------------------------------\n');
fprintf('Oz extraction completed successfully.\n');
fprintf('----------------------------------------\n');

fprintf('Number of subjects: %d\n', numberOfSubjects);
fprintf('Number of classes: %d\n', numberOfClasses);
fprintf('Blocks per class: %d\n', numberOfBlocks);
fprintf('Total extracted trials: %d\n', numberOfTrials);
fprintf('Samples per five-second trial: %d\n', numberOfStimulusSamples);

fprintf('\nSize of ozFullTrials:\n');
disp(size(ozFullTrials));

fprintf('Size of ozStimulusTrials:\n');
disp(size(ozStimulusTrials));

fprintf('MAT output:\n%s\n\n', outputMatFile);
fprintf('CSV output:\n%s\n', outputCsvFile);