clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz trials file was not found.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

ozFullTrials = inputData.ozFullTrials;
samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = configuration.numberOfBlocks;

windowStartSample = 126;
windowEndSample = 1375;
numberOfWindowSamples = 1250;

waveletName = 'db4';
decompositionLevel = 4;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

candidateBoundaryModes = {
    'sym'
    'symh'
    'zpd'
    'sp0'
    'spd'
    'ppd'
    'per'
    'asym'
    'asymh'
};

processingMethods = {
    'FullTrialDWT_ThenCrop'
    'CropThenDWT'
};

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)

    matchedIndex = find(subjectIDs == groupA(index), 1);

    if isempty(matchedIndex)
        error('Group A subject S%d was not found.', groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)

    matchedIndex = find(subjectIDs == groupB(index), 1);

    if isempty(matchedIndex)
        error('Group B subject S%d was not found.', groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

frequencySearchMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = frequencyAxis(frequencySearchMask);

maximumNumberOfResults = ...
    numel(candidateBoundaryModes) * numel(processingMethods);

boundaryModeColumn = strings(maximumNumberOfResults, 1);
processingMethodColumn = strings(maximumNumberOfResults, 1);

meanAbsoluteDifferenceColumn = ...
    nan(maximumNumberOfResults, 1);

groupAMeanAbsoluteDifferenceColumn = ...
    nan(maximumNumberOfResults, 1);

groupBMeanAbsoluteDifferenceColumn = ...
    nan(maximumNumberOfResults, 1);

rootMeanSquaredDifferenceColumn = ...
    nan(maximumNumberOfResults, 1);

maximumAbsoluteDifferenceColumn = ...
    nan(maximumNumberOfResults, 1);

matchingPercentageColumn = ...
    nan(maximumNumberOfResults, 1);

matchingTolerance = 0.051;

resultIndex = 0;

bestScore = inf;
bestBoundaryMode = "";
bestProcessingMethod = "";
bestDominantFrequencyArray = [];
bestMeanDominantFrequencies = [];

fprintf('================================================\n');
fprintf('Step 08: Wavelet-setting search\n');
fprintf('================================================\n\n');

fprintf('Window: %d:%d\n', ...
    windowStartSample, windowEndSample);

fprintf('Wavelet: %s\n', waveletName);
fprintf('Level: %d\n\n', decompositionLevel);

for modeIndex = 1:numel(candidateBoundaryModes)

    boundaryMode = candidateBoundaryModes{modeIndex};

    try
        dwtmode(boundaryMode, 'nodisp');
    catch
        fprintf( ...
            'Boundary mode %s is not supported. Skipping.\n', ...
            boundaryMode ...
        );
        continue;
    end

    for methodIndex = 1:numel(processingMethods)

        processingMethod = processingMethods{methodIndex};

        resultIndex = resultIndex + 1;

        fprintf( ...
            'Testing mode=%s, method=%s ...\n', ...
            boundaryMode, ...
            processingMethod ...
        );

        dominantFrequencyArray = zeros( ...
            numberOfClasses, ...
            numberOfBlocks, ...
            numberOfSubjects ...
        );

        failedVariant = false;

        for subjectIndex = 1:numberOfSubjects

            for classIndex = 1:numberOfClasses

                for blockIndex = 1:numberOfBlocks

                    fullTrialSignal = squeeze( ...
                        ozFullTrials( ...
                            :, ...
                            classIndex, ...
                            blockIndex, ...
                            subjectIndex ...
                        ) ...
                    );

                    fullTrialSignal = double(fullTrialSignal(:));

                    try
                        switch processingMethod

                            case 'FullTrialDWT_ThenCrop'

                                [coefficients, bookkeeping] = wavedec( ...
                                    fullTrialSignal, ...
                                    decompositionLevel, ...
                                    waveletName ...
                                );

                                reconstructedD4 = wrcoef( ...
                                    'd', ...
                                    coefficients, ...
                                    bookkeeping, ...
                                    waveletName, ...
                                    decompositionLevel ...
                                );

                                analysisSignal = reconstructedD4( ...
                                    windowStartSample:windowEndSample ...
                                );

                            case 'CropThenDWT'

                                croppedSignal = fullTrialSignal( ...
                                    windowStartSample:windowEndSample ...
                                );

                                [coefficients, bookkeeping] = wavedec( ...
                                    croppedSignal, ...
                                    decompositionLevel, ...
                                    waveletName ...
                                );

                                analysisSignal = wrcoef( ...
                                    'd', ...
                                    coefficients, ...
                                    bookkeeping, ...
                                    waveletName, ...
                                    decompositionLevel ...
                                );

                            otherwise
                                error('Unknown processing method.');
                        end

                    catch exceptionInformation

                        warning( ...
                            'Variant failed: mode=%s, method=%s. %s', ...
                            boundaryMode, ...
                            processingMethod, ...
                            exceptionInformation.message ...
                        );

                        failedVariant = true;
                        break;
                    end

                    analysisSignal = double(analysisSignal(:));

                    if numel(analysisSignal) ~= numberOfWindowSamples
                        failedVariant = true;
                        break;
                    end

                    fftCoefficients = fft(analysisSignal);

                    twoSidedAmplitude = ...
                        abs(fftCoefficients / numberOfWindowSamples);

                    oneSidedAmplitude = ...
                        twoSidedAmplitude( ...
                            1:(numberOfWindowSamples / 2 + 1) ...
                        );

                    oneSidedAmplitude(2:end - 1) = ...
                        2 * oneSidedAmplitude(2:end - 1);

                    searchAmplitude = ...
                        oneSidedAmplitude(frequencySearchMask);

                    [~, maximumIndex] = max(searchAmplitude);

                    dominantFrequencyArray( ...
                        classIndex, ...
                        blockIndex, ...
                        subjectIndex ...
                    ) = searchFrequencies(maximumIndex);
                end

                if failedVariant
                    break;
                end
            end

            if failedVariant
                break;
            end
        end

        boundaryModeColumn(resultIndex) = boundaryMode;
        processingMethodColumn(resultIndex) = processingMethod;

        if failedVariant
            continue;
        end

        meanDominantFrequencies = squeeze( ...
            mean(dominantFrequencyArray, 2) ...
        )';

        calculatedGroupA = ...
            meanDominantFrequencies(groupAIndices, :);

        calculatedGroupB = ...
            meanDominantFrequencies(groupBIndices, :);

        differenceGroupA = calculatedGroupA - paperGroupA;
        differenceGroupB = calculatedGroupB - paperGroupB;

        allDifferences = [
            differenceGroupA(:)
            differenceGroupB(:)
        ];

        groupAMeanAbsoluteDifference = ...
            mean(abs(differenceGroupA(:)));

        groupBMeanAbsoluteDifference = ...
            mean(abs(differenceGroupB(:)));

        meanAbsoluteDifference = ...
            mean(abs(allDifferences));

        rootMeanSquaredDifference = ...
            sqrt(mean(allDifferences .^ 2));

        maximumAbsoluteDifference = ...
            max(abs(allDifferences));

        matchingPercentage = ...
            100 * sum( ...
                abs(allDifferences) <= matchingTolerance ...
            ) / numel(allDifferences);

        meanAbsoluteDifferenceColumn(resultIndex) = ...
            meanAbsoluteDifference;

        groupAMeanAbsoluteDifferenceColumn(resultIndex) = ...
            groupAMeanAbsoluteDifference;

        groupBMeanAbsoluteDifferenceColumn(resultIndex) = ...
            groupBMeanAbsoluteDifference;

        rootMeanSquaredDifferenceColumn(resultIndex) = ...
            rootMeanSquaredDifference;

        maximumAbsoluteDifferenceColumn(resultIndex) = ...
            maximumAbsoluteDifference;

        matchingPercentageColumn(resultIndex) = ...
            matchingPercentage;

        fprintf( ...
            ['  Overall MAD=%.4f, Group A MAD=%.4f, ' ...
             'Group B MAD=%.4f, Match=%.2f%%\n'], ...
            meanAbsoluteDifference, ...
            groupAMeanAbsoluteDifference, ...
            groupBMeanAbsoluteDifference, ...
            matchingPercentage ...
        );

        if meanAbsoluteDifference < bestScore

            bestScore = meanAbsoluteDifference;
            bestBoundaryMode = boundaryMode;
            bestProcessingMethod = processingMethod;

            bestDominantFrequencyArray = ...
                dominantFrequencyArray;

            bestMeanDominantFrequencies = ...
                meanDominantFrequencies;
        end
    end
end

boundaryModeColumn = boundaryModeColumn(1:resultIndex);
processingMethodColumn = processingMethodColumn(1:resultIndex);

meanAbsoluteDifferenceColumn = ...
    meanAbsoluteDifferenceColumn(1:resultIndex);

groupAMeanAbsoluteDifferenceColumn = ...
    groupAMeanAbsoluteDifferenceColumn(1:resultIndex);

groupBMeanAbsoluteDifferenceColumn = ...
    groupBMeanAbsoluteDifferenceColumn(1:resultIndex);

rootMeanSquaredDifferenceColumn = ...
    rootMeanSquaredDifferenceColumn(1:resultIndex);

maximumAbsoluteDifferenceColumn = ...
    maximumAbsoluteDifferenceColumn(1:resultIndex);

matchingPercentageColumn = ...
    matchingPercentageColumn(1:resultIndex);

resultsTable = table( ...
    boundaryModeColumn, ...
    processingMethodColumn, ...
    meanAbsoluteDifferenceColumn, ...
    groupAMeanAbsoluteDifferenceColumn, ...
    groupBMeanAbsoluteDifferenceColumn, ...
    rootMeanSquaredDifferenceColumn, ...
    maximumAbsoluteDifferenceColumn, ...
    matchingPercentageColumn, ...
    'VariableNames', { ...
        'BoundaryMode', ...
        'ProcessingMethod', ...
        'MeanAbsoluteDifferenceHz', ...
        'GroupAMeanAbsoluteDifferenceHz', ...
        'GroupBMeanAbsoluteDifferenceHz', ...
        'RootMeanSquaredDifferenceHz', ...
        'MaximumAbsoluteDifferenceHz', ...
        'MatchingPercentage' ...
    } ...
);

resultsTable = resultsTable( ...
    ~isnan(resultsTable.MeanAbsoluteDifferenceHz), ...
    : ...
);

resultsTable = sortrows( ...
    resultsTable, ...
    'MeanAbsoluteDifferenceHz', ...
    'ascend' ...
);

bestCalculatedGroupA = ...
    bestMeanDominantFrequencies(groupAIndices, :);

bestCalculatedGroupB = ...
    bestMeanDominantFrequencies(groupBIndices, :);

outputDirectory = fullfile( ...
    configuration.resultsDirectory, ...
    'wavelet_search' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

outputCsvFile = fullfile( ...
    outputDirectory, ...
    'step08_wavelet_setting_results.csv' ...
);

outputMatFile = fullfile( ...
    outputDirectory, ...
    'step08_wavelet_setting_results.mat' ...
);

writetable(resultsTable, outputCsvFile);

save( ...
    outputMatFile, ...
    'resultsTable', ...
    'bestBoundaryMode', ...
    'bestProcessingMethod', ...
    'bestScore', ...
    'bestDominantFrequencyArray', ...
    'bestMeanDominantFrequencies', ...
    'bestCalculatedGroupA', ...
    'bestCalculatedGroupB', ...
    'paperGroupA', ...
    'paperGroupB', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 08 completed\n');
fprintf('================================================\n\n');

fprintf('Ranked wavelet settings:\n');
disp(resultsTable);

fprintf('Best boundary mode: %s\n', bestBoundaryMode);
fprintf('Best processing method: %s\n', bestProcessingMethod);
fprintf('Best mean absolute difference: %.4f Hz\n', bestScore);

fprintf('\nBest Group A averages:\n');

disp(array2table( ...
    [groupA(:), bestCalculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
));

fprintf('\nBest Group B averages:\n');

disp(array2table( ...
    [groupB(:), bestCalculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
));

fprintf('\nResults CSV:\n%s\n', outputCsvFile);
fprintf('\nResults MAT:\n%s\n', outputMatFile);