clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

classificationDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'classification_learner' ...
);

groupAFile = fullfile( ...
    classificationDirectory, ...
    'GroupA_ClassificationLearner.xlsx' ...
);

groupBFile = fullfile( ...
    classificationDirectory, ...
    'GroupB_ClassificationLearner.xlsx' ...
);

if ~isfile(groupAFile)
    error('Group A file was not found:\n%s', groupAFile);
end

if ~isfile(groupBFile)
    error('Group B file was not found:\n%s', groupBFile);
end

requiredFunctions = {
    'trainFineTree10Fold'
    'trainLDA10Fold'
    'trainSVM10Fold'
};

for functionIndex = 1:numel(requiredFunctions)

    functionName = requiredFunctions{functionIndex};

    if exist(functionName, 'file') ~= 2
        error( ...
            'Required function was not found: %s', ...
            functionName ...
        );
    end
end

groupNames = [
    "A"
    "B"
];

groupFiles = {
    groupAFile
    groupBFile
};

expectedObservationCounts = [
    240
    432
];

modelNames = [
    "Fine Tree"
    "Linear Discriminant"
    "Linear SVM"
];

modelFunctions = {
    @trainFineTree10Fold
    @trainLDA10Fold
    @trainSVM10Fold
};

articleAccuracyPercent = [
    95.8, 96.7, 96.7
    91.4, 91.7, 91.9
];

articleAveragePrecision = [
    0.95, 0.96, 0.96
    0.92, 0.91, 0.91
];

articleAverageSensitivity = [
    0.95, 0.96, 0.96
    0.92, 0.91, 0.91
];

numberOfGroups = numel(groupNames);
numberOfModels = numel(modelNames);
numberOfClasses = 4;

numberOfSummaryRows = ...
    numberOfGroups * numberOfModels;

numberOfClassRows = ...
    numberOfGroups * numberOfModels * numberOfClasses;

summaryGroup = strings(numberOfSummaryRows, 1);
summaryClassifier = strings(numberOfSummaryRows, 1);

accuracyPercentColumn = zeros(numberOfSummaryRows, 1);
averagePrecisionColumn = zeros(numberOfSummaryRows, 1);
averageSensitivityColumn = zeros(numberOfSummaryRows, 1);
averageF1ScoreColumn = zeros(numberOfSummaryRows, 1);

articleAccuracyColumn = zeros(numberOfSummaryRows, 1);
articlePrecisionColumn = zeros(numberOfSummaryRows, 1);
articleSensitivityColumn = zeros(numberOfSummaryRows, 1);

accuracyDifferenceColumn = zeros(numberOfSummaryRows, 1);
precisionDifferenceColumn = zeros(numberOfSummaryRows, 1);
sensitivityDifferenceColumn = zeros(numberOfSummaryRows, 1);

classGroup = strings(numberOfClassRows, 1);
classClassifier = strings(numberOfClassRows, 1);
classLabelColumn = zeros(numberOfClassRows, 1);

truePositiveColumn = zeros(numberOfClassRows, 1);
falsePositiveColumn = zeros(numberOfClassRows, 1);
falseNegativeColumn = zeros(numberOfClassRows, 1);
trueNegativeColumn = zeros(numberOfClassRows, 1);

classPrecisionColumn = zeros(numberOfClassRows, 1);
classSensitivityColumn = zeros(numberOfClassRows, 1);
classSpecificityColumn = zeros(numberOfClassRows, 1);
classF1ScoreColumn = zeros(numberOfClassRows, 1);

confusionMatrices = cell( ...
    numberOfGroups, ...
    numberOfModels ...
);

summaryRow = 0;
classRow = 0;

randomSeed = 2026;

fprintf('================================================\n');
fprintf('Step 19: 10-fold precision and sensitivity\n');
fprintf('================================================\n\n');

fprintf('Cross-validation seed: %d\n', randomSeed);
fprintf('Averaging method: Macro average over four classes\n\n');

for groupIndex = 1:numberOfGroups

    currentGroup = groupNames(groupIndex);

    currentData = readtable( ...
        groupFiles{groupIndex} ...
    );

    requiredVariables = {
        'DominantFrequencyHz'
        'ClassLabel'
    };

    for variableIndex = 1:numel(requiredVariables)

        variableName = requiredVariables{variableIndex};

        if ~ismember( ...
                variableName, ...
                currentData.Properties.VariableNames ...
            )

            error( ...
                'Variable %s was not found in Group %s.', ...
                variableName, ...
                currentGroup ...
            );
        end
    end

    currentData = currentData(:, requiredVariables);

    if height(currentData) ~= ...
            expectedObservationCounts(groupIndex)

        error( ...
            ['Group %s must contain %d observations, ' ...
             'but contains %d.'], ...
            currentGroup, ...
            expectedObservationCounts(groupIndex), ...
            height(currentData) ...
        );
    end

    trueLabels = currentData.ClassLabel;

    if iscategorical(trueLabels) || ...
            isstring(trueLabels) || ...
            iscell(trueLabels)

        trueLabels = str2double(string(trueLabels));
    end

    trueLabels = double(trueLabels(:));

    if ~isequal(unique(trueLabels), (1:4)')
        error( ...
            'Group %s must contain class labels 1 to 4.', ...
            currentGroup ...
        );
    end

    classCounts = zeros(numberOfClasses, 1);

    for classIndex = 1:numberOfClasses

        classCounts(classIndex) = sum( ...
            trueLabels == classIndex ...
        );
    end

    fprintf('Group %s\n', currentGroup);
    fprintf('Observations: %d\n', height(currentData));

    fprintf( ...
        'Class counts: %d, %d, %d, %d\n\n', ...
        classCounts(1), ...
        classCounts(2), ...
        classCounts(3), ...
        classCounts(4) ...
    );

    for modelIndex = 1:numberOfModels

        summaryRow = summaryRow + 1;

        rng(randomSeed, 'twister');

        [~, ~, validationPredictions] = ...
            modelFunctions{modelIndex}(currentData);

        if iscategorical(validationPredictions) || ...
                isstring(validationPredictions) || ...
                iscell(validationPredictions)

            validationPredictions = ...
                str2double(string(validationPredictions));
        end

        validationPredictions = ...
            double(validationPredictions(:));

        if numel(validationPredictions) ~= ...
                numel(trueLabels)

            error( ...
                ['Prediction count mismatch for Group %s, ' ...
                 'model %s.'], ...
                currentGroup, ...
                modelNames(modelIndex) ...
            );
        end

        confusionMatrix = confusionmat( ...
            trueLabels, ...
            validationPredictions, ...
            'Order', ...
            (1:numberOfClasses)' ...
        );

        confusionMatrices{ ...
            groupIndex, ...
            modelIndex ...
        } = confusionMatrix;

        truePositive = diag(confusionMatrix);

        falsePositive = ...
            sum(confusionMatrix, 1)' - truePositive;

        falseNegative = ...
            sum(confusionMatrix, 2) - truePositive;

        trueNegative = ...
            sum(confusionMatrix(:)) ...
            - truePositive ...
            - falsePositive ...
            - falseNegative;

        classPrecision = safeDivide( ...
            truePositive, ...
            truePositive + falsePositive ...
        );

        classSensitivity = safeDivide( ...
            truePositive, ...
            truePositive + falseNegative ...
        );

        classSpecificity = safeDivide( ...
            trueNegative, ...
            trueNegative + falsePositive ...
        );

        classF1Score = safeDivide( ...
            2 .* classPrecision .* classSensitivity, ...
            classPrecision + classSensitivity ...
        );

        accuracyPercent = ...
            100 * sum(truePositive) / ...
            sum(confusionMatrix(:));

        averagePrecision = mean(classPrecision);
        averageSensitivity = mean(classSensitivity);
        averageF1Score = mean(classF1Score);

        summaryGroup(summaryRow) = currentGroup;

        summaryClassifier(summaryRow) = ...
            modelNames(modelIndex);

        accuracyPercentColumn(summaryRow) = ...
            accuracyPercent;

        averagePrecisionColumn(summaryRow) = ...
            averagePrecision;

        averageSensitivityColumn(summaryRow) = ...
            averageSensitivity;

        averageF1ScoreColumn(summaryRow) = ...
            averageF1Score;

        articleAccuracyColumn(summaryRow) = ...
            articleAccuracyPercent( ...
                groupIndex, ...
                modelIndex ...
            );

        articlePrecisionColumn(summaryRow) = ...
            articleAveragePrecision( ...
                groupIndex, ...
                modelIndex ...
            );

        articleSensitivityColumn(summaryRow) = ...
            articleAverageSensitivity( ...
                groupIndex, ...
                modelIndex ...
            );

        accuracyDifferenceColumn(summaryRow) = ...
            accuracyPercent ...
            - articleAccuracyColumn(summaryRow);

        precisionDifferenceColumn(summaryRow) = ...
            averagePrecision ...
            - articlePrecisionColumn(summaryRow);

        sensitivityDifferenceColumn(summaryRow) = ...
            averageSensitivity ...
            - articleSensitivityColumn(summaryRow);

        for classIndex = 1:numberOfClasses

            classRow = classRow + 1;

            classGroup(classRow) = currentGroup;

            classClassifier(classRow) = ...
                modelNames(modelIndex);

            classLabelColumn(classRow) = classIndex;

            truePositiveColumn(classRow) = ...
                truePositive(classIndex);

            falsePositiveColumn(classRow) = ...
                falsePositive(classIndex);

            falseNegativeColumn(classRow) = ...
                falseNegative(classIndex);

            trueNegativeColumn(classRow) = ...
                trueNegative(classIndex);

            classPrecisionColumn(classRow) = ...
                classPrecision(classIndex);

            classSensitivityColumn(classRow) = ...
                classSensitivity(classIndex);

            classSpecificityColumn(classRow) = ...
                classSpecificity(classIndex);

            classF1ScoreColumn(classRow) = ...
                classF1Score(classIndex);
        end

        fprintf( ...
            '%s\n', ...
            modelNames(modelIndex) ...
        );

        fprintf( ...
            'Accuracy: %.3f%%\n', ...
            accuracyPercent ...
        );

        fprintf( ...
            'Average precision: %.6f\n', ...
            averagePrecision ...
        );

        fprintf( ...
            'Average sensitivity: %.6f\n', ...
            averageSensitivity ...
        );

        fprintf('Confusion matrix:\n');
        disp(confusionMatrix);
    end
end

summaryTable = table( ...
    summaryGroup, ...
    summaryClassifier, ...
    accuracyPercentColumn, ...
    averagePrecisionColumn, ...
    averageSensitivityColumn, ...
    averageF1ScoreColumn, ...
    articleAccuracyColumn, ...
    articlePrecisionColumn, ...
    articleSensitivityColumn, ...
    accuracyDifferenceColumn, ...
    precisionDifferenceColumn, ...
    sensitivityDifferenceColumn, ...
    'VariableNames', { ...
        'Group', ...
        'Classifier', ...
        'AccuracyPercent', ...
        'AveragePrecision', ...
        'AverageSensitivity', ...
        'AverageF1Score', ...
        'ArticleAccuracyPercent', ...
        'ArticleAveragePrecision', ...
        'ArticleAverageSensitivity', ...
        'AccuracyDifferencePercent', ...
        'PrecisionDifference', ...
        'SensitivityDifference' ...
    } ...
);

classwiseTable = table( ...
    classGroup, ...
    classClassifier, ...
    classLabelColumn, ...
    truePositiveColumn, ...
    falsePositiveColumn, ...
    falseNegativeColumn, ...
    trueNegativeColumn, ...
    classPrecisionColumn, ...
    classSensitivityColumn, ...
    classSpecificityColumn, ...
    classF1ScoreColumn, ...
    'VariableNames', { ...
        'Group', ...
        'Classifier', ...
        'ClassLabel', ...
        'TruePositive', ...
        'FalsePositive', ...
        'FalseNegative', ...
        'TrueNegative', ...
        'Precision', ...
        'Sensitivity', ...
        'Specificity', ...
        'F1Score' ...
    } ...
);

summaryCsvFile = fullfile( ...
    classificationDirectory, ...
    'TenFold_Precision_Sensitivity_Summary.csv' ...
);

classwiseCsvFile = fullfile( ...
    classificationDirectory, ...
    'TenFold_Classwise_Metrics.csv' ...
);

resultMatFile = fullfile( ...
    classificationDirectory, ...
    'TenFold_Precision_Sensitivity_Results.mat' ...
);

writetable(summaryTable, summaryCsvFile);
writetable(classwiseTable, classwiseCsvFile);

save( ...
    resultMatFile, ...
    'summaryTable', ...
    'classwiseTable', ...
    'confusionMatrices', ...
    'randomSeed' ...
);

fprintf('\n================================================\n');
fprintf('Step 19 completed\n');
fprintf('================================================\n\n');

fprintf('Summary:\n');
disp(summaryTable);

fprintf('\nSummary CSV:\n%s\n', summaryCsvFile);
fprintf('\nClass-wise CSV:\n%s\n', classwiseCsvFile);
fprintf('\nMAT results:\n%s\n', resultMatFile);

function result = safeDivide(numerator, denominator)

    result = zeros(size(numerator));

    validIndices = denominator ~= 0;

    result(validIndices) = ...
        numerator(validIndices) ./ ...
        denominator(validIndices);

    result(~validIndices) = NaN;
end