clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

dataFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'classification_learner', ...
    'GroupA_ClassificationLearner.xlsx' ...
);

if ~isfile(dataFile)
    error( ...
        'Group A Classification Learner file was not found:\n%s', ...
        dataFile ...
    );
end

groupAData = readtable(dataFile);

requiredVariables = {
    'DominantFrequencyHz'
    'ClassLabel'
};

for variableIndex = 1:numel(requiredVariables)

    variableName = requiredVariables{variableIndex};

    if ~ismember( ...
            variableName, ...
            groupAData.Properties.VariableNames ...
        )

        error( ...
            'Required variable was not found: %s', ...
            variableName ...
        );
    end
end

groupAData = groupAData(:, requiredVariables);

if height(groupAData) ~= 240

    error( ...
        'Group A must contain 240 observations, but contains %d.', ...
        height(groupAData) ...
    );
end

if ~isnumeric(groupAData.DominantFrequencyHz)

    error( ...
        'DominantFrequencyHz must be numeric.' ...
    );
end

if ~isnumeric(groupAData.ClassLabel)

    error( ...
        'ClassLabel must be numeric.' ...
    );
end

expectedClasses = [1; 2; 3; 4];

actualClasses = unique(groupAData.ClassLabel);

if ~isequal(actualClasses(:), expectedClasses)

    error( ...
        'ClassLabel must contain classes 1, 2, 3 and 4.' ...
    );
end

classCounts = zeros(4, 1);

for classIndex = 1:4

    classCounts(classIndex) = sum( ...
        groupAData.ClassLabel == classIndex ...
    );
end

if ~isequal(classCounts, [60; 60; 60; 60])

    error( ...
        ['Each Group A class must contain 60 observations. ' ...
         'Current counts are: %d, %d, %d, %d.'], ...
        classCounts(1), ...
        classCounts(2), ...
        classCounts(3), ...
        classCounts(4) ...
    );
end

requiredFunctions = {
    'trainGroupA_FineTree_Holdout'
    'trainGroupA_LDA_Holdout'
    'trainGroupA_SVM_Holdout'
};

for functionIndex = 1:numel(requiredFunctions)

    functionName = requiredFunctions{functionIndex};

    if exist(functionName, 'file') ~= 2

        error( ...
            'Required generated function was not found: %s', ...
            functionName ...
        );
    end
end

numberOfObservations = height(groupAData);
holdoutFraction = 0.20;

expectedTestObservations = round( ...
    holdoutFraction * numberOfObservations ...
);

expectedTrainingObservations = ...
    numberOfObservations - expectedTestObservations;

numberOfRepetitions = 100;

randomSeeds = (1:numberOfRepetitions)';

fineTreeAccuracy = zeros(numberOfRepetitions, 1);
ldaAccuracy = zeros(numberOfRepetitions, 1);
svmAccuracy = zeros(numberOfRepetitions, 1);

fprintf('================================================\n');
fprintf('Step 18: Repeated Group A holdout validation\n');
fprintf('================================================\n\n');

fprintf('Observations: %d\n', numberOfObservations);
fprintf('Classes: 4\n');
fprintf('Observations per class: 60\n');
fprintf('Holdout fraction: %.0f%%\n', 100 * holdoutFraction);

fprintf('Approximate training observations: %d\n', ...
    expectedTrainingObservations);

fprintf('Approximate test observations: %d\n', ...
    expectedTestObservations);

fprintf('Repetitions: %d\n\n', numberOfRepetitions);

for repetition = 1:numberOfRepetitions

    randomSeed = randomSeeds(repetition);

    rng(randomSeed, 'twister');

    [~, currentFineTreeAccuracy] = ...
        trainGroupA_FineTree_Holdout(groupAData);

    rng(randomSeed, 'twister');

    [~, currentLDAAccuracy] = ...
        trainGroupA_LDA_Holdout(groupAData);

    rng(randomSeed, 'twister');

    [~, currentSVMAccuracy] = ...
        trainGroupA_SVM_Holdout(groupAData);

    if currentFineTreeAccuracy <= 1.0001

        currentFineTreeAccuracy = ...
            100 * currentFineTreeAccuracy;
    end

    if currentLDAAccuracy <= 1.0001

        currentLDAAccuracy = ...
            100 * currentLDAAccuracy;
    end

    if currentSVMAccuracy <= 1.0001

        currentSVMAccuracy = ...
            100 * currentSVMAccuracy;
    end

    fineTreeAccuracy(repetition) = ...
        currentFineTreeAccuracy;

    ldaAccuracy(repetition) = ...
        currentLDAAccuracy;

    svmAccuracy(repetition) = ...
        currentSVMAccuracy;

    if mod(repetition, 10) == 0

        fprintf( ...
            'Completed %d of %d repetitions.\n', ...
            repetition, ...
            numberOfRepetitions ...
        );
    end
end

classifier = [
    "Fine Tree"
    "Linear Discriminant"
    "Linear SVM"
];

meanAccuracy = [
    mean(fineTreeAccuracy)
    mean(ldaAccuracy)
    mean(svmAccuracy)
];

standardDeviation = [
    std(fineTreeAccuracy)
    std(ldaAccuracy)
    std(svmAccuracy)
];

medianAccuracy = [
    median(fineTreeAccuracy)
    median(ldaAccuracy)
    median(svmAccuracy)
];

minimumAccuracy = [
    min(fineTreeAccuracy)
    min(ldaAccuracy)
    min(svmAccuracy)
];

maximumAccuracy = [
    max(fineTreeAccuracy)
    max(ldaAccuracy)
    max(svmAccuracy)
];

paperMeanAccuracy = [
    96.74
    97.66
    97.66
];

paperStandardDeviation = [
    2.67
    2.35
    2.35
];

meanDifferenceFromPaper = ...
    meanAccuracy - paperMeanAccuracy;

standardDeviationDifferenceFromPaper = ...
    standardDeviation - paperStandardDeviation;

resultsSummary = table( ...
    classifier, ...
    meanAccuracy, ...
    standardDeviation, ...
    medianAccuracy, ...
    minimumAccuracy, ...
    maximumAccuracy, ...
    paperMeanAccuracy, ...
    paperStandardDeviation, ...
    meanDifferenceFromPaper, ...
    standardDeviationDifferenceFromPaper, ...
    'VariableNames', { ...
        'Classifier', ...
        'MeanAccuracyPercent', ...
        'StandardDeviationPercent', ...
        'MedianAccuracyPercent', ...
        'MinimumAccuracyPercent', ...
        'MaximumAccuracyPercent', ...
        'PaperMeanAccuracyPercent', ...
        'PaperStandardDeviationPercent', ...
        'MeanDifferenceFromPaperPercent', ...
        'StandardDeviationDifferenceFromPaperPercent' ...
    } ...
);

allRepetitions = table( ...
    randomSeeds, ...
    fineTreeAccuracy, ...
    ldaAccuracy, ...
    svmAccuracy, ...
    'VariableNames', { ...
        'RandomSeed', ...
        'FineTreeAccuracyPercent', ...
        'LDAAccuracyPercent', ...
        'SVMAccuracyPercent' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'classification_learner' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

summaryCsvFile = fullfile( ...
    outputDirectory, ...
    'GroupA_RepeatedHoldout_Summary.csv' ...
);

allRunsCsvFile = fullfile( ...
    outputDirectory, ...
    'GroupA_RepeatedHoldout_AllRuns.csv' ...
);

resultMatFile = fullfile( ...
    outputDirectory, ...
    'GroupA_RepeatedHoldout_Results.mat' ...
);

writetable(resultsSummary, summaryCsvFile);
writetable(allRepetitions, allRunsCsvFile);

save( ...
    resultMatFile, ...
    'resultsSummary', ...
    'allRepetitions', ...
    'fineTreeAccuracy', ...
    'ldaAccuracy', ...
    'svmAccuracy', ...
    'randomSeeds', ...
    'numberOfRepetitions', ...
    'holdoutFraction', ...
    'classCounts' ...
);

fprintf('\n================================================\n');
fprintf('Repeated Group A holdout results\n');
fprintf('================================================\n\n');

disp(resultsSummary);

fprintf('\nSummary CSV:\n%s\n', ...
    summaryCsvFile);

fprintf('\nAll repetitions CSV:\n%s\n', ...
    allRunsCsvFile);

fprintf('\nMAT results:\n%s\n', ...
    resultMatFile);