clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

featureFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step03_wavelet_fft_features.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(featureFile)
    error('Step 03 feature file was not found.');
end

configuration = load(configurationFile);

featureData = load( ...
    featureFile, ...
    'dominantFrequencyArray', ...
    'featuresTable', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

dominantFrequencyArray = ...
    featureData.dominantFrequencyArray;

featuresTable = featureData.featuresTable;
subjectIDs = featureData.subjectIDs;
targetFrequencies = featureData.targetFrequencies;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = configuration.numberOfBlocks;

expectedSize = [
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects
];

if ~isequal(size(dominantFrequencyArray), expectedSize)
    error( ...
        ['Unexpected dominantFrequencyArray size.\n' ...
         'Expected: [%s]\n' ...
         'Actual: [%s]'], ...
        num2str(expectedSize), ...
        num2str(size(dominantFrequencyArray)) ...
    );
end

meanDominantFrequencies = zeros( ...
    numberOfSubjects, ...
    numberOfClasses ...
);

standardDeviationFrequencies = zeros( ...
    numberOfSubjects, ...
    numberOfClasses ...
);

for subjectArrayIndex = 1:numberOfSubjects

    for classArrayIndex = 1:numberOfClasses

        blockFrequencies = squeeze( ...
            dominantFrequencyArray( ...
                classArrayIndex, ...
                :, ...
                subjectArrayIndex ...
            ) ...
        );

        meanDominantFrequencies( ...
            subjectArrayIndex, ...
            classArrayIndex ...
        ) = mean(blockFrequencies);

        standardDeviationFrequencies( ...
            subjectArrayIndex, ...
            classArrayIndex ...
        ) = std(blockFrequencies);
    end
end

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)

    matchedIndex = find( ...
        subjectIDs == groupA(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group A subject S%d was not found.', groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)

    matchedIndex = find( ...
        subjectIDs == groupB(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group B subject S%d was not found.', groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

calculatedGroupA = ...
    meanDominantFrequencies(groupAIndices, :);

calculatedGroupB = ...
    meanDominantFrequencies(groupBIndices, :);

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

if ~isequal(size(calculatedGroupA), size(paperGroupA))
    error('Group A table dimensions do not match.');
end

if ~isequal(size(calculatedGroupB), size(paperGroupB))
    error('Group B table dimensions do not match.');
end

differenceGroupA = ...
    calculatedGroupA - paperGroupA;

differenceGroupB = ...
    calculatedGroupB - paperGroupB;

absoluteDifferenceGroupA = abs(differenceGroupA);
absoluteDifferenceGroupB = abs(differenceGroupB);

groupATable = table( ...
    groupA(:), ...
    calculatedGroupA(:, 1), ...
    paperGroupA(:, 1), ...
    differenceGroupA(:, 1), ...
    calculatedGroupA(:, 2), ...
    paperGroupA(:, 2), ...
    differenceGroupA(:, 2), ...
    calculatedGroupA(:, 3), ...
    paperGroupA(:, 3), ...
    differenceGroupA(:, 3), ...
    calculatedGroupA(:, 4), ...
    paperGroupA(:, 4), ...
    differenceGroupA(:, 4), ...
    'VariableNames', { ...
        'SubjectID', ...
        'Calculated9Hz', ...
        'Paper9Hz', ...
        'Difference9Hz', ...
        'Calculated10Hz', ...
        'Paper10Hz', ...
        'Difference10Hz', ...
        'Calculated11Hz', ...
        'Paper11Hz', ...
        'Difference11Hz', ...
        'Calculated12Hz', ...
        'Paper12Hz', ...
        'Difference12Hz' ...
    } ...
);

groupBTable = table( ...
    groupB(:), ...
    calculatedGroupB(:, 1), ...
    paperGroupB(:, 1), ...
    differenceGroupB(:, 1), ...
    calculatedGroupB(:, 2), ...
    paperGroupB(:, 2), ...
    differenceGroupB(:, 2), ...
    calculatedGroupB(:, 3), ...
    paperGroupB(:, 3), ...
    differenceGroupB(:, 3), ...
    calculatedGroupB(:, 4), ...
    paperGroupB(:, 4), ...
    differenceGroupB(:, 4), ...
    'VariableNames', { ...
        'SubjectID', ...
        'Calculated9Hz', ...
        'Paper9Hz', ...
        'Difference9Hz', ...
        'Calculated10Hz', ...
        'Paper10Hz', ...
        'Difference10Hz', ...
        'Calculated11Hz', ...
        'Paper11Hz', ...
        'Difference11Hz', ...
        'Calculated12Hz', ...
        'Paper12Hz', ...
        'Difference12Hz' ...
    } ...
);

allCalculatedValues = [
    calculatedGroupA(:)
    calculatedGroupB(:)
];

allPaperValues = [
    paperGroupA(:)
    paperGroupB(:)
];

allDifferences = ...
    allCalculatedValues - allPaperValues;

meanAbsoluteDifference = ...
    mean(abs(allDifferences));

rootMeanSquaredDifference = ...
    sqrt(mean(allDifferences .^ 2));

maximumAbsoluteDifference = ...
    max(abs(allDifferences));

exactMatchTolerance = 0.051;

numberOfApproximatelyMatchingValues = sum( ...
    abs(allDifferences) <= exactMatchTolerance ...
);

totalNumberOfValues = numel(allDifferences);

matchingPercentage = ...
    100 * numberOfApproximatelyMatchingValues / ...
    totalNumberOfValues;

tablesDirectory = fullfile( ...
    configuration.resultsDirectory, ...
    'tables' ...
);

if ~isfolder(tablesDirectory)
    mkdir(tablesDirectory);
end

groupACsvFile = fullfile( ...
    tablesDirectory, ...
    'step04_groupA_table_comparison.csv' ...
);

groupBCsvFile = fullfile( ...
    tablesDirectory, ...
    'step04_groupB_table_comparison.csv' ...
);

summaryFile = fullfile( ...
    tablesDirectory, ...
    'step04_comparison_summary.mat' ...
);

writetable(groupATable, groupACsvFile);
writetable(groupBTable, groupBCsvFile);

save( ...
    summaryFile, ...
    'meanDominantFrequencies', ...
    'standardDeviationFrequencies', ...
    'calculatedGroupA', ...
    'calculatedGroupB', ...
    'paperGroupA', ...
    'paperGroupB', ...
    'differenceGroupA', ...
    'differenceGroupB', ...
    'meanAbsoluteDifference', ...
    'rootMeanSquaredDifference', ...
    'maximumAbsoluteDifference', ...
    'matchingPercentage' ...
);

fprintf('=============================================\n');
fprintf('Step 04: Reconstruction of Tables 1 and 2\n');
fprintf('=============================================\n\n');

fprintf('Calculated Group A table:\n');
disp(array2table( ...
    [groupA(:), calculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
));

fprintf('Calculated Group B table:\n');
disp(array2table( ...
    [groupB(:), calculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
));

fprintf('---------------------------------------------\n');
fprintf('Comparison with the paper\n');
fprintf('---------------------------------------------\n');

fprintf( ...
    'Mean absolute difference: %.4f Hz\n', ...
    meanAbsoluteDifference ...
);

fprintf( ...
    'Root mean squared difference: %.4f Hz\n', ...
    rootMeanSquaredDifference ...
);

fprintf( ...
    'Maximum absolute difference: %.4f Hz\n', ...
    maximumAbsoluteDifference ...
);

fprintf( ...
    ['Values matching the paper within ' ...
     '%.3f Hz: %d of %d (%.2f%%)\n'], ...
    exactMatchTolerance, ...
    numberOfApproximatelyMatchingValues, ...
    totalNumberOfValues, ...
    matchingPercentage ...
);

fprintf('\nGroup A comparison file:\n%s\n', groupACsvFile);
fprintf('\nGroup B comparison file:\n%s\n', groupBCsvFile);
fprintf('\nSummary MAT file:\n%s\n', summaryFile);