clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz-trials file was not found.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

ozFullTrials = inputData.ozFullTrials;
samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = size(ozFullTrials, 2);
numberOfBlocks = size(ozFullTrials, 3);

windowStartSample = 126;
windowEndSample = 1375;

numberOfWindowSamples = ...
    windowEndSample - windowStartSample + 1;

waveletName = 'db4';
decompositionLevel = 4;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

dwtmode('sym', 'nodisp');

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)
    matchedIndex = find(subjectIDs == groupA(index), 1);

    if isempty(matchedIndex)
        error('Group A subject S%d was not found.', groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)
    matchedIndex = find(subjectIDs == groupB(index), 1);

    if isempty(matchedIndex)
        error('Group B subject S%d was not found.', groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

fprintf('================================================\n');
fprintf('Step 15: FFT-windowing search\n');
fprintf('================================================\n\n');

fprintf('Reconstructing full-trial D4 signals...\n');

d4WindowTrials = zeros( ...
    numberOfWindowSamples, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

for subjectIndex = 1:numberOfSubjects

    fprintf( ...
        'Processing S%d (%d of %d)...\n', ...
        subjectIDs(subjectIndex), ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    for classIndex = 1:numberOfClasses

        for blockIndex = 1:numberOfBlocks

            fullTrial = squeeze( ...
                ozFullTrials( ...
                    :, ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex ...
                ) ...
            );

            fullTrial = double(fullTrial(:));

            [coefficients, bookkeeping] = wavedec( ...
                fullTrial, ...
                decompositionLevel, ...
                waveletName ...
            );

            reconstructedD4 = wrcoef( ...
                'd', ...
                coefficients, ...
                bookkeeping, ...
                waveletName, ...
                decompositionLevel ...
            );

            d4WindowTrials( ...
                :, ...
                classIndex, ...
                blockIndex, ...
                subjectIndex ...
            ) = reconstructedD4( ...
                windowStartSample:windowEndSample ...
            );
        end
    end
end

signalMatrix = reshape( ...
    d4WindowTrials, ...
    numberOfWindowSamples, ...
    [] ...
);

sampleIndex = (0:numberOfWindowSamples - 1)';

rectangularWindow = ones(numberOfWindowSamples, 1);

hannSymmetricWindow = ...
    0.5 - 0.5 * cos( ...
        2 * pi * sampleIndex / ...
        (numberOfWindowSamples - 1) ...
    );

hannPeriodicWindow = ...
    0.5 - 0.5 * cos( ...
        2 * pi * sampleIndex / ...
        numberOfWindowSamples ...
    );

hammingSymmetricWindow = ...
    0.54 - 0.46 * cos( ...
        2 * pi * sampleIndex / ...
        (numberOfWindowSamples - 1) ...
    );

hammingPeriodicWindow = ...
    0.54 - 0.46 * cos( ...
        2 * pi * sampleIndex / ...
        numberOfWindowSamples ...
    );

blackmanWindow = ...
    0.42 ...
    - 0.5 * cos( ...
        2 * pi * sampleIndex / ...
        (numberOfWindowSamples - 1) ...
    ) ...
    + 0.08 * cos( ...
        4 * pi * sampleIndex / ...
        (numberOfWindowSamples - 1) ...
    );

windowNames = [
    "Rectangular"
    "HannSymmetric"
    "HannPeriodic"
    "HammingSymmetric"
    "HammingPeriodic"
    "Blackman"
];

windowVectors = {
    rectangularWindow
    hannSymmetricWindow
    hannPeriodicWindow
    hammingSymmetricWindow
    hammingPeriodicWindow
    blackmanWindow
};

preprocessingNames = [
    "None"
    "RemoveMean"
    "LinearDetrend"
];

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

frequencyMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = frequencyAxis(frequencyMask);

numberOfVariants = ...
    numel(windowNames) * numel(preprocessingNames);

windowNameColumn = strings(numberOfVariants, 1);
preprocessingColumn = strings(numberOfVariants, 1);

overallMADColumn = zeros(numberOfVariants, 1);
groupAMADColumn = zeros(numberOfVariants, 1);
groupBMADColumn = zeros(numberOfVariants, 1);
rmseColumn = zeros(numberOfVariants, 1);
maximumDifferenceColumn = zeros(numberOfVariants, 1);
matchingPercentageColumn = zeros(numberOfVariants, 1);

matchingTolerance = 0.051;

bestScore = inf;
bestWindowName = "";
bestPreprocessing = "";
bestMeanFrequencies = [];
bestDominantFrequencyArray = [];

resultIndex = 0;

fprintf('\nTesting %d FFT preprocessing variants...\n\n', ...
    numberOfVariants);

for preprocessingIndex = 1:numel(preprocessingNames)

    preprocessingName = ...
        preprocessingNames(preprocessingIndex);

    switch preprocessingName

        case "None"
            processedSignalMatrix = signalMatrix;

        case "RemoveMean"
            processedSignalMatrix = ...
                signalMatrix - mean(signalMatrix, 1);

        case "LinearDetrend"
            processedSignalMatrix = detrend(signalMatrix);

        otherwise
            error('Unknown preprocessing method.');
    end

    for windowIndex = 1:numel(windowNames)

        resultIndex = resultIndex + 1;

        currentWindowName = windowNames(windowIndex);
        currentWindow = windowVectors{windowIndex};

        windowedSignalMatrix = ...
            processedSignalMatrix .* currentWindow;

        fftCoefficients = fft( ...
            windowedSignalMatrix, ...
            [], ...
            1 ...
        );

        twoSidedAmplitude = abs( ...
            fftCoefficients / numberOfWindowSamples ...
        );

        oneSidedAmplitude = twoSidedAmplitude( ...
            1:(numberOfWindowSamples / 2 + 1), ...
            : ...
        );

        oneSidedAmplitude(2:end - 1, :) = ...
            2 * oneSidedAmplitude(2:end - 1, :);

        selectedAmplitude = ...
            oneSidedAmplitude(frequencyMask, :);

        [~, maximumIndices] = max( ...
            selectedAmplitude, ...
            [], ...
            1 ...
        );

        dominantFrequencyVector = ...
            searchFrequencies(maximumIndices);

        dominantFrequencyArray = reshape( ...
            dominantFrequencyVector, ...
            numberOfClasses, ...
            numberOfBlocks, ...
            numberOfSubjects ...
        );

        meanFrequencies = squeeze( ...
            mean(dominantFrequencyArray, 2) ...
        )';

        calculatedGroupA = ...
            meanFrequencies(groupAIndices, :);

        calculatedGroupB = ...
            meanFrequencies(groupBIndices, :);

        differenceGroupA = ...
            calculatedGroupA - paperGroupA;

        differenceGroupB = ...
            calculatedGroupB - paperGroupB;

        allDifferences = [
            differenceGroupA(:)
            differenceGroupB(:)
        ];

        overallMAD = mean(abs(allDifferences));
        groupAMAD = mean(abs(differenceGroupA(:)));
        groupBMAD = mean(abs(differenceGroupB(:)));

        rmseValue = sqrt(mean(allDifferences .^ 2));

        maximumDifference = ...
            max(abs(allDifferences));

        matchingPercentage = ...
            100 * sum( ...
                abs(allDifferences) <= matchingTolerance ...
            ) / numel(allDifferences);

        windowNameColumn(resultIndex) = ...
            currentWindowName;

        preprocessingColumn(resultIndex) = ...
            preprocessingName;

        overallMADColumn(resultIndex) = overallMAD;
        groupAMADColumn(resultIndex) = groupAMAD;
        groupBMADColumn(resultIndex) = groupBMAD;
        rmseColumn(resultIndex) = rmseValue;

        maximumDifferenceColumn(resultIndex) = ...
            maximumDifference;

        matchingPercentageColumn(resultIndex) = ...
            matchingPercentage;

        fprintf( ...
            ['Window=%s, preprocessing=%s: ' ...
             'overall MAD=%.4f, Group B MAD=%.4f, ' ...
             'match=%.2f%%\n'], ...
            currentWindowName, ...
            preprocessingName, ...
            overallMAD, ...
            groupBMAD, ...
            matchingPercentage ...
        );

        if overallMAD < bestScore

            bestScore = overallMAD;
            bestWindowName = currentWindowName;
            bestPreprocessing = preprocessingName;

            bestMeanFrequencies = meanFrequencies;

            bestDominantFrequencyArray = ...
                dominantFrequencyArray;
        end
    end
end

resultsTable = table( ...
    windowNameColumn, ...
    preprocessingColumn, ...
    overallMADColumn, ...
    groupAMADColumn, ...
    groupBMADColumn, ...
    rmseColumn, ...
    maximumDifferenceColumn, ...
    matchingPercentageColumn, ...
    'VariableNames', { ...
        'FFTWindow', ...
        'Preprocessing', ...
        'MeanAbsoluteDifferenceHz', ...
        'GroupAMeanAbsoluteDifferenceHz', ...
        'GroupBMeanAbsoluteDifferenceHz', ...
        'RootMeanSquaredDifferenceHz', ...
        'MaximumAbsoluteDifferenceHz', ...
        'MatchingPercentage' ...
    } ...
);

rankedResults = sortrows( ...
    resultsTable, ...
    'MeanAbsoluteDifferenceHz', ...
    'ascend' ...
);

bestCalculatedGroupA = ...
    bestMeanFrequencies(groupAIndices, :);

bestCalculatedGroupB = ...
    bestMeanFrequencies(groupBIndices, :);

bestGroupATable = array2table( ...
    [groupA(:), bestCalculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

bestGroupBTable = array2table( ...
    [groupB(:), bestCalculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'fft_windowing_search' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

resultsCsvFile = fullfile( ...
    outputDirectory, ...
    'step15_fft_windowing_results.csv' ...
);

resultsMatFile = fullfile( ...
    outputDirectory, ...
    'step15_fft_windowing_results.mat' ...
);

groupACsvFile = fullfile( ...
    outputDirectory, ...
    'step15_best_groupA_averages.csv' ...
);

groupBCsvFile = fullfile( ...
    outputDirectory, ...
    'step15_best_groupB_averages.csv' ...
);

writetable(rankedResults, resultsCsvFile);
writetable(bestGroupATable, groupACsvFile);
writetable(bestGroupBTable, groupBCsvFile);

save( ...
    resultsMatFile, ...
    'resultsTable', ...
    'rankedResults', ...
    'bestScore', ...
    'bestWindowName', ...
    'bestPreprocessing', ...
    'bestMeanFrequencies', ...
    'bestDominantFrequencyArray', ...
    'bestCalculatedGroupA', ...
    'bestCalculatedGroupB', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 15 completed\n');
fprintf('================================================\n\n');

fprintf('Best FFT window: %s\n', bestWindowName);
fprintf('Best preprocessing: %s\n', bestPreprocessing);

fprintf('Best overall mean absolute difference: %.4f Hz\n', ...
    bestScore);

fprintf('\nTop variants:\n');

disp(rankedResults( ...
    1:min(15, height(rankedResults)), ...
    : ...
));

fprintf('\nBest Group A averages:\n');
disp(bestGroupATable);

fprintf('\nBest Group B averages:\n');
disp(bestGroupBTable);

fprintf('\nResults CSV:\n%s\n', resultsCsvFile);
fprintf('\nResults MAT:\n%s\n', resultsMatFile);