clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

dataFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'classification_learner', ...
    'ClassificationLearnerData.mat' ...
);

if ~isfile(dataFile)
    error('ClassificationLearnerData.mat was not found.');
end

data = load(dataFile, 'groupBClassificationData');
groupBData = data.groupBClassificationData;

requiredFunctions = {
    'trainGroupB_FineTree_Holdout'
    'trainGroupB_LDA_Holdout'
    'trainGroupB_SVM_Holdout'
};

for functionIndex = 1:numel(requiredFunctions)

    if exist(requiredFunctions{functionIndex}, 'file') ~= 2
        error( ...
            'Generated function was not found: %s', ...
            requiredFunctions{functionIndex} ...
        );
    end
end

numberOfRepetitions = 100;

fineTreeAccuracy = zeros(numberOfRepetitions, 1);
ldaAccuracy = zeros(numberOfRepetitions, 1);
svmAccuracy = zeros(numberOfRepetitions, 1);

fprintf('=============================================\n');
fprintf('Repeated Group B holdout validation\n');
fprintf('=============================================\n');

for repetition = 1:numberOfRepetitions

    randomSeed = repetition;

    rng(randomSeed, 'twister');

    [~, fineTreeValidationAccuracy] = ...
        trainGroupB_FineTree_Holdout(groupBData);

    rng(randomSeed, 'twister');

    [~, ldaValidationAccuracy] = ...
        trainGroupB_LDA_Holdout(groupBData);

    rng(randomSeed, 'twister');

    [~, svmValidationAccuracy] = ...
        trainGroupB_SVM_Holdout(groupBData);

    fineTreeAccuracy(repetition) = ...
        100 * fineTreeValidationAccuracy;

    ldaAccuracy(repetition) = ...
        100 * ldaValidationAccuracy;

    svmAccuracy(repetition) = ...
        100 * svmValidationAccuracy;

    if mod(repetition, 10) == 0
        fprintf( ...
            'Completed %d of %d repetitions.\n', ...
            repetition, ...
            numberOfRepetitions ...
        );
    end
end

classifier = [
    "Fine Tree"
    "Linear Discriminant"
    "Linear SVM"
];

meanAccuracy = [
    mean(fineTreeAccuracy)
    mean(ldaAccuracy)
    mean(svmAccuracy)
];

standardDeviation = [
    std(fineTreeAccuracy)
    std(ldaAccuracy)
    std(svmAccuracy)
];

minimumAccuracy = [
    min(fineTreeAccuracy)
    min(ldaAccuracy)
    min(svmAccuracy)
];

maximumAccuracy = [
    max(fineTreeAccuracy)
    max(ldaAccuracy)
    max(svmAccuracy)
];

paperMeanAccuracy = [
    90.46
    91.60
    92.68
];

paperStandardDeviation = [
    2.22
    0.82
    0.67
];

meanDifferenceFromPaper = ...
    meanAccuracy - paperMeanAccuracy;

resultsSummary = table( ...
    classifier, ...
    meanAccuracy, ...
    standardDeviation, ...
    minimumAccuracy, ...
    maximumAccuracy, ...
    paperMeanAccuracy, ...
    paperStandardDeviation, ...
    meanDifferenceFromPaper, ...
    'VariableNames', { ...
        'Classifier', ...
        'MeanAccuracyPercent', ...
        'StandardDeviationPercent', ...
        'MinimumAccuracyPercent', ...
        'MaximumAccuracyPercent', ...
        'PaperMeanAccuracyPercent', ...
        'PaperStandardDeviationPercent', ...
        'MeanDifferenceFromPaperPercent' ...
    } ...
);

allRepetitions = table( ...
    (1:numberOfRepetitions)', ...
    fineTreeAccuracy, ...
    ldaAccuracy, ...
    svmAccuracy, ...
    'VariableNames', { ...
        'RandomSeed', ...
        'FineTreeAccuracyPercent', ...
        'LDAAccuracyPercent', ...
        'SVMAccuracyPercent' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'classification_learner' ...
);

summaryFile = fullfile( ...
    outputDirectory, ...
    'GroupB_RepeatedHoldout_Summary.csv' ...
);

repetitionsFile = fullfile( ...
    outputDirectory, ...
    'GroupB_RepeatedHoldout_AllRuns.csv' ...
);

matFile = fullfile( ...
    outputDirectory, ...
    'GroupB_RepeatedHoldout_Results.mat' ...
);

writetable(resultsSummary, summaryFile);
writetable(allRepetitions, repetitionsFile);

save( ...
    matFile, ...
    'resultsSummary', ...
    'allRepetitions', ...
    'fineTreeAccuracy', ...
    'ldaAccuracy', ...
    'svmAccuracy', ...
    'numberOfRepetitions' ...
);

fprintf('\n=============================================\n');
fprintf('Repeated holdout results\n');
fprintf('=============================================\n\n');

disp(resultsSummary);

fprintf('\nSummary CSV:\n%s\n', summaryFile);
fprintf('\nAll repetitions CSV:\n%s\n', repetitionsFile);
fprintf('\nMAT results:\n%s\n', matFile);