clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz-trials file was not found.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'trialMetadata', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

ozFullTrials = inputData.ozFullTrials;
trialMetadata = inputData.trialMetadata;
samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = configuration.numberOfBlocks;

windowStartSample = 126;
windowEndSample = 1375;
numberOfWindowSamples = ...
    windowEndSample - windowStartSample + 1;

waveletName = 'db4';
decompositionLevel = 4;

dwtmode('sym', 'nodisp');

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)

    matchedIndex = find( ...
        subjectIDs == groupA(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group A subject S%d was not found.', groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)

    matchedIndex = find( ...
        subjectIDs == groupB(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group B subject S%d was not found.', groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

fprintf('================================================\n');
fprintf('Step 09: FFT frequency-range search\n');
fprintf('================================================\n\n');

fprintf('Wavelet: %s\n', waveletName);
fprintf('Wavelet level: %d\n', decompositionLevel);
fprintf('Processing: Full-trial DWT, then crop\n');
fprintf('Window: %d:%d\n\n', ...
    windowStartSample, ...
    windowEndSample ...
);

fprintf('Reconstructing D4 and computing FFT spectra...\n');

fullD4Trials = zeros(size(ozFullTrials));

for subjectIndex = 1:numberOfSubjects

    fprintf( ...
        'Processing S%d (%d of %d)...\n', ...
        subjectIDs(subjectIndex), ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    for classIndex = 1:numberOfClasses

        for blockIndex = 1:numberOfBlocks

            fullTrial = squeeze( ...
                ozFullTrials( ...
                    :, ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex ...
                ) ...
            );

            fullTrial = double(fullTrial(:));

            [coefficients, bookkeeping] = wavedec( ...
                fullTrial, ...
                decompositionLevel, ...
                waveletName ...
            );

            reconstructedD4 = wrcoef( ...
                'd', ...
                coefficients, ...
                bookkeeping, ...
                waveletName, ...
                decompositionLevel ...
            );

            fullD4Trials( ...
                :, ...
                classIndex, ...
                blockIndex, ...
                subjectIndex ...
            ) = reconstructedD4(:);
        end
    end
end

d4WindowTrials = fullD4Trials( ...
    windowStartSample:windowEndSample, ...
    :, ...
    :, ...
    : ...
);

d4WindowMatrix = reshape( ...
    d4WindowTrials, ...
    numberOfWindowSamples, ...
    [] ...
);

fftCoefficients = fft(d4WindowMatrix, [], 1);

twoSidedAmplitude = abs( ...
    fftCoefficients / numberOfWindowSamples ...
);

oneSidedAmplitude = twoSidedAmplitude( ...
    1:(numberOfWindowSamples / 2 + 1), ...
    : ...
);

oneSidedAmplitude(2:end - 1, :) = ...
    2 * oneSidedAmplitude(2:end - 1, :);

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

candidateLowerBounds = 7.8:0.2:9.0;
candidateUpperBounds = 12.0:0.2:15.6;

numberOfCandidates = ...
    numel(candidateLowerBounds) * ...
    numel(candidateUpperBounds);

lowerBoundColumn = zeros(numberOfCandidates, 1);
upperBoundColumn = zeros(numberOfCandidates, 1);

meanAbsoluteDifferenceColumn = zeros(numberOfCandidates, 1);
groupAMeanAbsoluteDifferenceColumn = zeros(numberOfCandidates, 1);
groupBMeanAbsoluteDifferenceColumn = zeros(numberOfCandidates, 1);

rootMeanSquaredDifferenceColumn = zeros(numberOfCandidates, 1);
maximumAbsoluteDifferenceColumn = zeros(numberOfCandidates, 1);
matchingPercentageColumn = zeros(numberOfCandidates, 1);

matchingTolerance = 0.051;

resultIndex = 0;

bestOverallScore = inf;
bestOverallLowerBound = NaN;
bestOverallUpperBound = NaN;
bestOverallDominantFrequencyArray = [];
bestOverallMeanFrequencies = [];

bestGroupBScore = inf;
bestGroupBLowerBound = NaN;
bestGroupBUpperBound = NaN;

fprintf('\nTesting %d frequency ranges...\n', ...
    numberOfCandidates);

for lowerIndex = 1:numel(candidateLowerBounds)

    lowerBound = candidateLowerBounds(lowerIndex);

    for upperIndex = 1:numel(candidateUpperBounds)

        upperBound = candidateUpperBounds(upperIndex);

        resultIndex = resultIndex + 1;

        frequencyMask = ...
            frequencyAxis >= lowerBound - 1e-10 & ...
            frequencyAxis <= upperBound + 1e-10;

        selectedFrequencies = ...
            frequencyAxis(frequencyMask);

        selectedAmplitudes = ...
            oneSidedAmplitude(frequencyMask, :);

        [~, maximumIndices] = max( ...
            selectedAmplitudes, ...
            [], ...
            1 ...
        );

        dominantFrequencyVector = ...
            selectedFrequencies(maximumIndices);

        dominantFrequencyArray = reshape( ...
            dominantFrequencyVector, ...
            numberOfClasses, ...
            numberOfBlocks, ...
            numberOfSubjects ...
        );

        meanDominantFrequencies = squeeze( ...
            mean(dominantFrequencyArray, 2) ...
        )';

        calculatedGroupA = ...
            meanDominantFrequencies(groupAIndices, :);

        calculatedGroupB = ...
            meanDominantFrequencies(groupBIndices, :);

        differenceGroupA = ...
            calculatedGroupA - paperGroupA;

        differenceGroupB = ...
            calculatedGroupB - paperGroupB;

        allDifferences = [
            differenceGroupA(:)
            differenceGroupB(:)
        ];

        overallMAD = mean(abs(allDifferences));
        groupAMAD = mean(abs(differenceGroupA(:)));
        groupBMAD = mean(abs(differenceGroupB(:)));

        overallRMSE = sqrt( ...
            mean(allDifferences .^ 2) ...
        );

        maximumDifference = max( ...
            abs(allDifferences) ...
        );

        matchingPercentage = ...
            100 * sum( ...
                abs(allDifferences) <= matchingTolerance ...
            ) / numel(allDifferences);

        lowerBoundColumn(resultIndex) = lowerBound;
        upperBoundColumn(resultIndex) = upperBound;

        meanAbsoluteDifferenceColumn(resultIndex) = ...
            overallMAD;

        groupAMeanAbsoluteDifferenceColumn(resultIndex) = ...
            groupAMAD;

        groupBMeanAbsoluteDifferenceColumn(resultIndex) = ...
            groupBMAD;

        rootMeanSquaredDifferenceColumn(resultIndex) = ...
            overallRMSE;

        maximumAbsoluteDifferenceColumn(resultIndex) = ...
            maximumDifference;

        matchingPercentageColumn(resultIndex) = ...
            matchingPercentage;

        if overallMAD < bestOverallScore

            bestOverallScore = overallMAD;
            bestOverallLowerBound = lowerBound;
            bestOverallUpperBound = upperBound;

            bestOverallDominantFrequencyArray = ...
                dominantFrequencyArray;

            bestOverallMeanFrequencies = ...
                meanDominantFrequencies;
        end

        if groupBMAD < bestGroupBScore

            bestGroupBScore = groupBMAD;
            bestGroupBLowerBound = lowerBound;
            bestGroupBUpperBound = upperBound;
        end
    end
end

resultsTable = table( ...
    lowerBoundColumn, ...
    upperBoundColumn, ...
    meanAbsoluteDifferenceColumn, ...
    groupAMeanAbsoluteDifferenceColumn, ...
    groupBMeanAbsoluteDifferenceColumn, ...
    rootMeanSquaredDifferenceColumn, ...
    maximumAbsoluteDifferenceColumn, ...
    matchingPercentageColumn, ...
    'VariableNames', { ...
        'LowerFrequencyHz', ...
        'UpperFrequencyHz', ...
        'MeanAbsoluteDifferenceHz', ...
        'GroupAMeanAbsoluteDifferenceHz', ...
        'GroupBMeanAbsoluteDifferenceHz', ...
        'RootMeanSquaredDifferenceHz', ...
        'MaximumAbsoluteDifferenceHz', ...
        'MatchingPercentage' ...
    } ...
);

rankedResults = sortrows( ...
    resultsTable, ...
    'MeanAbsoluteDifferenceHz', ...
    'ascend' ...
);

currentRangeResult = resultsTable( ...
    abs(resultsTable.LowerFrequencyHz - 7.8) < 1e-10 & ...
    abs(resultsTable.UpperFrequencyHz - 15.6) < 1e-10, ...
    : ...
);

targetRangeResult = resultsTable( ...
    abs(resultsTable.LowerFrequencyHz - 9.0) < 1e-10 & ...
    abs(resultsTable.UpperFrequencyHz - 12.0) < 1e-10, ...
    : ...
);

bestCalculatedGroupA = ...
    bestOverallMeanFrequencies(groupAIndices, :);

bestCalculatedGroupB = ...
    bestOverallMeanFrequencies(groupBIndices, :);

dominantFrequencyInMetadataOrder = permute( ...
    bestOverallDominantFrequencyArray, ...
    [2, 1, 3] ...
);

dominantFrequencyInMetadataOrder = ...
    dominantFrequencyInMetadataOrder(:);

bestFeaturesTable = trialMetadata;

bestFeaturesTable.DominantFrequencyHz = ...
    dominantFrequencyInMetadataOrder;

groupAClassificationData = bestFeaturesTable( ...
    bestFeaturesTable.Group == "A", ...
    {'DominantFrequencyHz', 'ClassLabel'} ...
);

groupBClassificationData = bestFeaturesTable( ...
    bestFeaturesTable.Group == "B", ...
    {'DominantFrequencyHz', 'ClassLabel'} ...
);

outputDirectory = fullfile( ...
    configuration.resultsDirectory, ...
    'fft_range_search' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

resultsCsvFile = fullfile( ...
    outputDirectory, ...
    'step09_fft_range_search_results.csv' ...
);

resultsMatFile = fullfile( ...
    outputDirectory, ...
    'step09_fft_range_search_results.mat' ...
);

bestGroupACsvFile = fullfile( ...
    outputDirectory, ...
    'step09_best_range_groupA.csv' ...
);

bestGroupBCsvFile = fullfile( ...
    outputDirectory, ...
    'step09_best_range_groupB.csv' ...
);

groupAExcelFile = fullfile( ...
    outputDirectory, ...
    'GroupA_BestFFT_Range_ClassificationLearner.xlsx' ...
);

groupBExcelFile = fullfile( ...
    outputDirectory, ...
    'GroupB_BestFFT_Range_ClassificationLearner.xlsx' ...
);

writetable(rankedResults, resultsCsvFile);

bestGroupATable = array2table( ...
    [groupA(:), bestCalculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

bestGroupBTable = array2table( ...
    [groupB(:), bestCalculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

writetable(bestGroupATable, bestGroupACsvFile);
writetable(bestGroupBTable, bestGroupBCsvFile);

writetable( ...
    groupAClassificationData, ...
    groupAExcelFile ...
);

writetable( ...
    groupBClassificationData, ...
    groupBExcelFile ...
);

save( ...
    resultsMatFile, ...
    'resultsTable', ...
    'rankedResults', ...
    'currentRangeResult', ...
    'targetRangeResult', ...
    'bestOverallScore', ...
    'bestOverallLowerBound', ...
    'bestOverallUpperBound', ...
    'bestGroupBScore', ...
    'bestGroupBLowerBound', ...
    'bestGroupBUpperBound', ...
    'bestOverallDominantFrequencyArray', ...
    'bestOverallMeanFrequencies', ...
    'bestCalculatedGroupA', ...
    'bestCalculatedGroupB', ...
    'bestFeaturesTable', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 09 completed\n');
fprintf('================================================\n\n');

fprintf('Current paper-stated D4 range, 7.8-15.6 Hz:\n');
disp(currentRangeResult);

fprintf('Restricted target range, 9-12 Hz:\n');
disp(targetRangeResult);

fprintf('Best overall FFT range:\n');
fprintf( ...
    'Lower bound: %.1f Hz\n', ...
    bestOverallLowerBound ...
);
fprintf( ...
    'Upper bound: %.1f Hz\n', ...
    bestOverallUpperBound ...
);
fprintf( ...
    'Overall mean absolute difference: %.4f Hz\n', ...
    bestOverallScore ...
);

fprintf('\nBest range based only on Group B:\n');
fprintf( ...
    'Lower bound: %.1f Hz\n', ...
    bestGroupBLowerBound ...
);
fprintf( ...
    'Upper bound: %.1f Hz\n', ...
    bestGroupBUpperBound ...
);
fprintf( ...
    'Group B mean absolute difference: %.4f Hz\n', ...
    bestGroupBScore ...
);

fprintf('\nTop 15 FFT ranges:\n');
disp(rankedResults(1:min(15, height(rankedResults)), :));

fprintf('\nBest Group A averages:\n');
disp(bestGroupATable);

fprintf('\nBest Group B averages:\n');
disp(bestGroupBTable);

fprintf('\nClassification Learner Group A file:\n%s\n', ...
    groupAExcelFile);

fprintf('\nClassification Learner Group B file:\n%s\n', ...
    groupBExcelFile);