clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz trials file was not found.');
end

if exist('wavedec', 'file') ~= 2 || ...
   exist('wrcoef', 'file') ~= 2

    error('Wavelet Toolbox is required.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'trialMetadata', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies', ...
    'targetIndices', ...
    'stimulusStartSample', ...
    'stimulusEndSample' ...
);

ozFullTrials = inputData.ozFullTrials;
trialMetadata = inputData.trialMetadata;

samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;
targetIndices = inputData.targetIndices;

stimulusStartSample = inputData.stimulusStartSample;
stimulusEndSample = inputData.stimulusEndSample;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = configuration.numberOfBlocks;

numberOfFullTrialSamples = size(ozFullTrials, 1);

numberOfWindowSamples = ...
    stimulusEndSample - stimulusStartSample + 1;

expectedFullSize = [
    1500, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects
];

if ~isequal(size(ozFullTrials), expectedFullSize)
    error( ...
        ['Unexpected ozFullTrials dimensions.\n' ...
         'Expected: [%s]\n' ...
         'Actual: [%s]'], ...
        num2str(expectedFullSize), ...
        num2str(size(ozFullTrials)) ...
    );
end

if numberOfWindowSamples ~= 1250
    error( ...
        'The five-second window must contain 1250 samples.' ...
    );
end

waveletName = 'db4';
decompositionLevel = 4;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

dwtmode('sym', 'nodisp');

frequencyResolution = ...
    samplingFrequency / numberOfWindowSamples;

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

frequencySearchMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = ...
    frequencyAxis(frequencySearchMask);

fprintf('================================================\n');
fprintf('Step 05: Full-trial DWT followed by 5-s FFT\n');
fprintf('================================================\n\n');

fprintf('Full trial length: %d samples\n', ...
    numberOfFullTrialSamples);

fprintf('Wavelet decomposition input: 1500 samples\n');

fprintf( ...
    'FFT window: samples %d:%d\n', ...
    stimulusStartSample, ...
    stimulusEndSample ...
);

fprintf('FFT window length: %d samples\n', ...
    numberOfWindowSamples);

fprintf('Wavelet: %s\n', waveletName);
fprintf('Wavelet level: %d\n', decompositionLevel);

fprintf('FFT resolution: %.4f Hz\n', ...
    frequencyResolution);

fprintf( ...
    'Search range: %.1f to %.1f Hz\n\n', ...
    minimumSearchFrequency, ...
    maximumSearchFrequency ...
);

cad4WindowTrials = zeros( ...
    numberOfWindowSamples, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

dominantFrequencyArray = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

dominantAmplitudeArray = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

numberOfTrials = ...
    numberOfSubjects * ...
    numberOfClasses * ...
    numberOfBlocks;

dominantFrequencyVector = zeros(numberOfTrials, 1);
dominantAmplitudeVector = zeros(numberOfTrials, 1);
frequencyErrorVector = zeros(numberOfTrials, 1);

featureRow = 0;

for subjectArrayIndex = 1:numberOfSubjects

    subjectID = subjectIDs(subjectArrayIndex);

    fprintf( ...
        'Processing subject S%d (%d of %d)...\n', ...
        subjectID, ...
        subjectArrayIndex, ...
        numberOfSubjects ...
    );

    for classArrayIndex = 1:numberOfClasses

        stimulusFrequency = ...
            targetFrequencies(classArrayIndex);

        for blockIndex = 1:numberOfBlocks

            featureRow = featureRow + 1;

            fullTrialSignal = squeeze( ...
                ozFullTrials( ...
                    :, ...
                    classArrayIndex, ...
                    blockIndex, ...
                    subjectArrayIndex ...
                ) ...
            );

            fullTrialSignal = ...
                double(fullTrialSignal(:));

            if numel(fullTrialSignal) ~= ...
                    numberOfFullTrialSamples

                error( ...
                    ['Incorrect full trial length for ' ...
                     'S%d, class %d, block %d.'], ...
                    subjectID, ...
                    classArrayIndex, ...
                    blockIndex ...
                );
            end

            if any(~isfinite(fullTrialSignal))
                error( ...
                    ['Invalid values detected for ' ...
                     'S%d, class %d, block %d.'], ...
                    subjectID, ...
                    classArrayIndex, ...
                    blockIndex ...
                );
            end

            [waveletCoefficients, bookkeepingVector] = ...
                wavedec( ...
                    fullTrialSignal, ...
                    decompositionLevel, ...
                    waveletName ...
                );

            fullCad4Signal = wrcoef( ...
                'd', ...
                waveletCoefficients, ...
                bookkeepingVector, ...
                waveletName, ...
                decompositionLevel ...
            );

            fullCad4Signal = ...
                double(fullCad4Signal(:));

            if numel(fullCad4Signal) ~= ...
                    numberOfFullTrialSamples

                error( ...
                    'Unexpected reconstructed Cad4 length.' ...
                );
            end

            cad4Window = fullCad4Signal( ...
                stimulusStartSample:stimulusEndSample ...
            );

            cad4WindowTrials( ...
                :, ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = cad4Window;

            fftCoefficients = fft(cad4Window);

            twoSidedAmplitude = ...
                abs( ...
                    fftCoefficients / ...
                    numberOfWindowSamples ...
                );

            oneSidedAmplitude = ...
                twoSidedAmplitude( ...
                    1:(numberOfWindowSamples / 2 + 1) ...
                );

            oneSidedAmplitude(2:end - 1) = ...
                2 * oneSidedAmplitude(2:end - 1);

            searchAmplitude = ...
                oneSidedAmplitude(frequencySearchMask);

            [maximumAmplitude, localMaximumIndex] = ...
                max(searchAmplitude);

            dominantFrequency = ...
                searchFrequencies(localMaximumIndex);

            dominantFrequencyArray( ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = dominantFrequency;

            dominantAmplitudeArray( ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = maximumAmplitude;

            dominantFrequencyVector(featureRow) = ...
                dominantFrequency;

            dominantAmplitudeVector(featureRow) = ...
                maximumAmplitude;

            frequencyErrorVector(featureRow) = ...
                dominantFrequency - stimulusFrequency;

            if trialMetadata.SubjectID(featureRow) ~= subjectID
                error('Metadata subject order mismatch.');
            end

            if trialMetadata.ClassLabel(featureRow) ~= ...
                    classArrayIndex
                error('Metadata class order mismatch.');
            end

            if trialMetadata.Block(featureRow) ~= blockIndex
                error('Metadata block order mismatch.');
            end
        end
    end
end

featuresTable = trialMetadata;

featuresTable.DominantFrequencyHz = ...
    dominantFrequencyVector;

featuresTable.MaximumFFTAmplitude = ...
    dominantAmplitudeVector;

featuresTable.FrequencyErrorHz = ...
    frequencyErrorVector;

meanDominantFrequencies = squeeze( ...
    mean(dominantFrequencyArray, 2) ...
)';

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)

    matchedIndex = find( ...
        subjectIDs == groupA(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group A subject S%d was not found.', ...
            groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)

    matchedIndex = find( ...
        subjectIDs == groupB(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group B subject S%d was not found.', ...
            groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

calculatedGroupA = ...
    meanDominantFrequencies(groupAIndices, :);

calculatedGroupB = ...
    meanDominantFrequencies(groupBIndices, :);

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

differenceGroupA = ...
    calculatedGroupA - paperGroupA;

differenceGroupB = ...
    calculatedGroupB - paperGroupB;

allDifferences = [
    differenceGroupA(:)
    differenceGroupB(:)
];

meanAbsoluteDifference = ...
    mean(abs(allDifferences));

rootMeanSquaredDifference = ...
    sqrt(mean(allDifferences .^ 2));

maximumAbsoluteDifference = ...
    max(abs(allDifferences));

matchingTolerance = 0.051;

numberOfMatchingValues = sum( ...
    abs(allDifferences) <= matchingTolerance ...
);

totalNumberOfValues = numel(allDifferences);

matchingPercentage = ...
    100 * numberOfMatchingValues / ...
    totalNumberOfValues;

groupAComparisonTable = table( ...
    groupA(:), ...
    calculatedGroupA(:, 1), ...
    paperGroupA(:, 1), ...
    differenceGroupA(:, 1), ...
    calculatedGroupA(:, 2), ...
    paperGroupA(:, 2), ...
    differenceGroupA(:, 2), ...
    calculatedGroupA(:, 3), ...
    paperGroupA(:, 3), ...
    differenceGroupA(:, 3), ...
    calculatedGroupA(:, 4), ...
    paperGroupA(:, 4), ...
    differenceGroupA(:, 4), ...
    'VariableNames', { ...
        'SubjectID', ...
        'Calculated9Hz', ...
        'Paper9Hz', ...
        'Difference9Hz', ...
        'Calculated10Hz', ...
        'Paper10Hz', ...
        'Difference10Hz', ...
        'Calculated11Hz', ...
        'Paper11Hz', ...
        'Difference11Hz', ...
        'Calculated12Hz', ...
        'Paper12Hz', ...
        'Difference12Hz' ...
    } ...
);

groupBComparisonTable = table( ...
    groupB(:), ...
    calculatedGroupB(:, 1), ...
    paperGroupB(:, 1), ...
    differenceGroupB(:, 1), ...
    calculatedGroupB(:, 2), ...
    paperGroupB(:, 2), ...
    differenceGroupB(:, 2), ...
    calculatedGroupB(:, 3), ...
    paperGroupB(:, 3), ...
    differenceGroupB(:, 3), ...
    calculatedGroupB(:, 4), ...
    paperGroupB(:, 4), ...
    differenceGroupB(:, 4), ...
    'VariableNames', { ...
        'SubjectID', ...
        'Calculated9Hz', ...
        'Paper9Hz', ...
        'Difference9Hz', ...
        'Calculated10Hz', ...
        'Paper10Hz', ...
        'Difference10Hz', ...
        'Calculated11Hz', ...
        'Paper11Hz', ...
        'Difference11Hz', ...
        'Calculated12Hz', ...
        'Paper12Hz', ...
        'Difference12Hz' ...
    } ...
);

featureDirectory = fullfile( ...
    configuration.resultsDirectory, ...
    'features' ...
);

tableDirectory = fullfile( ...
    configuration.resultsDirectory, ...
    'tables' ...
);

if ~isfolder(featureDirectory)
    mkdir(featureDirectory);
end

if ~isfolder(tableDirectory)
    mkdir(tableDirectory);
end

outputFeatureMatFile = fullfile( ...
    featureDirectory, ...
    'step05_fulltrial_wavelet_features.mat' ...
);

outputFeatureCsvFile = fullfile( ...
    featureDirectory, ...
    'step05_fulltrial_wavelet_features.csv' ...
);

outputGroupACsvFile = fullfile( ...
    tableDirectory, ...
    'step05_groupA_comparison.csv' ...
);

outputGroupBCsvFile = fullfile( ...
    tableDirectory, ...
    'step05_groupB_comparison.csv' ...
);

save( ...
    outputFeatureMatFile, ...
    'cad4WindowTrials', ...
    'dominantFrequencyArray', ...
    'dominantAmplitudeArray', ...
    'dominantFrequencyVector', ...
    'dominantAmplitudeVector', ...
    'frequencyErrorVector', ...
    'featuresTable', ...
    'meanDominantFrequencies', ...
    'calculatedGroupA', ...
    'calculatedGroupB', ...
    'paperGroupA', ...
    'paperGroupB', ...
    'differenceGroupA', ...
    'differenceGroupB', ...
    'meanAbsoluteDifference', ...
    'rootMeanSquaredDifference', ...
    'maximumAbsoluteDifference', ...
    'matchingPercentage', ...
    'frequencyAxis', ...
    'searchFrequencies', ...
    'waveletName', ...
    'decompositionLevel', ...
    'stimulusStartSample', ...
    'stimulusEndSample', ...
    '-v7.3' ...
);

writetable(featuresTable, outputFeatureCsvFile);

writetable( ...
    groupAComparisonTable, ...
    outputGroupACsvFile ...
);

writetable( ...
    groupBComparisonTable, ...
    outputGroupBCsvFile ...
);

fprintf('\n================================================\n');
fprintf('Step 05 completed\n');
fprintf('================================================\n\n');

fprintf('Calculated Group A table:\n');

disp(array2table( ...
    [groupA(:), calculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
));

fprintf('Comparison with paper:\n');

fprintf( ...
    'Mean absolute difference: %.4f Hz\n', ...
    meanAbsoluteDifference ...
);

fprintf( ...
    'Root mean squared difference: %.4f Hz\n', ...
    rootMeanSquaredDifference ...
);

fprintf( ...
    'Maximum absolute difference: %.4f Hz\n', ...
    maximumAbsoluteDifference ...
);

fprintf( ...
    ['Values matching within %.3f Hz: ' ...
     '%d of %d (%.2f%%)\n'], ...
    matchingTolerance, ...
    numberOfMatchingValues, ...
    totalNumberOfValues, ...
    matchingPercentage ...
);

fprintf('\nFeature MAT file:\n%s\n', ...
    outputFeatureMatFile);

fprintf('\nFeature CSV file:\n%s\n', ...
    outputFeatureCsvFile);

fprintf('\nGroup A comparison:\n%s\n', ...
    outputGroupACsvFile);

fprintf('\nGroup B comparison:\n%s\n', ...
    outputGroupBCsvFile);