clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

configuration = load(configurationFile);

groupA = configuration.groupA;
groupB = configuration.groupB;

subjectIDs = [groupA(:); groupB(:)];
numberOfSubjects = numel(subjectIDs);

datasetDirectory = "";

configurationFields = fieldnames(configuration);

for fieldIndex = 1:numel(configurationFields)

    fieldValue = configuration.( ...
        configurationFields{fieldIndex} ...
    );

    if ischar(fieldValue) || ...
            (isstring(fieldValue) && isscalar(fieldValue))

        candidateDirectory = char(fieldValue);

        if isfolder(candidateDirectory)

            candidateS1 = fullfile( ...
                candidateDirectory, ...
                'S1.mat' ...
            );

            candidateS01 = fullfile( ...
                candidateDirectory, ...
                'S01.mat' ...
            );

            if isfile(candidateS1) || isfile(candidateS01)
                datasetDirectory = string(candidateDirectory);
                break;
            end
        end
    end
end

if strlength(datasetDirectory) == 0

    subjectSearch = dir( ...
        fullfile( ...
            projectDirectory, ...
            '**', ...
            'S1.mat' ...
        ) ...
    );

    if isempty(subjectSearch)

        subjectSearch = dir( ...
            fullfile( ...
                projectDirectory, ...
                '**', ...
                'S01.mat' ...
            ) ...
        );
    end

    if isempty(subjectSearch)
        error('The Benchmark Dataset directory could not be located.');
    end

    datasetDirectory = string(subjectSearch(1).folder);
end

datasetDirectory = char(datasetDirectory);

frequencyFile = fullfile( ...
    datasetDirectory, ...
    'Freq_Phase.mat' ...
);

if ~isfile(frequencyFile)

    frequencySearch = dir( ...
        fullfile( ...
            datasetDirectory, ...
            '**', ...
            'Freq_Phase.mat' ...
        ) ...
    );

    if isempty(frequencySearch)
        error('Freq_Phase.mat could not be located.');
    end

    frequencyFile = fullfile( ...
        frequencySearch(1).folder, ...
        frequencySearch(1).name ...
    );
end

frequencyData = load(frequencyFile);

if ~isfield(frequencyData, 'freqs')
    error('Variable freqs was not found in Freq_Phase.mat.');
end

allStimulusFrequencies = ...
    double(frequencyData.freqs(:));

targetFrequencies = [9, 10, 11, 12];

targetIndices = zeros(1, numel(targetFrequencies));

for frequencyIndex = 1:numel(targetFrequencies)

    matchedIndex = find( ...
        abs( ...
            allStimulusFrequencies - ...
            targetFrequencies(frequencyIndex) ...
        ) < 1e-8, ...
        1 ...
    );

    if isempty(matchedIndex)

        error( ...
            'Target frequency %.1f Hz was not found.', ...
            targetFrequencies(frequencyIndex) ...
        );
    end

    targetIndices(frequencyIndex) = matchedIndex;
end

candidateChannelIndices = 53:64;

candidateChannelNames = [
    "PO7"
    "PO5"
    "PO3"
    "POz"
    "PO4"
    "PO6"
    "PO8"
    "CB1"
    "O1"
    "Oz"
    "O2"
    "CB2"
];

numberOfChannels = numel(candidateChannelIndices);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = 6;

windowStartSample = 126;
windowEndSample = 1375;

numberOfWindowSamples = ...
    windowEndSample - windowStartSample + 1;

samplingFrequency = 250;

waveletName = 'db4';
decompositionLevel = 4;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

dwtmode('sym', 'nodisp');

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

frequencyMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = frequencyAxis(frequencyMask);

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

dominantFrequencyResults = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects, ...
    numberOfChannels ...
);

fprintf('================================================\n');
fprintf('Step 17: Occipital-channel audit\n');
fprintf('================================================\n\n');

fprintf('Dataset directory:\n%s\n\n', datasetDirectory);

fprintf('Verified stimulus mapping:\n');

for classIndex = 1:numberOfClasses

    fprintf( ...
        'Class %d: %.1f Hz -> dataset index %d\n', ...
        classIndex, ...
        targetFrequencies(classIndex), ...
        targetIndices(classIndex) ...
    );
end

fprintf('\nCandidate channels:\n');

for channelCandidateIndex = 1:numberOfChannels

    fprintf( ...
        '%d: %s\n', ...
        candidateChannelIndices(channelCandidateIndex), ...
        candidateChannelNames(channelCandidateIndex) ...
    );
end

fprintf('\n');

for subjectIndex = 1:numberOfSubjects

    subjectID = subjectIDs(subjectIndex);

    subjectFile = fullfile( ...
        datasetDirectory, ...
        sprintf('S%d.mat', subjectID) ...
    );

    if ~isfile(subjectFile)

        subjectFile = fullfile( ...
            datasetDirectory, ...
            sprintf('S%02d.mat', subjectID) ...
        );
    end

    if ~isfile(subjectFile)

        subjectSearch = dir( ...
            fullfile( ...
                datasetDirectory, ...
                '**', ...
                sprintf('S%d.mat', subjectID) ...
            ) ...
        );

        if isempty(subjectSearch)

            subjectSearch = dir( ...
                fullfile( ...
                    datasetDirectory, ...
                    '**', ...
                    sprintf('S%02d.mat', subjectID) ...
                ) ...
            );
        end

        if isempty(subjectSearch)
            error('Subject file S%d was not found.', subjectID);
        end

        subjectFile = fullfile( ...
            subjectSearch(1).folder, ...
            subjectSearch(1).name ...
        );
    end

    loadedSubject = load(subjectFile);

    if isfield(loadedSubject, 'data')

        subjectData = loadedSubject.data;

    else

        loadedFields = fieldnames(loadedSubject);
        subjectData = [];

        for fieldIndex = 1:numel(loadedFields)

            candidateData = loadedSubject.( ...
                loadedFields{fieldIndex} ...
            );

            if isnumeric(candidateData) && ...
                    ndims(candidateData) == 4 && ...
                    size(candidateData, 1) == 64 && ...
                    size(candidateData, 2) == 1500

                subjectData = candidateData;
                break;
            end
        end

        if isempty(subjectData)

            error( ...
                'A valid EEG data variable was not found for S%d.', ...
                subjectID ...
            );
        end
    end

    if size(subjectData, 1) ~= 64 || ...
            size(subjectData, 2) ~= 1500 || ...
            size(subjectData, 4) ~= numberOfBlocks

        error( ...
            'Unexpected data dimensions for S%d.', ...
            subjectID ...
        );
    end

    fprintf( ...
        'Processing S%d (%d of %d)...\n', ...
        subjectID, ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    for channelCandidateIndex = 1:numberOfChannels

        channelIndex = ...
            candidateChannelIndices(channelCandidateIndex);

        for classIndex = 1:numberOfClasses

            datasetFrequencyIndex = ...
                targetIndices(classIndex);

            for blockIndex = 1:numberOfBlocks

                fullTrial = squeeze( ...
                    subjectData( ...
                        channelIndex, ...
                        :, ...
                        datasetFrequencyIndex, ...
                        blockIndex ...
                    ) ...
                );

                fullTrial = double(fullTrial(:));

                [coefficients, bookkeeping] = wavedec( ...
                    fullTrial, ...
                    decompositionLevel, ...
                    waveletName ...
                );

                reconstructedD4 = wrcoef( ...
                    'd', ...
                    coefficients, ...
                    bookkeeping, ...
                    waveletName, ...
                    decompositionLevel ...
                );

                analysisSignal = reconstructedD4( ...
                    windowStartSample:windowEndSample ...
                );

                fftCoefficients = fft(analysisSignal);

                twoSidedAmplitude = abs( ...
                    fftCoefficients / numberOfWindowSamples ...
                );

                oneSidedAmplitude = ...
                    twoSidedAmplitude( ...
                        1:(numberOfWindowSamples / 2 + 1) ...
                    );

                oneSidedAmplitude(2:end - 1) = ...
                    2 * oneSidedAmplitude(2:end - 1);

                selectedAmplitude = ...
                    oneSidedAmplitude(frequencyMask);

                [~, maximumIndex] = max(selectedAmplitude);

                dominantFrequencyResults( ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex, ...
                    channelCandidateIndex ...
                ) = searchFrequencies(maximumIndex);
            end
        end
    end
end

channelIndexColumn = candidateChannelIndices(:);
channelNameColumn = candidateChannelNames(:);

overallMADColumn = zeros(numberOfChannels, 1);
groupAMADColumn = zeros(numberOfChannels, 1);
groupBMADColumn = zeros(numberOfChannels, 1);
rmseColumn = zeros(numberOfChannels, 1);
maximumDifferenceColumn = zeros(numberOfChannels, 1);
matchingPercentageColumn = zeros(numberOfChannels, 1);

matchingTolerance = 0.051;

bestScore = inf;
bestChannelCandidateIndex = NaN;
bestMeanFrequencies = [];

groupAIndices = 1:numel(groupA);

groupBIndices = ...
    (numel(groupA) + 1):numberOfSubjects;

for channelCandidateIndex = 1:numberOfChannels

    currentDominantFrequencies = ...
        dominantFrequencyResults( ...
            :, ...
            :, ...
            :, ...
            channelCandidateIndex ...
        );

    currentMeanFrequencies = squeeze( ...
        mean(currentDominantFrequencies, 2) ...
    )';

    calculatedGroupA = ...
        currentMeanFrequencies(groupAIndices, :);

    calculatedGroupB = ...
        currentMeanFrequencies(groupBIndices, :);

    differenceGroupA = ...
        calculatedGroupA - paperGroupA;

    differenceGroupB = ...
        calculatedGroupB - paperGroupB;

    allDifferences = [
        differenceGroupA(:)
        differenceGroupB(:)
    ];

    overallMAD = mean(abs(allDifferences));
    groupAMAD = mean(abs(differenceGroupA(:)));
    groupBMAD = mean(abs(differenceGroupB(:)));

    rmseValue = sqrt(mean(allDifferences .^ 2));

    maximumDifference = max(abs(allDifferences));

    matchingPercentage = ...
        100 * sum( ...
            abs(allDifferences) <= matchingTolerance ...
        ) / numel(allDifferences);

    overallMADColumn(channelCandidateIndex) = overallMAD;
    groupAMADColumn(channelCandidateIndex) = groupAMAD;
    groupBMADColumn(channelCandidateIndex) = groupBMAD;
    rmseColumn(channelCandidateIndex) = rmseValue;

    maximumDifferenceColumn(channelCandidateIndex) = ...
        maximumDifference;

    matchingPercentageColumn(channelCandidateIndex) = ...
        matchingPercentage;

    if overallMAD < bestScore

        bestScore = overallMAD;

        bestChannelCandidateIndex = ...
            channelCandidateIndex;

        bestMeanFrequencies = ...
            currentMeanFrequencies;
    end
end

resultsTable = table( ...
    channelIndexColumn, ...
    channelNameColumn, ...
    overallMADColumn, ...
    groupAMADColumn, ...
    groupBMADColumn, ...
    rmseColumn, ...
    maximumDifferenceColumn, ...
    matchingPercentageColumn, ...
    'VariableNames', { ...
        'ChannelIndex', ...
        'ChannelName', ...
        'MeanAbsoluteDifferenceHz', ...
        'GroupAMeanAbsoluteDifferenceHz', ...
        'GroupBMeanAbsoluteDifferenceHz', ...
        'RootMeanSquaredDifferenceHz', ...
        'MaximumAbsoluteDifferenceHz', ...
        'MatchingPercentage' ...
    } ...
);

rankedResults = sortrows( ...
    resultsTable, ...
    'MeanAbsoluteDifferenceHz', ...
    'ascend' ...
);

ozResult = resultsTable( ...
    resultsTable.ChannelIndex == 62, ...
    : ...
);

bestChannelIndex = ...
    candidateChannelIndices(bestChannelCandidateIndex);

bestChannelName = ...
    candidateChannelNames(bestChannelCandidateIndex);

bestCalculatedGroupA = ...
    bestMeanFrequencies(groupAIndices, :);

bestCalculatedGroupB = ...
    bestMeanFrequencies(groupBIndices, :);

bestGroupATable = array2table( ...
    [groupA(:), bestCalculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

bestGroupBTable = array2table( ...
    [groupB(:), bestCalculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'channel_audit' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

resultsCsvFile = fullfile( ...
    outputDirectory, ...
    'step17_occipital_channel_results.csv' ...
);

resultsMatFile = fullfile( ...
    outputDirectory, ...
    'step17_occipital_channel_results.mat' ...
);

groupACsvFile = fullfile( ...
    outputDirectory, ...
    'step17_best_channel_groupA.csv' ...
);

groupBCsvFile = fullfile( ...
    outputDirectory, ...
    'step17_best_channel_groupB.csv' ...
);

writetable(rankedResults, resultsCsvFile);
writetable(bestGroupATable, groupACsvFile);
writetable(bestGroupBTable, groupBCsvFile);

save( ...
    resultsMatFile, ...
    'resultsTable', ...
    'rankedResults', ...
    'ozResult', ...
    'dominantFrequencyResults', ...
    'bestScore', ...
    'bestChannelIndex', ...
    'bestChannelName', ...
    'bestMeanFrequencies', ...
    'bestCalculatedGroupA', ...
    'bestCalculatedGroupB', ...
    'targetIndices', ...
    'targetFrequencies', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 17 completed\n');
fprintf('================================================\n\n');

fprintf('Result for the article-stated Oz channel:\n');
disp(ozResult);

fprintf('Ranked occipital channels:\n');
disp(rankedResults);

fprintf('Best channel: %s, index %d\n', ...
    bestChannelName, ...
    bestChannelIndex);

fprintf( ...
    'Best overall mean absolute difference: %.4f Hz\n', ...
    bestScore ...
);

fprintf('\nBest-channel Group A averages:\n');
disp(bestGroupATable);

fprintf('\nBest-channel Group B averages:\n');
disp(bestGroupBTable);

fprintf('\nResults CSV:\n%s\n', resultsCsvFile);
fprintf('\nResults MAT:\n%s\n', resultsMatFile);