clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz-trials file was not found.');
end

if exist('wavedec', 'file') ~= 2 || ...
   exist('wrcoef', 'file') ~= 2

    error('Wavelet Toolbox is required.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

ozFullTrials = inputData.ozFullTrials;
samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = configuration.numberOfBlocks;

numberOfFullTrialSamples = size(ozFullTrials, 1);

windowDurationSeconds = 5;
numberOfWindowSamples = ...
    windowDurationSeconds * samplingFrequency;

maximumWindowStart = ...
    numberOfFullTrialSamples - numberOfWindowSamples + 1;

candidateWindowStarts = 1:maximumWindowStart;
numberOfCandidates = numel(candidateWindowStarts);

expectedSize = [
    1500, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects
];

if ~isequal(size(ozFullTrials), expectedSize)
    error( ...
        ['Unexpected size of ozFullTrials.\n' ...
         'Expected: [%s]\n' ...
         'Actual: [%s]'], ...
        num2str(expectedSize), ...
        num2str(size(ozFullTrials)) ...
    );
end

waveletName = 'db4';
decompositionLevel = 4;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

dwtmode('sym', 'nodisp');

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)

    matchedIndex = find( ...
        subjectIDs == groupA(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Subject S%d was not found.', groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)

    matchedIndex = find( ...
        subjectIDs == groupB(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Subject S%d was not found.', groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

fprintf('================================================\n');
fprintf('Step 07: Five-second window search\n');
fprintf('================================================\n\n');

fprintf('Full trial length: %d samples\n', ...
    numberOfFullTrialSamples);

fprintf('Window length: %d samples\n', ...
    numberOfWindowSamples);

fprintf('Candidate window starts: %d to %d\n', ...
    candidateWindowStarts(1), ...
    candidateWindowStarts(end));

fprintf('Number of candidate windows: %d\n', ...
    numberOfCandidates);

fprintf('Wavelet: %s\n', waveletName);
fprintf('Wavelet level: %d\n', decompositionLevel);
fprintf('Boundary mode: sym\n\n');

fprintf('Reconstructing full-trial D4 components...\n');

fullD4Trials = zeros(size(ozFullTrials));

for subjectIndex = 1:numberOfSubjects

    fprintf( ...
        'D4 reconstruction for S%d (%d of %d)...\n', ...
        subjectIDs(subjectIndex), ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    for classIndex = 1:numberOfClasses

        for blockIndex = 1:numberOfBlocks

            trialSignal = squeeze( ...
                ozFullTrials( ...
                    :, ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex ...
                ) ...
            );

            trialSignal = double(trialSignal(:));

            [waveletCoefficients, bookkeepingVector] = ...
                wavedec( ...
                    trialSignal, ...
                    decompositionLevel, ...
                    waveletName ...
                );

            reconstructedD4 = wrcoef( ...
                'd', ...
                waveletCoefficients, ...
                bookkeepingVector, ...
                waveletName, ...
                decompositionLevel ...
            );

            fullD4Trials( ...
                :, ...
                classIndex, ...
                blockIndex, ...
                subjectIndex ...
            ) = reconstructedD4(:);
        end
    end
end

fullD4Matrix = reshape( ...
    fullD4Trials, ...
    numberOfFullTrialSamples, ...
    [] ...
);

frequencyResolution = ...
    samplingFrequency / numberOfWindowSamples;

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

frequencySearchMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = ...
    frequencyAxis(frequencySearchMask);

meanAbsoluteDifference = zeros(numberOfCandidates, 1);
groupAMeanAbsoluteDifference = zeros(numberOfCandidates, 1);
groupBMeanAbsoluteDifference = zeros(numberOfCandidates, 1);
rootMeanSquaredDifference = zeros(numberOfCandidates, 1);
maximumAbsoluteDifference = zeros(numberOfCandidates, 1);
matchingPercentage = zeros(numberOfCandidates, 1);

matchingTolerance = 0.051;

bestDominantFrequencyArray = [];
bestMeanDominantFrequencies = [];
bestScore = inf;
bestStartSample = NaN;

fprintf('\nSearching all five-second windows...\n');

for candidateIndex = 1:numberOfCandidates

    windowStartSample = ...
        candidateWindowStarts(candidateIndex);

    windowEndSample = ...
        windowStartSample + numberOfWindowSamples - 1;

    windowSignals = fullD4Matrix( ...
        windowStartSample:windowEndSample, ...
        : ...
    );

    fftCoefficients = fft(windowSignals, [], 1);

    twoSidedAmplitude = ...
        abs(fftCoefficients / numberOfWindowSamples);

    oneSidedAmplitude = ...
        twoSidedAmplitude( ...
            1:(numberOfWindowSamples / 2 + 1), ...
            : ...
        );

    oneSidedAmplitude(2:end - 1, :) = ...
        2 * oneSidedAmplitude(2:end - 1, :);

    searchAmplitude = ...
        oneSidedAmplitude(frequencySearchMask, :);

    [~, maximumIndices] = max(searchAmplitude, [], 1);

    dominantFrequencyVector = ...
        searchFrequencies(maximumIndices);

    dominantFrequencyArray = reshape( ...
        dominantFrequencyVector, ...
        numberOfClasses, ...
        numberOfBlocks, ...
        numberOfSubjects ...
    );

    meanDominantFrequencies = squeeze( ...
        mean(dominantFrequencyArray, 2) ...
    )';

    calculatedGroupA = ...
        meanDominantFrequencies(groupAIndices, :);

    calculatedGroupB = ...
        meanDominantFrequencies(groupBIndices, :);

    differenceGroupA = ...
        calculatedGroupA - paperGroupA;

    differenceGroupB = ...
        calculatedGroupB - paperGroupB;

    allDifferences = [
        differenceGroupA(:)
        differenceGroupB(:)
    ];

    groupAMeanAbsoluteDifference(candidateIndex) = ...
        mean(abs(differenceGroupA(:)));

    groupBMeanAbsoluteDifference(candidateIndex) = ...
        mean(abs(differenceGroupB(:)));

    meanAbsoluteDifference(candidateIndex) = ...
        mean(abs(allDifferences));

    rootMeanSquaredDifference(candidateIndex) = ...
        sqrt(mean(allDifferences .^ 2));

    maximumAbsoluteDifference(candidateIndex) = ...
        max(abs(allDifferences));

    matchingPercentage(candidateIndex) = ...
        100 * sum( ...
            abs(allDifferences) <= matchingTolerance ...
        ) / numel(allDifferences);

    if meanAbsoluteDifference(candidateIndex) < bestScore

        bestScore = ...
            meanAbsoluteDifference(candidateIndex);

        bestStartSample = windowStartSample;

        bestDominantFrequencyArray = ...
            dominantFrequencyArray;

        bestMeanDominantFrequencies = ...
            meanDominantFrequencies;
    end

    if mod(candidateIndex, 25) == 0 || ...
       candidateIndex == numberOfCandidates

        fprintf( ...
            'Completed %d of %d candidate windows.\n', ...
            candidateIndex, ...
            numberOfCandidates ...
        );
    end
end

windowEndSamples = ...
    candidateWindowStarts' + numberOfWindowSamples - 1;

windowStartTimeFromEpochSeconds = ...
    (candidateWindowStarts' - 1) / samplingFrequency;

windowStartTimeRelativeToStimulusSeconds = ...
    (candidateWindowStarts' - 126) / samplingFrequency;

searchResults = table( ...
    candidateWindowStarts', ...
    windowEndSamples, ...
    windowStartTimeFromEpochSeconds, ...
    windowStartTimeRelativeToStimulusSeconds, ...
    meanAbsoluteDifference, ...
    groupAMeanAbsoluteDifference, ...
    groupBMeanAbsoluteDifference, ...
    rootMeanSquaredDifference, ...
    maximumAbsoluteDifference, ...
    matchingPercentage, ...
    'VariableNames', { ...
        'StartSample', ...
        'EndSample', ...
        'StartTimeFromEpochSeconds', ...
        'StartTimeRelativeToStimulusSeconds', ...
        'MeanAbsoluteDifferenceHz', ...
        'GroupAMeanAbsoluteDifferenceHz', ...
        'GroupBMeanAbsoluteDifferenceHz', ...
        'RootMeanSquaredDifferenceHz', ...
        'MaximumAbsoluteDifferenceHz', ...
        'MatchingPercentage' ...
    } ...
);

[~, rankingOrder] = sort( ...
    searchResults.MeanAbsoluteDifferenceHz, ...
    'ascend' ...
);

rankedResults = searchResults(rankingOrder, :);

originalWindowRow = searchResults( ...
    searchResults.StartSample == 126, ...
    : ...
);

bestEndSample = ...
    bestStartSample + numberOfWindowSamples - 1;

bestCalculatedGroupA = ...
    bestMeanDominantFrequencies(groupAIndices, :);

bestCalculatedGroupB = ...
    bestMeanDominantFrequencies(groupBIndices, :);

outputDirectory = fullfile( ...
    configuration.resultsDirectory, ...
    'window_search' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

outputCsvFile = fullfile( ...
    outputDirectory, ...
    'step07_window_search_results.csv' ...
);

outputMatFile = fullfile( ...
    outputDirectory, ...
    'step07_window_search_results.mat' ...
);

bestGroupACsvFile = fullfile( ...
    outputDirectory, ...
    'step07_best_window_groupA.csv' ...
);

bestGroupBCsvFile = fullfile( ...
    outputDirectory, ...
    'step07_best_window_groupB.csv' ...
);

writetable(rankedResults, outputCsvFile);

bestGroupATable = array2table( ...
    [groupA(:), bestCalculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

bestGroupBTable = array2table( ...
    [groupB(:), bestCalculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

writetable(bestGroupATable, bestGroupACsvFile);
writetable(bestGroupBTable, bestGroupBCsvFile);

save( ...
    outputMatFile, ...
    'searchResults', ...
    'rankedResults', ...
    'bestStartSample', ...
    'bestEndSample', ...
    'bestDominantFrequencyArray', ...
    'bestMeanDominantFrequencies', ...
    'bestCalculatedGroupA', ...
    'bestCalculatedGroupB', ...
    'paperGroupA', ...
    'paperGroupB', ...
    'waveletName', ...
    'decompositionLevel', ...
    'matchingTolerance', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 07 completed\n');
fprintf('================================================\n\n');

fprintf('Original window 126:1375:\n');
disp(originalWindowRow);

fprintf('Best window found:\n');
fprintf('Start sample: %d\n', bestStartSample);
fprintf('End sample: %d\n', bestEndSample);

fprintf( ...
    'Start time from epoch beginning: %.4f s\n', ...
    (bestStartSample - 1) / samplingFrequency ...
);

fprintf( ...
    'Start time relative to stimulus onset: %.4f s\n', ...
    (bestStartSample - 126) / samplingFrequency ...
);

fprintf('\nTop 15 candidate windows:\n');
disp(rankedResults(1:min(15, height(rankedResults)), :));

fprintf('\nBest Group A averages:\n');
disp(bestGroupATable);

fprintf('\nBest Group B averages:\n');
disp(bestGroupBTable);

fprintf('\nResults CSV:\n%s\n', outputCsvFile);
fprintf('\nResults MAT:\n%s\n', outputMatFile);