clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

featureFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step05_fulltrial_wavelet_features.mat' ...
);

if ~isfile(featureFile)
    error('Step 05 feature file was not found.');
end

featureData = load(featureFile, 'featuresTable');
featuresTable = featureData.featuresTable;

requiredVariables = {
    'Group'
    'ClassLabel'
    'DominantFrequencyHz'
};

for variableIndex = 1:numel(requiredVariables)

    if ~ismember( ...
            requiredVariables{variableIndex}, ...
            featuresTable.Properties.VariableNames ...
        )

        error( ...
            'Required variable was not found: %s', ...
            requiredVariables{variableIndex} ...
        );
    end
end

groupAClassificationData = featuresTable( ...
    featuresTable.Group == "A", ...
    {'DominantFrequencyHz', 'ClassLabel'} ...
);

groupBClassificationData = featuresTable( ...
    featuresTable.Group == "B", ...
    {'DominantFrequencyHz', 'ClassLabel'} ...
);

if height(groupAClassificationData) ~= 240
    error( ...
        'Group A must contain 240 observations, but contains %d.', ...
        height(groupAClassificationData) ...
    );
end

if height(groupBClassificationData) ~= 432
    error( ...
        'Group B must contain 432 observations, but contains %d.', ...
        height(groupBClassificationData) ...
    );
end

if any(~isfinite(groupAClassificationData.DominantFrequencyHz))
    error('Group A contains invalid feature values.');
end

if any(~isfinite(groupBClassificationData.DominantFrequencyHz))
    error('Group B contains invalid feature values.');
end

expectedClasses = [1, 2, 3, 4];

if ~isequal( ...
        unique(groupAClassificationData.ClassLabel)', ...
        expectedClasses ...
    )

    error('Group A class labels are incorrect.');
end

if ~isequal( ...
        unique(groupBClassificationData.ClassLabel)', ...
        expectedClasses ...
    )

    error('Group B class labels are incorrect.');
end

classificationDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'classification_learner' ...
);

if ~isfolder(classificationDirectory)
    mkdir(classificationDirectory);
end

groupAExcelFile = fullfile( ...
    classificationDirectory, ...
    'GroupA_ClassificationLearner.xlsx' ...
);

groupBExcelFile = fullfile( ...
    classificationDirectory, ...
    'GroupB_ClassificationLearner.xlsx' ...
);

workspaceFile = fullfile( ...
    classificationDirectory, ...
    'ClassificationLearnerData.mat' ...
);

writetable( ...
    groupAClassificationData, ...
    groupAExcelFile, ...
    'Sheet', ...
    'GroupA' ...
);

writetable( ...
    groupBClassificationData, ...
    groupBExcelFile, ...
    'Sheet', ...
    'GroupB' ...
);

save( ...
    workspaceFile, ...
    'groupAClassificationData', ...
    'groupBClassificationData' ...
);

fprintf('================================================\n');
fprintf('Classification Learner data prepared\n');
fprintf('================================================\n\n');

fprintf('Group A observations: %d\n', ...
    height(groupAClassificationData));

fprintf('Group B observations: %d\n', ...
    height(groupBClassificationData));

fprintf('\nGroup A class counts:\n');

for classIndex = 1:4
    fprintf( ...
        'Class %d: %d\n', ...
        classIndex, ...
        sum(groupAClassificationData.ClassLabel == classIndex) ...
    );
end

fprintf('\nGroup B class counts:\n');

for classIndex = 1:4
    fprintf( ...
        'Class %d: %d\n', ...
        classIndex, ...
        sum(groupBClassificationData.ClassLabel == classIndex) ...
    );
end

fprintf('\nGroup A Excel file:\n%s\n', groupAExcelFile);
fprintf('\nGroup B Excel file:\n%s\n', groupBExcelFile);
fprintf('\nWorkspace MAT file:\n%s\n', workspaceFile);