clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz-trials file was not found.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

ozFullTrials = inputData.ozFullTrials;
samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = size(ozFullTrials, 2);
numberOfBlocks = size(ozFullTrials, 3);

windowStartSample = 126;
windowEndSample = 1375;

numberOfWindowSamples = ...
    windowEndSample - windowStartSample + 1;

waveletName = 'db4';
decompositionLevel = 4;
boundaryMode = 'sym';

dwtmode(boundaryMode, 'nodisp');

firstSignal = squeeze( ...
    ozFullTrials( ...
        windowStartSample:windowEndSample, ...
        1, ...
        1, ...
        1 ...
    ) ...
);

firstSignal = double(firstSignal(:));

[firstCoefficients, firstBookkeeping] = wavedec( ...
    firstSignal, ...
    decompositionLevel, ...
    waveletName ...
);

firstD4 = detcoef( ...
    firstCoefficients, ...
    firstBookkeeping, ...
    decompositionLevel ...
);

firstD4 = double(firstD4(:));

numberOfD4Coefficients = numel(firstD4);

numberOfTrials = ...
    numberOfSubjects * ...
    numberOfClasses * ...
    numberOfBlocks;

cad4PredictorMatrix = zeros( ...
    numberOfTrials, ...
    numberOfD4Coefficients ...
);

classLabelVector = zeros(numberOfTrials, 1);
subjectIDVector = zeros(numberOfTrials, 1);
blockVector = zeros(numberOfTrials, 1);
targetFrequencyVector = zeros(numberOfTrials, 1);
groupVector = strings(numberOfTrials, 1);

fprintf('================================================\n');
fprintf('Step 14: Cad4 coefficient-vector extraction\n');
fprintf('================================================\n\n');

fprintf('Sampling frequency: %.1f Hz\n', samplingFrequency);

fprintf('Window: %d:%d\n', ...
    windowStartSample, ...
    windowEndSample ...
);

fprintf('Window duration: %.2f s\n', ...
    numberOfWindowSamples / samplingFrequency ...
);

fprintf('Wavelet: %s\n', waveletName);
fprintf('Decomposition level: %d\n', decompositionLevel);
fprintf('Boundary mode: %s\n', boundaryMode);

fprintf('Number of Cad4 coefficients per trial: %d\n\n', ...
    numberOfD4Coefficients);

rowIndex = 0;

for subjectIndex = 1:numberOfSubjects

    subjectID = subjectIDs(subjectIndex);

    fprintf( ...
        'Processing S%d (%d of %d)...\n', ...
        subjectID, ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    if ismember(subjectID, groupA)
        currentGroup = "A";
    elseif ismember(subjectID, groupB)
        currentGroup = "B";
    else
        error('Subject S%d does not belong to either group.', subjectID);
    end

    for classIndex = 1:numberOfClasses

        for blockIndex = 1:numberOfBlocks

            rowIndex = rowIndex + 1;

            stimulusSignal = squeeze( ...
                ozFullTrials( ...
                    windowStartSample:windowEndSample, ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex ...
                ) ...
            );

            stimulusSignal = double(stimulusSignal(:));

            [coefficients, bookkeeping] = wavedec( ...
                stimulusSignal, ...
                decompositionLevel, ...
                waveletName ...
            );

            d4Coefficients = detcoef( ...
                coefficients, ...
                bookkeeping, ...
                decompositionLevel ...
            );

            d4Coefficients = double(d4Coefficients(:));

            if numel(d4Coefficients) ~= numberOfD4Coefficients

                error( ...
                    ['Unexpected Cad4 length for S%d, class %d, ' ...
                     'block %d. Expected %d but received %d.'], ...
                    subjectID, ...
                    classIndex, ...
                    blockIndex, ...
                    numberOfD4Coefficients, ...
                    numel(d4Coefficients) ...
                );
            end

            cad4PredictorMatrix(rowIndex, :) = ...
                d4Coefficients';

            classLabelVector(rowIndex) = classIndex;
            subjectIDVector(rowIndex) = subjectID;
            blockVector(rowIndex) = blockIndex;

            targetFrequencyVector(rowIndex) = ...
                targetFrequencies(classIndex);

            groupVector(rowIndex) = currentGroup;
        end
    end
end

coefficientVariableNames = cell( ...
    1, ...
    numberOfD4Coefficients ...
);

for coefficientIndex = 1:numberOfD4Coefficients

    coefficientVariableNames{coefficientIndex} = ...
        sprintf('D4_%03d', coefficientIndex);
end

cad4ClassificationTable = array2table( ...
    cad4PredictorMatrix, ...
    'VariableNames', coefficientVariableNames ...
);

cad4ClassificationTable.ClassLabel = ...
    classLabelVector;

groupAMask = groupVector == "A";
groupBMask = groupVector == "B";

groupAClassificationData = ...
    cad4ClassificationTable(groupAMask, :);

groupBClassificationData = ...
    cad4ClassificationTable(groupBMask, :);

metadataTable = table( ...
    subjectIDVector, ...
    groupVector, ...
    blockVector, ...
    classLabelVector, ...
    targetFrequencyVector, ...
    'VariableNames', { ...
        'SubjectID', ...
        'Group', ...
        'Block', ...
        'ClassLabel', ...
        'TargetFrequencyHz' ...
    } ...
);

if height(groupAClassificationData) ~= 240
    error( ...
        'Group A must contain 240 trials, but contains %d.', ...
        height(groupAClassificationData) ...
    );
end

if height(groupBClassificationData) ~= 432
    error( ...
        'Group B must contain 432 trials, but contains %d.', ...
        height(groupBClassificationData) ...
    );
end

for classIndex = 1:numberOfClasses

    groupAClassCount = sum( ...
        groupAClassificationData.ClassLabel == classIndex ...
    );

    groupBClassCount = sum( ...
        groupBClassificationData.ClassLabel == classIndex ...
    );

    if groupAClassCount ~= 60
        error( ...
            'Group A class %d must contain 60 trials.', ...
            classIndex ...
        );
    end

    if groupBClassCount ~= 108
        error( ...
            'Group B class %d must contain 108 trials.', ...
            classIndex ...
        );
    end
end

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'cad4_coefficient_vectors' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

groupAExcelFile = fullfile( ...
    outputDirectory, ...
    'GroupA_Cad4Vector_ClassificationLearner.xlsx' ...
);

groupBExcelFile = fullfile( ...
    outputDirectory, ...
    'GroupB_Cad4Vector_ClassificationLearner.xlsx' ...
);

metadataCsvFile = fullfile( ...
    outputDirectory, ...
    'step14_cad4_vector_metadata.csv' ...
);

resultMatFile = fullfile( ...
    outputDirectory, ...
    'step14_cad4_coefficient_vectors.mat' ...
);

writetable( ...
    groupAClassificationData, ...
    groupAExcelFile ...
);

writetable( ...
    groupBClassificationData, ...
    groupBExcelFile ...
);

writetable( ...
    metadataTable, ...
    metadataCsvFile ...
);

save( ...
    resultMatFile, ...
    'cad4PredictorMatrix', ...
    'cad4ClassificationTable', ...
    'groupAClassificationData', ...
    'groupBClassificationData', ...
    'metadataTable', ...
    'numberOfD4Coefficients', ...
    'waveletName', ...
    'decompositionLevel', ...
    'boundaryMode', ...
    'windowStartSample', ...
    'windowEndSample', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 14 completed\n');
fprintf('================================================\n\n');

fprintf('Total trials: %d\n', numberOfTrials);

fprintf('Cad4 predictors per trial: %d\n', ...
    numberOfD4Coefficients);

fprintf('Group A observations: %d\n', ...
    height(groupAClassificationData));

fprintf('Group B observations: %d\n', ...
    height(groupBClassificationData));

fprintf('\nGroup A Excel file:\n%s\n', ...
    groupAExcelFile);

fprintf('\nGroup B Excel file:\n%s\n', ...
    groupBExcelFile);

fprintf('\nMetadata CSV:\n%s\n', ...
    metadataCsvFile);

fprintf('\nMAT results:\n%s\n', ...
    resultMatFile);