clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error( ...
        'Configuration file was not found:\n%s', ...
        configurationFile ...
    );
end

if ~isfile(ozTrialsFile)
    error( ...
        'Oz trials file was not found:\n%s', ...
        ozTrialsFile ...
    );
end

if exist('wavedec', 'file') ~= 2
    error( ...
        ['Wavelet Toolbox is required. ' ...
         'The function wavedec was not found.'] ...
    );
end

if exist('wrcoef', 'file') ~= 2
    error( ...
        ['Wavelet Toolbox is required. ' ...
         'The function wrcoef was not found.'] ...
    );
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozStimulusTrials', ...
    'trialMetadata', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies', ...
    'targetIndices' ...
);

ozStimulusTrials = inputData.ozStimulusTrials;
trialMetadata = inputData.trialMetadata;

samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;
targetIndices = inputData.targetIndices;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = configuration.numberOfBlocks;

numberOfSamples = size(ozStimulusTrials, 1);

expectedDataSize = [
    numberOfSamples, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects
];

if ~isequal(size(ozStimulusTrials), expectedDataSize)
    error( ...
        ['Unexpected size for ozStimulusTrials.\n' ...
         'Expected: [%s]\n' ...
         'Actual:   [%s]'], ...
        num2str(expectedDataSize), ...
        num2str(size(ozStimulusTrials)) ...
    );
end

expectedNumberOfTrials = ...
    numberOfSubjects * numberOfClasses * numberOfBlocks;

if height(trialMetadata) ~= expectedNumberOfTrials
    error( ...
        ['Unexpected number of rows in trialMetadata.\n' ...
         'Expected: %d\n' ...
         'Actual: %d'], ...
        expectedNumberOfTrials, ...
        height(trialMetadata) ...
    );
end

waveletName = 'db4';
decompositionLevel = 4;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

dwtmode('sym', 'nodisp');

frequencyResolution = samplingFrequency / numberOfSamples;

frequencyAxis = ...
    samplingFrequency * ...
    (0:floor(numberOfSamples / 2)) / ...
    numberOfSamples;

frequencySearchMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = frequencyAxis(frequencySearchMask);

if isempty(searchFrequencies)
    error('No FFT frequencies were found in the requested range.');
end

fprintf('---------------------------------------------\n');
fprintf('Step 03: Wavelet and FFT feature extraction\n');
fprintf('---------------------------------------------\n');

fprintf('Wavelet: %s\n', waveletName);
fprintf('Decomposition level: %d\n', decompositionLevel);
fprintf('Sampling frequency: %.2f Hz\n', samplingFrequency);
fprintf('Samples per trial: %d\n', numberOfSamples);
fprintf('FFT frequency resolution: %.4f Hz\n', frequencyResolution);

fprintf( ...
    'Frequency search interval: %.1f to %.1f Hz\n', ...
    minimumSearchFrequency, ...
    maximumSearchFrequency ...
);

fprintf( ...
    'Number of frequencies in search interval: %d\n\n', ...
    numel(searchFrequencies) ...
);

cad4Trials = zeros( ...
    numberOfSamples, ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

dominantFrequencyArray = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

dominantAmplitudeArray = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

dominantFrequencyVector = zeros( ...
    expectedNumberOfTrials, ...
    1 ...
);

dominantAmplitudeVector = zeros( ...
    expectedNumberOfTrials, ...
    1 ...
);

frequencyErrorVector = zeros( ...
    expectedNumberOfTrials, ...
    1 ...
);

featureRow = 0;

for subjectArrayIndex = 1:numberOfSubjects

    subjectID = subjectIDs(subjectArrayIndex);

    fprintf( ...
        'Processing subject S%d (%d of %d)...\n', ...
        subjectID, ...
        subjectArrayIndex, ...
        numberOfSubjects ...
    );

    for classArrayIndex = 1:numberOfClasses

        stimulusFrequency = ...
            targetFrequencies(classArrayIndex);

        for blockIndex = 1:numberOfBlocks

            featureRow = featureRow + 1;

            trialSignal = squeeze( ...
                ozStimulusTrials( ...
                    :, ...
                    classArrayIndex, ...
                    blockIndex, ...
                    subjectArrayIndex ...
                ) ...
            );

            trialSignal = double(trialSignal(:));

            if numel(trialSignal) ~= numberOfSamples
                error( ...
                    ['Incorrect trial length for S%d, ' ...
                     'class %d, block %d.'], ...
                    subjectID, ...
                    classArrayIndex, ...
                    blockIndex ...
                );
            end

            if any(~isfinite(trialSignal))
                error( ...
                    ['Invalid signal values for S%d, ' ...
                     'class %d, block %d.'], ...
                    subjectID, ...
                    classArrayIndex, ...
                    blockIndex ...
                );
            end

            [waveletCoefficients, bookkeepingVector] = ...
                wavedec( ...
                    trialSignal, ...
                    decompositionLevel, ...
                    waveletName ...
                );

            cad4Signal = wrcoef( ...
                'd', ...
                waveletCoefficients, ...
                bookkeepingVector, ...
                waveletName, ...
                decompositionLevel ...
            );

            cad4Signal = double(cad4Signal(:));

            if numel(cad4Signal) ~= numberOfSamples
                error( ...
                    ['The reconstructed Cad4 signal has ' ...
                     'an unexpected length.'] ...
                );
            end

            cad4Trials( ...
                :, ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = cad4Signal;

            fftCoefficients = fft(cad4Signal);

            twoSidedAmplitude = ...
                abs(fftCoefficients / numberOfSamples);

            oneSidedAmplitude = ...
                twoSidedAmplitude( ...
                    1:floor(numberOfSamples / 2) + 1 ...
                );

            if numel(oneSidedAmplitude) > 2
                oneSidedAmplitude(2:end - 1) = ...
                    2 * oneSidedAmplitude(2:end - 1);
            end

            searchAmplitude = ...
                oneSidedAmplitude(frequencySearchMask);

            [maximumAmplitude, localMaximumIndex] = ...
                max(searchAmplitude);

            dominantFrequency = ...
                searchFrequencies(localMaximumIndex);

            dominantFrequencyArray( ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = dominantFrequency;

            dominantAmplitudeArray( ...
                classArrayIndex, ...
                blockIndex, ...
                subjectArrayIndex ...
            ) = maximumAmplitude;

            dominantFrequencyVector(featureRow) = ...
                dominantFrequency;

            dominantAmplitudeVector(featureRow) = ...
                maximumAmplitude;

            frequencyErrorVector(featureRow) = ...
                dominantFrequency - stimulusFrequency;

            if trialMetadata.SubjectID(featureRow) ~= subjectID
                error( ...
                    'Metadata subject order does not match signal order.' ...
                );
            end

            if trialMetadata.ClassLabel(featureRow) ~= ...
                    classArrayIndex
                error( ...
                    'Metadata class order does not match signal order.' ...
                );
            end

            if trialMetadata.Block(featureRow) ~= blockIndex
                error( ...
                    'Metadata block order does not match signal order.' ...
                );
            end
        end
    end
end

if featureRow ~= expectedNumberOfTrials
    error( ...
        ['Incorrect number of extracted features.\n' ...
         'Expected: %d\n' ...
         'Actual: %d'], ...
        expectedNumberOfTrials, ...
        featureRow ...
    );
end

featuresTable = trialMetadata;

featuresTable.DominantFrequencyHz = ...
    dominantFrequencyVector;

featuresTable.MaximumFFTAmplitude = ...
    dominantAmplitudeVector;

featuresTable.FrequencyErrorHz = ...
    frequencyErrorVector;

validFrequencyGrid = ...
    minimumSearchFrequency:frequencyResolution:maximumSearchFrequency;

frequencyGridError = zeros( ...
    numel(dominantFrequencyVector), ...
    1 ...
);

for rowIndex = 1:numel(dominantFrequencyVector)

    frequencyGridError(rowIndex) = min( ...
        abs( ...
            validFrequencyGrid - ...
            dominantFrequencyVector(rowIndex) ...
        ) ...
    );
end

if any(frequencyGridError > 1e-9)
    error( ...
        'Some dominant frequencies are outside the FFT frequency grid.' ...
    );
end

featureResultsDirectory = fullfile( ...
    configuration.resultsDirectory, ...
    'features' ...
);

if ~isfolder(featureResultsDirectory)
    mkdir(featureResultsDirectory);
end

outputMatFile = fullfile( ...
    featureResultsDirectory, ...
    'step03_wavelet_fft_features.mat' ...
);

outputCsvFile = fullfile( ...
    featureResultsDirectory, ...
    'step03_wavelet_fft_features.csv' ...
);

save( ...
    outputMatFile, ...
    'cad4Trials', ...
    'dominantFrequencyArray', ...
    'dominantAmplitudeArray', ...
    'dominantFrequencyVector', ...
    'dominantAmplitudeVector', ...
    'frequencyErrorVector', ...
    'featuresTable', ...
    'frequencyAxis', ...
    'searchFrequencies', ...
    'waveletName', ...
    'decompositionLevel', ...
    'minimumSearchFrequency', ...
    'maximumSearchFrequency', ...
    'frequencyResolution', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies', ...
    'targetIndices', ...
    '-v7.3' ...
);

writetable(featuresTable, outputCsvFile);

fprintf('\n---------------------------------------------\n');
fprintf('Feature extraction completed successfully.\n');
fprintf('---------------------------------------------\n');

fprintf( ...
    'Total extracted features: %d\n', ...
    numel(dominantFrequencyVector) ...
);

fprintf( ...
    'Minimum dominant frequency: %.2f Hz\n', ...
    min(dominantFrequencyVector) ...
);

fprintf( ...
    'Maximum dominant frequency: %.2f Hz\n', ...
    max(dominantFrequencyVector) ...
);

fprintf( ...
    'Mean absolute frequency error: %.4f Hz\n', ...
    mean(abs(frequencyErrorVector)) ...
);

fprintf('\nSize of cad4Trials:\n');
disp(size(cad4Trials));

fprintf('Size of dominantFrequencyArray:\n');
disp(size(dominantFrequencyArray));

fprintf('\nFirst 12 extracted feature rows:\n');
disp(featuresTable(1:min(12, height(featuresTable)), :));

fprintf('MAT output:\n%s\n\n', outputMatFile);
fprintf('CSV output:\n%s\n', outputCsvFile);