clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz-trials file was not found.');
end

if exist('modwt', 'file') ~= 2
    error('The MODWT function is not available.');
end

if exist('modwtmra', 'file') ~= 2
    error('The MODWTMRA function is not available.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'trialMetadata', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

ozFullTrials = inputData.ozFullTrials;
trialMetadata = inputData.trialMetadata;
samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = size(ozFullTrials, 2);
numberOfBlocks = size(ozFullTrials, 3);

windowStartSample = 126;
windowEndSample = 1375;

numberOfWindowSamples = ...
    windowEndSample - windowStartSample + 1;

waveletName = 'db4';
decompositionLevel = 4;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

dwtmode('sym', 'nodisp');

methodNames = [
    "DWT_wrcoef_FullThenCrop"
    "MODWT_MRA_FullThenCrop"
    "MODWT_MRA_CropThenTransform"
];

numberOfMethods = numel(methodNames);

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)

    matchedIndex = find( ...
        subjectIDs == groupA(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group A subject S%d was not found.', groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)

    matchedIndex = find( ...
        subjectIDs == groupB(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group B subject S%d was not found.', groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

frequencyMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = frequencyAxis(frequencyMask);

dominantFrequencyResults = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects, ...
    numberOfMethods ...
);

methodColumn = strings(numberOfMethods, 1);

overallMADColumn = zeros(numberOfMethods, 1);
groupAMADColumn = zeros(numberOfMethods, 1);
groupBMADColumn = zeros(numberOfMethods, 1);

rmseColumn = zeros(numberOfMethods, 1);
maximumDifferenceColumn = zeros(numberOfMethods, 1);
matchingPercentageColumn = zeros(numberOfMethods, 1);

meanFrequencyResults = zeros( ...
    numberOfSubjects, ...
    numberOfClasses, ...
    numberOfMethods ...
);

matchingTolerance = 0.051;

fprintf('================================================\n');
fprintf('Step 16: DWT versus MODWT-MRA comparison\n');
fprintf('================================================\n\n');

fprintf('Wavelet: %s\n', waveletName);
fprintf('Level: %d\n', decompositionLevel);

fprintf('Window: %d:%d\n', ...
    windowStartSample, ...
    windowEndSample);

fprintf('Window samples: %d\n', numberOfWindowSamples);

fprintf('FFT resolution: %.4f Hz\n\n', ...
    samplingFrequency / numberOfWindowSamples);

for subjectIndex = 1:numberOfSubjects

    fprintf( ...
        'Processing S%d (%d of %d)...\n', ...
        subjectIDs(subjectIndex), ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    for classIndex = 1:numberOfClasses

        for blockIndex = 1:numberOfBlocks

            fullTrial = squeeze( ...
                ozFullTrials( ...
                    :, ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex ...
                ) ...
            );

            fullTrial = double(fullTrial(:));

            croppedTrial = fullTrial( ...
                windowStartSample:windowEndSample ...
            );

            signalVariants = zeros( ...
                numberOfWindowSamples, ...
                numberOfMethods ...
            );

            [dwtCoefficients, dwtBookkeeping] = wavedec( ...
                fullTrial, ...
                decompositionLevel, ...
                waveletName ...
            );

            reconstructedD4 = wrcoef( ...
                'd', ...
                dwtCoefficients, ...
                dwtBookkeeping, ...
                waveletName, ...
                decompositionLevel ...
            );

            signalVariants(:, 1) = reconstructedD4( ...
                windowStartSample:windowEndSample ...
            );

            fullTrialRow = fullTrial(:)';

            modwtFullCoefficients = modwt( ...
                fullTrialRow, ...
                waveletName, ...
                decompositionLevel ...
            );

            modwtFullMRA = modwtmra( ...
                modwtFullCoefficients, ...
                waveletName ...
            );

            if size(modwtFullMRA, 1) < decompositionLevel
                error('Unexpected MODWT-MRA output dimensions.');
            end

            modwtFullD4 = ...
                modwtFullMRA(decompositionLevel, :)';

            if numel(modwtFullD4) ~= numel(fullTrial)
                error( ...
                    'Unexpected full-trial MODWT-MRA length: %d.', ...
                    numel(modwtFullD4) ...
                );
            end

            signalVariants(:, 2) = modwtFullD4( ...
                windowStartSample:windowEndSample ...
            );

            croppedTrialRow = croppedTrial(:)';

            modwtCropCoefficients = modwt( ...
                croppedTrialRow, ...
                waveletName, ...
                decompositionLevel ...
            );

            modwtCropMRA = modwtmra( ...
                modwtCropCoefficients, ...
                waveletName ...
            );

            modwtCropD4 = ...
                modwtCropMRA(decompositionLevel, :)';

            if numel(modwtCropD4) ~= numberOfWindowSamples

                error( ...
                    'Unexpected cropped MODWT-MRA length: %d.', ...
                    numel(modwtCropD4) ...
                );
            end

            signalVariants(:, 3) = modwtCropD4;

            for methodIndex = 1:numberOfMethods

                analysisSignal = ...
                    signalVariants(:, methodIndex);

                fftCoefficients = fft(analysisSignal);

                twoSidedAmplitude = abs( ...
                    fftCoefficients / numberOfWindowSamples ...
                );

                oneSidedAmplitude = ...
                    twoSidedAmplitude( ...
                        1:(numberOfWindowSamples / 2 + 1) ...
                    );

                oneSidedAmplitude(2:end - 1) = ...
                    2 * oneSidedAmplitude(2:end - 1);

                selectedAmplitude = ...
                    oneSidedAmplitude(frequencyMask);

                [~, maximumIndex] = max(selectedAmplitude);

                dominantFrequencyResults( ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex, ...
                    methodIndex ...
                ) = searchFrequencies(maximumIndex);
            end
        end
    end
end

bestScore = inf;
bestMethod = "";
bestMethodIndex = NaN;
bestCalculatedGroupA = [];
bestCalculatedGroupB = [];

for methodIndex = 1:numberOfMethods

    methodColumn(methodIndex) = ...
        methodNames(methodIndex);

    currentDominantFrequencies = ...
        dominantFrequencyResults(:, :, :, methodIndex);

    currentMeanFrequencies = squeeze( ...
        mean(currentDominantFrequencies, 2) ...
    )';

    meanFrequencyResults(:, :, methodIndex) = ...
        currentMeanFrequencies;

    calculatedGroupA = ...
        currentMeanFrequencies(groupAIndices, :);

    calculatedGroupB = ...
        currentMeanFrequencies(groupBIndices, :);

    differenceGroupA = ...
        calculatedGroupA - paperGroupA;

    differenceGroupB = ...
        calculatedGroupB - paperGroupB;

    allDifferences = [
        differenceGroupA(:)
        differenceGroupB(:)
    ];

    overallMAD = mean(abs(allDifferences));
    groupAMAD = mean(abs(differenceGroupA(:)));
    groupBMAD = mean(abs(differenceGroupB(:)));

    rmseValue = sqrt(mean(allDifferences .^ 2));

    maximumDifference = ...
        max(abs(allDifferences));

    matchingPercentage = ...
        100 * sum( ...
            abs(allDifferences) <= matchingTolerance ...
        ) / numel(allDifferences);

    overallMADColumn(methodIndex) = overallMAD;
    groupAMADColumn(methodIndex) = groupAMAD;
    groupBMADColumn(methodIndex) = groupBMAD;
    rmseColumn(methodIndex) = rmseValue;

    maximumDifferenceColumn(methodIndex) = ...
        maximumDifference;

    matchingPercentageColumn(methodIndex) = ...
        matchingPercentage;

    if overallMAD < bestScore

        bestScore = overallMAD;
        bestMethod = methodNames(methodIndex);
        bestMethodIndex = methodIndex;

        bestCalculatedGroupA = calculatedGroupA;
        bestCalculatedGroupB = calculatedGroupB;
    end
end

resultsTable = table( ...
    methodColumn, ...
    overallMADColumn, ...
    groupAMADColumn, ...
    groupBMADColumn, ...
    rmseColumn, ...
    maximumDifferenceColumn, ...
    matchingPercentageColumn, ...
    'VariableNames', { ...
        'WaveletMethod', ...
        'MeanAbsoluteDifferenceHz', ...
        'GroupAMeanAbsoluteDifferenceHz', ...
        'GroupBMeanAbsoluteDifferenceHz', ...
        'RootMeanSquaredDifferenceHz', ...
        'MaximumAbsoluteDifferenceHz', ...
        'MatchingPercentage' ...
    } ...
);

rankedResults = sortrows( ...
    resultsTable, ...
    'MeanAbsoluteDifferenceHz', ...
    'ascend' ...
);

bestGroupATable = array2table( ...
    [groupA(:), bestCalculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

bestGroupBTable = array2table( ...
    [groupB(:), bestCalculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'dwt_modwt_comparison' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

resultsCsvFile = fullfile( ...
    outputDirectory, ...
    'step16_dwt_modwt_results.csv' ...
);

resultsMatFile = fullfile( ...
    outputDirectory, ...
    'step16_dwt_modwt_results.mat' ...
);

groupACsvFile = fullfile( ...
    outputDirectory, ...
    'step16_best_groupA_averages.csv' ...
);

groupBCsvFile = fullfile( ...
    outputDirectory, ...
    'step16_best_groupB_averages.csv' ...
);

writetable(rankedResults, resultsCsvFile);
writetable(bestGroupATable, groupACsvFile);
writetable(bestGroupBTable, groupBCsvFile);

save( ...
    resultsMatFile, ...
    'resultsTable', ...
    'rankedResults', ...
    'dominantFrequencyResults', ...
    'meanFrequencyResults', ...
    'bestScore', ...
    'bestMethod', ...
    'bestMethodIndex', ...
    'bestCalculatedGroupA', ...
    'bestCalculatedGroupB', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 16 completed\n');
fprintf('================================================\n\n');

fprintf('Ranked methods:\n');
disp(rankedResults);

fprintf('Best method: %s\n', bestMethod);

fprintf( ...
    'Best overall mean absolute difference: %.4f Hz\n', ...
    bestScore ...
);

fprintf('\nBest Group A averages:\n');
disp(bestGroupATable);

fprintf('\nBest Group B averages:\n');
disp(bestGroupBTable);

fprintf('\nResults CSV:\n%s\n', resultsCsvFile);
fprintf('\nResults MAT:\n%s\n', resultsMatFile);