clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

featureFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step05_fulltrial_wavelet_features.mat' ...
);

if ~isfile(featureFile)
    error('Step 05 feature file was not found.');
end

requiredFunctions = {
    'trainFineTree10Fold'
    'trainLDA10Fold'
    'trainSVM10Fold'
};

for functionIndex = 1:numel(requiredFunctions)

    if exist(requiredFunctions{functionIndex}, 'file') ~= 2
        error( ...
            'Generated function was not found: %s', ...
            requiredFunctions{functionIndex} ...
        );
    end
end

featureData = load(featureFile, 'featuresTable');
featuresTable = featureData.featuresTable;

groupA = [
    10, 14, 15, 20, 22, ...
    25, 26, 31, 32, 35
];

groupB = [
    1, 2, 3, 5, 6, 7, 8, 9, 12, ...
    17, 18, 19, 21, 24, 27, 28, 30, 34
];

subjectIDs = [groupA, groupB];
numberOfSubjects = numel(subjectIDs);

fineTreeAccuracy = zeros(numberOfSubjects, 1);
ldaAccuracy = zeros(numberOfSubjects, 1);
svmAccuracy = zeros(numberOfSubjects, 1);

groupColumn = strings(numberOfSubjects, 1);

fprintf('================================================\n');
fprintf('Step 13: Subject-wise 10-fold classification\n');
fprintf('================================================\n\n');

for subjectIndex = 1:numberOfSubjects

    subjectID = subjectIDs(subjectIndex);

    subjectData = featuresTable( ...
        featuresTable.SubjectID == subjectID, ...
        {'DominantFrequencyHz', 'ClassLabel'} ...
    );

    if height(subjectData) ~= 24
        error( ...
            'Subject S%d must contain 24 observations, but has %d.', ...
            subjectID, ...
            height(subjectData) ...
        );
    end

    classCounts = zeros(4, 1);

    for classIndex = 1:4
        classCounts(classIndex) = sum( ...
            subjectData.ClassLabel == classIndex ...
        );
    end

    if ~isequal(classCounts, [6; 6; 6; 6])
        error( ...
            'Subject S%d does not have six trials per class.', ...
            subjectID ...
        );
    end

    if ismember(subjectID, groupA)
        groupColumn(subjectIndex) = "A";
    else
        groupColumn(subjectIndex) = "B";
    end

    fprintf( ...
        'Processing S%d, Group %s (%d of %d)...\n', ...
        subjectID, ...
        groupColumn(subjectIndex), ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    rng(subjectID, 'twister');

    [~, currentTreeAccuracy] = ...
        trainFineTree10Fold(subjectData);

    rng(subjectID, 'twister');

    [~, currentLDAAccuracy] = ...
        trainLDA10Fold(subjectData);

    rng(subjectID, 'twister');

    [~, currentSVMAccuracy] = ...
        trainSVM10Fold(subjectData);

    if currentTreeAccuracy <= 1.0001
        currentTreeAccuracy = 100 * currentTreeAccuracy;
    end

    if currentLDAAccuracy <= 1.0001
        currentLDAAccuracy = 100 * currentLDAAccuracy;
    end

    if currentSVMAccuracy <= 1.0001
        currentSVMAccuracy = 100 * currentSVMAccuracy;
    end

    fineTreeAccuracy(subjectIndex) = currentTreeAccuracy;
    ldaAccuracy(subjectIndex) = currentLDAAccuracy;
    svmAccuracy(subjectIndex) = currentSVMAccuracy;
end

subjectResults = table( ...
    subjectIDs(:), ...
    groupColumn, ...
    fineTreeAccuracy, ...
    ldaAccuracy, ...
    svmAccuracy, ...
    'VariableNames', { ...
        'SubjectID', ...
        'Group', ...
        'FineTreeAccuracyPercent', ...
        'LDAAccuracyPercent', ...
        'SVMAccuracyPercent' ...
    } ...
);

groupAIndices = groupColumn == "A";
groupBIndices = groupColumn == "B";

classifier = [
    "Fine Tree"
    "Linear Discriminant"
    "Linear SVM"
];

groupAMeanAccuracy = [
    mean(fineTreeAccuracy(groupAIndices))
    mean(ldaAccuracy(groupAIndices))
    mean(svmAccuracy(groupAIndices))
];

groupBMeanAccuracy = [
    mean(fineTreeAccuracy(groupBIndices))
    mean(ldaAccuracy(groupBIndices))
    mean(svmAccuracy(groupBIndices))
];

groupAStandardDeviation = [
    std(fineTreeAccuracy(groupAIndices))
    std(ldaAccuracy(groupAIndices))
    std(svmAccuracy(groupAIndices))
];

groupBStandardDeviation = [
    std(fineTreeAccuracy(groupBIndices))
    std(ldaAccuracy(groupBIndices))
    std(svmAccuracy(groupBIndices))
];

paperGroupAAccuracy = [
    95.8
    96.7
    96.7
];

paperGroupBAccuracy = [
    91.4
    91.7
    91.9
];

summaryTable = table( ...
    classifier, ...
    groupAMeanAccuracy, ...
    groupAStandardDeviation, ...
    paperGroupAAccuracy, ...
    groupAMeanAccuracy - paperGroupAAccuracy, ...
    groupBMeanAccuracy, ...
    groupBStandardDeviation, ...
    paperGroupBAccuracy, ...
    groupBMeanAccuracy - paperGroupBAccuracy, ...
    'VariableNames', { ...
        'Classifier', ...
        'GroupAMeanAccuracyPercent', ...
        'GroupAStandardDeviationPercent', ...
        'PaperGroupAAccuracyPercent', ...
        'GroupADifferencePercent', ...
        'GroupBMeanAccuracyPercent', ...
        'GroupBStandardDeviationPercent', ...
        'PaperGroupBAccuracyPercent', ...
        'GroupBDifferencePercent' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'subjectwise_classification' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

subjectCsvFile = fullfile( ...
    outputDirectory, ...
    'step13_subjectwise_accuracies.csv' ...
);

summaryCsvFile = fullfile( ...
    outputDirectory, ...
    'step13_subjectwise_summary.csv' ...
);

matFile = fullfile( ...
    outputDirectory, ...
    'step13_subjectwise_results.mat' ...
);

writetable(subjectResults, subjectCsvFile);
writetable(summaryTable, summaryCsvFile);

save( ...
    matFile, ...
    'subjectResults', ...
    'summaryTable', ...
    'fineTreeAccuracy', ...
    'ldaAccuracy', ...
    'svmAccuracy', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Subject-wise results\n');
fprintf('================================================\n\n');

disp(subjectResults);

fprintf('\n================================================\n');
fprintf('Group summary\n');
fprintf('================================================\n\n');

disp(summaryTable);

fprintf('\nSubject results CSV:\n%s\n', subjectCsvFile);
fprintf('\nSummary CSV:\n%s\n', summaryCsvFile);
fprintf('\nMAT results:\n%s\n', matFile);