clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(scriptDirectory);

configurationFile = fullfile( ...
    projectDirectory, ...
    'article_configuration.mat' ...
);

ozTrialsFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'features', ...
    'step02_oz_trials.mat' ...
);

if ~isfile(configurationFile)
    error('Configuration file was not found.');
end

if ~isfile(ozTrialsFile)
    error('Step 02 Oz trials file was not found.');
end

configuration = load(configurationFile);

inputData = load( ...
    ozTrialsFile, ...
    'ozFullTrials', ...
    'trialMetadata', ...
    'samplingFrequency', ...
    'subjectIDs', ...
    'targetFrequencies' ...
);

ozFullTrials = inputData.ozFullTrials;
trialMetadata = inputData.trialMetadata;
samplingFrequency = inputData.samplingFrequency;
subjectIDs = inputData.subjectIDs;
targetFrequencies = inputData.targetFrequencies;

groupA = configuration.groupA;
groupB = configuration.groupB;

numberOfSubjects = numel(subjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = configuration.numberOfBlocks;

windowStartSample = 126;
windowEndSample = 1375;
numberOfWindowSamples = ...
    windowEndSample - windowStartSample + 1;

minimumSearchFrequency = 7.8;
maximumSearchFrequency = 15.6;

frequencyAxis = ...
    samplingFrequency * ...
    (0:(numberOfWindowSamples / 2)) / ...
    numberOfWindowSamples;

frequencySearchMask = ...
    frequencyAxis >= minimumSearchFrequency & ...
    frequencyAxis <= maximumSearchFrequency;

searchFrequencies = ...
    frequencyAxis(frequencySearchMask);

paperGroupA = [
    9.16, 10.00, 11.00, 12.00
    9.00, 10.26, 11.00, 11.13
    9.03, 10.00, 11.00, 12.00
    9.53, 10.13, 11.00, 12.00
    9.00,  9.96, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
    9.00, 10.00, 11.00, 12.00
];

paperGroupB = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

groupAIndices = zeros(numel(groupA), 1);

for index = 1:numel(groupA)

    matchedIndex = find( ...
        subjectIDs == groupA(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group A subject S%d was not found.', groupA(index));
    end

    groupAIndices(index) = matchedIndex;
end

groupBIndices = zeros(numel(groupB), 1);

for index = 1:numel(groupB)

    matchedIndex = find( ...
        subjectIDs == groupB(index), ...
        1 ...
    );

    if isempty(matchedIndex)
        error('Group B subject S%d was not found.', groupB(index));
    end

    groupBIndices(index) = matchedIndex;
end

numberOfTrials = ...
    numberOfSubjects * numberOfClasses * numberOfBlocks;

dominantFrequencyArray = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

dominantAmplitudeArray = zeros( ...
    numberOfClasses, ...
    numberOfBlocks, ...
    numberOfSubjects ...
);

dominantFrequencyVector = zeros(numberOfTrials, 1);
dominantAmplitudeVector = zeros(numberOfTrials, 1);

featureRow = 0;

fprintf('================================================\n');
fprintf('Step 12: Raw Oz FFT feature extraction\n');
fprintf('================================================\n\n');

fprintf('Wavelet processing: None\n');
fprintf('Window: %d:%d\n', ...
    windowStartSample, windowEndSample);

fprintf('Window samples: %d\n', numberOfWindowSamples);

fprintf('FFT frequency resolution: %.4f Hz\n', ...
    samplingFrequency / numberOfWindowSamples);

fprintf('Search range: %.1f to %.1f Hz\n\n', ...
    minimumSearchFrequency, ...
    maximumSearchFrequency);

for subjectIndex = 1:numberOfSubjects

    fprintf( ...
        'Processing S%d (%d of %d)...\n', ...
        subjectIDs(subjectIndex), ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    for classIndex = 1:numberOfClasses

        for blockIndex = 1:numberOfBlocks

            featureRow = featureRow + 1;

            rawSignal = squeeze( ...
                ozFullTrials( ...
                    windowStartSample:windowEndSample, ...
                    classIndex, ...
                    blockIndex, ...
                    subjectIndex ...
                ) ...
            );

            rawSignal = double(rawSignal(:));

            fftCoefficients = fft(rawSignal);

            twoSidedAmplitude = ...
                abs(fftCoefficients / numberOfWindowSamples);

            oneSidedAmplitude = ...
                twoSidedAmplitude( ...
                    1:(numberOfWindowSamples / 2 + 1) ...
                );

            oneSidedAmplitude(2:end - 1) = ...
                2 * oneSidedAmplitude(2:end - 1);

            searchAmplitude = ...
                oneSidedAmplitude(frequencySearchMask);

            [maximumAmplitude, maximumIndex] = ...
                max(searchAmplitude);

            dominantFrequency = ...
                searchFrequencies(maximumIndex);

            dominantFrequencyArray( ...
                classIndex, ...
                blockIndex, ...
                subjectIndex ...
            ) = dominantFrequency;

            dominantAmplitudeArray( ...
                classIndex, ...
                blockIndex, ...
                subjectIndex ...
            ) = maximumAmplitude;

            dominantFrequencyVector(featureRow) = ...
                dominantFrequency;

            dominantAmplitudeVector(featureRow) = ...
                maximumAmplitude;
        end
    end
end

meanDominantFrequencies = squeeze( ...
    mean(dominantFrequencyArray, 2) ...
)';

calculatedGroupA = ...
    meanDominantFrequencies(groupAIndices, :);

calculatedGroupB = ...
    meanDominantFrequencies(groupBIndices, :);

differenceGroupA = calculatedGroupA - paperGroupA;
differenceGroupB = calculatedGroupB - paperGroupB;

allDifferences = [
    differenceGroupA(:)
    differenceGroupB(:)
];

overallMeanAbsoluteDifference = ...
    mean(abs(allDifferences));

groupAMeanAbsoluteDifference = ...
    mean(abs(differenceGroupA(:)));

groupBMeanAbsoluteDifference = ...
    mean(abs(differenceGroupB(:)));

rootMeanSquaredDifference = ...
    sqrt(mean(allDifferences .^ 2));

matchingTolerance = 0.051;

matchingPercentage = ...
    100 * sum(abs(allDifferences) <= matchingTolerance) / ...
    numel(allDifferences);

featuresTable = trialMetadata;

featuresTable.DominantFrequencyHz = ...
    dominantFrequencyVector;

featuresTable.MaximumFFTAmplitude = ...
    dominantAmplitudeVector;

groupAClassificationData = featuresTable( ...
    featuresTable.Group == "A", ...
    {'DominantFrequencyHz', 'ClassLabel'} ...
);

groupBClassificationData = featuresTable( ...
    featuresTable.Group == "B", ...
    {'DominantFrequencyHz', 'ClassLabel'} ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'raw_fft' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

groupAExcelFile = fullfile( ...
    outputDirectory, ...
    'GroupA_RawFFT_ClassificationLearner.xlsx' ...
);

groupBExcelFile = fullfile( ...
    outputDirectory, ...
    'GroupB_RawFFT_ClassificationLearner.xlsx' ...
);

groupATableFile = fullfile( ...
    outputDirectory, ...
    'step12_raw_fft_groupA_averages.csv' ...
);

groupBTableFile = fullfile( ...
    outputDirectory, ...
    'step12_raw_fft_groupB_averages.csv' ...
);

resultMatFile = fullfile( ...
    outputDirectory, ...
    'step12_raw_fft_results.mat' ...
);

groupATable = array2table( ...
    [groupA(:), calculatedGroupA], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

groupBTable = array2table( ...
    [groupB(:), calculatedGroupB], ...
    'VariableNames', { ...
        'SubjectID', ...
        'Mean9Hz', ...
        'Mean10Hz', ...
        'Mean11Hz', ...
        'Mean12Hz' ...
    } ...
);

writetable(groupAClassificationData, groupAExcelFile);
writetable(groupBClassificationData, groupBExcelFile);

writetable(groupATable, groupATableFile);
writetable(groupBTable, groupBTableFile);

save( ...
    resultMatFile, ...
    'dominantFrequencyArray', ...
    'dominantAmplitudeArray', ...
    'featuresTable', ...
    'meanDominantFrequencies', ...
    'calculatedGroupA', ...
    'calculatedGroupB', ...
    'differenceGroupA', ...
    'differenceGroupB', ...
    'overallMeanAbsoluteDifference', ...
    'groupAMeanAbsoluteDifference', ...
    'groupBMeanAbsoluteDifference', ...
    'rootMeanSquaredDifference', ...
    'matchingPercentage', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Step 12 completed\n');
fprintf('================================================\n\n');

fprintf('Overall mean absolute difference: %.4f Hz\n', ...
    overallMeanAbsoluteDifference);

fprintf('Group A mean absolute difference: %.4f Hz\n', ...
    groupAMeanAbsoluteDifference);

fprintf('Group B mean absolute difference: %.4f Hz\n', ...
    groupBMeanAbsoluteDifference);

fprintf('Root mean squared difference: %.4f Hz\n', ...
    rootMeanSquaredDifference);

fprintf('Matching percentage: %.2f%%\n\n', ...
    matchingPercentage);

fprintf('Raw FFT Group A averages:\n');
disp(groupATable);

fprintf('Raw FFT Group B averages:\n');
disp(groupBTable);

fprintf('Group B Classification Learner file:\n%s\n', ...
    groupBExcelFile);