clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(fileparts(scriptDirectory));

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'groupB_rebuild' ...
);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

datasetDirectory = '';

if isempty(datasetDirectory) || ~isfolder(datasetDirectory)
    selectedDirectory = uigetdir( ...
        projectDirectory, ...
        'Select the Tsinghua Benchmark Dataset folder' ...
    );

    if isequal(selectedDirectory, 0)
        error('Dataset selection was cancelled.');
    end

    datasetDirectory = selectedDirectory;
end

groupBSubjectIDs = [
    1, 2, 3, 5, 6, 7, 8, 9, 12, ...
    17, 18, 19, 21, 24, 27, 28, 30, 34
];

targetFrequencies = [9, 10, 11, 12];
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = 6;
numberOfSubjects = numel(groupBSubjectIDs);

samplingFrequency = 250;
fullTrialSamples = 1500;

stimulusStartSample = 126;
stimulusEndSample = 1375;
stimulusSamples = stimulusEndSample - stimulusStartSample + 1;

waveletName = 'db4';
decompositionLevel = 4;
boundaryMode = 'sym';

roundedBandLowerHz = 7.8;
roundedBandUpperHz = 15.6;

theoreticalBandLowerHz = samplingFrequency / 2^(decompositionLevel + 1);
theoreticalBandUpperHz = samplingFrequency / 2^decompositionLevel;

numberOfTopPeaks = 5;

dwtmode(boundaryMode, 'nodisp');

fprintf('================================================\n');
fprintf('Group B rebuild: raw audit and feature extraction\n');
fprintf('================================================\n\n');

fprintf('Dataset directory:\n%s\n\n', datasetDirectory);

fprintf('Subjects: %d\n', numberOfSubjects);
fprintf('Classes: %d\n', numberOfClasses);
fprintf('Blocks per class: %d\n', numberOfBlocks);
fprintf('Expected trials: %d\n', ...
    numberOfSubjects * numberOfClasses * numberOfBlocks);

fprintf('Sampling frequency: %.1f Hz\n', samplingFrequency);
fprintf('Full trial samples: %d\n', fullTrialSamples);
fprintf('Stimulus window: %d:%d\n', ...
    stimulusStartSample, stimulusEndSample);
fprintf('Stimulus samples: %d\n', stimulusSamples);
fprintf('Stimulus duration: %.3f s\n', ...
    stimulusSamples / samplingFrequency);

fprintf('Wavelet: %s\n', waveletName);
fprintf('DWT level: %d\n', decompositionLevel);
fprintf('Boundary mode: %s\n', boundaryMode);
fprintf('Rounded article band: %.1f-%.1f Hz\n', ...
    roundedBandLowerHz, roundedBandUpperHz);
fprintf('Theoretical D4 band: %.4f-%.4f Hz\n\n', ...
    theoreticalBandLowerHz, theoreticalBandUpperHz);

frequencyFileSearch = dir( ...
    fullfile(datasetDirectory, '**', 'Freq_Phase.mat') ...
);

if isempty(frequencyFileSearch)
    error('Freq_Phase.mat was not found under the selected dataset folder.');
end

if numel(frequencyFileSearch) > 1
    warning( ...
        'Multiple Freq_Phase.mat files were found. Using the first one:\n%s', ...
        fullfile( ...
            frequencyFileSearch(1).folder, ...
            frequencyFileSearch(1).name ...
        ) ...
    );
end

frequencyFile = fullfile( ...
    frequencyFileSearch(1).folder, ...
    frequencyFileSearch(1).name ...
);

frequencyData = load(frequencyFile);

if ~isfield(frequencyData, 'freqs')
    error('Variable freqs was not found in Freq_Phase.mat.');
end

allDatasetFrequencies = double(frequencyData.freqs(:));
targetDatasetIndices = zeros(1, numberOfClasses);

fprintf('Verified target-frequency mapping:\n');

for classIndex = 1:numberOfClasses

    matchedIndex = find( ...
        abs( ...
            allDatasetFrequencies - ...
            targetFrequencies(classIndex) ...
        ) < 1e-10, ...
        1 ...
    );

    if isempty(matchedIndex)
        error( ...
            'Target frequency %.1f Hz was not found in Freq_Phase.mat.', ...
            targetFrequencies(classIndex) ...
        );
    end

    targetDatasetIndices(classIndex) = matchedIndex;

    fprintf( ...
        'Class %d: %.1f Hz -> dataset index %d\n', ...
        classIndex, ...
        targetFrequencies(classIndex), ...
        matchedIndex ...
    );
end

fprintf('\n');

auditSubjectID = zeros(numberOfSubjects, 1);
auditFileName = strings(numberOfSubjects, 1);
auditDimension1 = zeros(numberOfSubjects, 1);
auditDimension2 = zeros(numberOfSubjects, 1);
auditDimension3 = zeros(numberOfSubjects, 1);
auditDimension4 = zeros(numberOfSubjects, 1);
auditNaNCount = zeros(numberOfSubjects, 1);
auditInfCount = zeros(numberOfSubjects, 1);
auditMinimum = zeros(numberOfSubjects, 1);
auditMaximum = zeros(numberOfSubjects, 1);

numberOfTrials = ...
    numberOfSubjects * numberOfClasses * numberOfBlocks;

rawStimulusMatrix = zeros(numberOfTrials, stimulusSamples);
d4ReconstructedMatrix = zeros(numberOfTrials, stimulusSamples);

firstTrialD4Length = NaN;
d4CoefficientMatrix = [];

subjectIDColumn = zeros(numberOfTrials, 1);
classLabelColumn = zeros(numberOfTrials, 1);
targetFrequencyColumn = zeros(numberOfTrials, 1);
blockColumn = zeros(numberOfTrials, 1);

dominantFrequencyRoundedColumn = zeros(numberOfTrials, 1);
dominantAmplitudeRoundedColumn = zeros(numberOfTrials, 1);

dominantFrequencyTheoreticalColumn = zeros(numberOfTrials, 1);
dominantAmplitudeTheoreticalColumn = zeros(numberOfTrials, 1);

rawRMSColumn = zeros(numberOfTrials, 1);
d4RMSColumn = zeros(numberOfTrials, 1);

topPeakFrequencyColumns = zeros(numberOfTrials, numberOfTopPeaks);
topPeakAmplitudeColumns = zeros(numberOfTrials, numberOfTopPeaks);

frequencyAxis = ...
    samplingFrequency * ...
    (0:(stimulusSamples / 2)) / ...
    stimulusSamples;

roundedBandMask = ...
    frequencyAxis >= roundedBandLowerHz - 1e-12 & ...
    frequencyAxis <= roundedBandUpperHz + 1e-12;

theoreticalBandMask = ...
    frequencyAxis >= theoreticalBandLowerHz - 1e-12 & ...
    frequencyAxis <= theoreticalBandUpperHz + 1e-12;

roundedBandFrequencies = frequencyAxis(roundedBandMask);
theoreticalBandFrequencies = frequencyAxis(theoreticalBandMask);

trialRow = 0;

for subjectIndex = 1:numberOfSubjects

    subjectID = groupBSubjectIDs(subjectIndex);

    subjectFileCandidates = [
        dir(fullfile(datasetDirectory, '**', sprintf('S%d.mat', subjectID)))
        dir(fullfile(datasetDirectory, '**', sprintf('S%02d.mat', subjectID)))
    ];

    if isempty(subjectFileCandidates)
        error('Subject file S%d was not found.', subjectID);
    end

    subjectFile = fullfile( ...
        subjectFileCandidates(1).folder, ...
        subjectFileCandidates(1).name ...
    );

    loadedSubject = load(subjectFile);

    if isfield(loadedSubject, 'data')
        subjectData = loadedSubject.data;
    else
        loadedVariableNames = fieldnames(loadedSubject);
        subjectData = [];

        for variableIndex = 1:numel(loadedVariableNames)

            candidateData = loadedSubject.( ...
                loadedVariableNames{variableIndex} ...
            );

            if isnumeric(candidateData) && ...
                    ndims(candidateData) == 4 && ...
                    size(candidateData, 1) == 64 && ...
                    size(candidateData, 2) == 1500

                subjectData = candidateData;
                break;
            end
        end

        if isempty(subjectData)
            error( ...
                'No 64x1500x40x6 numeric EEG array was found for S%d.', ...
                subjectID ...
            );
        end
    end

    subjectDimensions = size(subjectData);

    if numel(subjectDimensions) ~= 4 || ...
            subjectDimensions(1) ~= 64 || ...
            subjectDimensions(2) ~= fullTrialSamples || ...
            subjectDimensions(3) ~= 40 || ...
            subjectDimensions(4) ~= numberOfBlocks

        error( ...
            ['Unexpected dimensions for S%d. ' ...
             'Expected 64x1500x40x6, received %s.'], ...
            subjectID, ...
            mat2str(subjectDimensions) ...
        );
    end

    auditSubjectID(subjectIndex) = subjectID;
    auditFileName(subjectIndex) = string(subjectFile);
    auditDimension1(subjectIndex) = subjectDimensions(1);
    auditDimension2(subjectIndex) = subjectDimensions(2);
    auditDimension3(subjectIndex) = subjectDimensions(3);
    auditDimension4(subjectIndex) = subjectDimensions(4);
    auditNaNCount(subjectIndex) = sum(isnan(subjectData(:)));
    auditInfCount(subjectIndex) = sum(isinf(subjectData(:)));
    auditMinimum(subjectIndex) = min(double(subjectData(:)));
    auditMaximum(subjectIndex) = max(double(subjectData(:)));

    if auditNaNCount(subjectIndex) > 0
        error('NaN values were found in S%d.', subjectID);
    end

    if auditInfCount(subjectIndex) > 0
        error('Inf values were found in S%d.', subjectID);
    end

    fprintf( ...
        'Processing S%d (%d of %d)...\n', ...
        subjectID, ...
        subjectIndex, ...
        numberOfSubjects ...
    );

    for classIndex = 1:numberOfClasses

        datasetFrequencyIndex = ...
            targetDatasetIndices(classIndex);

        for blockIndex = 1:numberOfBlocks

            trialRow = trialRow + 1;

            fullOzTrial = squeeze( ...
                subjectData( ...
                    62, ...
                    :, ...
                    datasetFrequencyIndex, ...
                    blockIndex ...
                ) ...
            );

            fullOzTrial = double(fullOzTrial(:));

            stimulusSignal = fullOzTrial( ...
                stimulusStartSample:stimulusEndSample ...
            );

            [waveletCoefficients, bookkeeping] = wavedec( ...
                stimulusSignal, ...
                decompositionLevel, ...
                waveletName ...
            );

            d4Coefficients = detcoef( ...
                waveletCoefficients, ...
                bookkeeping, ...
                decompositionLevel ...
            );

            d4Coefficients = double(d4Coefficients(:));

            if isnan(firstTrialD4Length)
                firstTrialD4Length = numel(d4Coefficients);
                d4CoefficientMatrix = zeros( ...
                    numberOfTrials, ...
                    firstTrialD4Length ...
                );
            end

            if numel(d4Coefficients) ~= firstTrialD4Length
                error( ...
                    ['D4 coefficient length mismatch for S%d, class %d, ' ...
                     'block %d. Expected %d, received %d.'], ...
                    subjectID, ...
                    classIndex, ...
                    blockIndex, ...
                    firstTrialD4Length, ...
                    numel(d4Coefficients) ...
                );
            end

            reconstructedD4 = wrcoef( ...
                'd', ...
                waveletCoefficients, ...
                bookkeeping, ...
                waveletName, ...
                decompositionLevel ...
            );

            reconstructedD4 = double(reconstructedD4(:));

            if numel(reconstructedD4) ~= stimulusSamples
                error( ...
                    ['Reconstructed D4 length mismatch for S%d, ' ...
                     'class %d, block %d.'], ...
                    subjectID, ...
                    classIndex, ...
                    blockIndex ...
                );
            end

            fftCoefficients = fft(reconstructedD4);

            twoSidedMagnitude = abs( ...
                fftCoefficients / stimulusSamples ...
            );

            oneSidedMagnitude = twoSidedMagnitude( ...
                1:(stimulusSamples / 2 + 1) ...
            );

            oneSidedMagnitude(2:end - 1) = ...
                2 * oneSidedMagnitude(2:end - 1);

            roundedBandMagnitude = ...
                oneSidedMagnitude(roundedBandMask);

            [roundedMaximumAmplitude, roundedMaximumIndex] = ...
                max(roundedBandMagnitude);

            theoreticalBandMagnitude = ...
                oneSidedMagnitude(theoreticalBandMask);

            [theoreticalMaximumAmplitude, theoreticalMaximumIndex] = ...
                max(theoreticalBandMagnitude);

            [topPeakFrequencies, topPeakAmplitudes] = ...
                extractTopLocalPeaks( ...
                    roundedBandFrequencies, ...
                    roundedBandMagnitude, ...
                    numberOfTopPeaks ...
                );

            subjectIDColumn(trialRow) = subjectID;
            classLabelColumn(trialRow) = classIndex;

            targetFrequencyColumn(trialRow) = ...
                targetFrequencies(classIndex);

            blockColumn(trialRow) = blockIndex;

            dominantFrequencyRoundedColumn(trialRow) = ...
                roundedBandFrequencies(roundedMaximumIndex);

            dominantAmplitudeRoundedColumn(trialRow) = ...
                roundedMaximumAmplitude;

            dominantFrequencyTheoreticalColumn(trialRow) = ...
                theoreticalBandFrequencies(theoreticalMaximumIndex);

            dominantAmplitudeTheoreticalColumn(trialRow) = ...
                theoreticalMaximumAmplitude;

            rawRMSColumn(trialRow) = sqrt( ...
                mean(stimulusSignal .^ 2) ...
            );

            d4RMSColumn(trialRow) = sqrt( ...
                mean(reconstructedD4 .^ 2) ...
            );

            topPeakFrequencyColumns(trialRow, :) = ...
                topPeakFrequencies;

            topPeakAmplitudeColumns(trialRow, :) = ...
                topPeakAmplitudes;

            rawStimulusMatrix(trialRow, :) = ...
                stimulusSignal';

            d4ReconstructedMatrix(trialRow, :) = ...
                reconstructedD4';

            d4CoefficientMatrix(trialRow, :) = ...
                d4Coefficients';
        end
    end
end

if trialRow ~= numberOfTrials
    error( ...
        'Expected %d trials but extracted %d.', ...
        numberOfTrials, ...
        trialRow ...
    );
end

auditTable = table( ...
    auditSubjectID, ...
    auditFileName, ...
    auditDimension1, ...
    auditDimension2, ...
    auditDimension3, ...
    auditDimension4, ...
    auditNaNCount, ...
    auditInfCount, ...
    auditMinimum, ...
    auditMaximum, ...
    'VariableNames', { ...
        'SubjectID', ...
        'SourceFile', ...
        'Channels', ...
        'TimeSamples', ...
        'Stimuli', ...
        'Blocks', ...
        'NaNCount', ...
        'InfCount', ...
        'MinimumValue', ...
        'MaximumValue' ...
    } ...
);

trialTable = table( ...
    subjectIDColumn, ...
    classLabelColumn, ...
    targetFrequencyColumn, ...
    blockColumn, ...
    dominantFrequencyRoundedColumn, ...
    dominantAmplitudeRoundedColumn, ...
    dominantFrequencyTheoreticalColumn, ...
    dominantAmplitudeTheoreticalColumn, ...
    rawRMSColumn, ...
    d4RMSColumn, ...
    'VariableNames', { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'Block', ...
        'DominantFrequencyRoundedBandHz', ...
        'DominantAmplitudeRoundedBand', ...
        'DominantFrequencyTheoreticalBandHz', ...
        'DominantAmplitudeTheoreticalBand', ...
        'RawStimulusRMS', ...
        'D4ReconstructedRMS' ...
    } ...
);

for peakIndex = 1:numberOfTopPeaks

    trialTable.( ...
        sprintf('Peak%dFrequencyHz', peakIndex) ...
    ) = topPeakFrequencyColumns(:, peakIndex);

    trialTable.( ...
        sprintf('Peak%dAmplitude', peakIndex) ...
    ) = topPeakAmplitudeColumns(:, peakIndex);
end

articleGroupBMeans = [
    9.53, 10.13, 11.00, 11.26
    9.83, 10.30, 11.00, 11.60
    9.00, 10.10, 11.00, 12.00
    9.56, 10.20, 11.03, 12.00
    9.166,10.00, 11.00, 12.00
    9.86, 10.23, 11.03, 11.93
    9.10, 10.20, 11.00, 12.00
    9.56, 10.56, 10.13, 11.86
    9.10, 10.00, 11.00, 12.00
    9.10, 10.00, 11.03, 11.86
    9.10, 10.56, 11.03, 10.23
    9.56, 10.20, 11.00, 12.00
    9.00, 10.00, 11.00, 11.86
    9.20, 10.20, 11.00, 12.00
    9.96, 10.00, 10.13, 11.56
    9.00, 10.00, 11.00, 11.86
    9.56, 10.00, 11.00, 10.23
    9.00, 10.00, 11.00, 11.86
];

roundedSubjectClassMeans = zeros( ...
    numberOfSubjects, ...
    numberOfClasses ...
);

theoreticalSubjectClassMeans = zeros( ...
    numberOfSubjects, ...
    numberOfClasses ...
);

for subjectIndex = 1:numberOfSubjects

    for classIndex = 1:numberOfClasses

        currentMask = ...
            subjectIDColumn == groupBSubjectIDs(subjectIndex) & ...
            classLabelColumn == classIndex;

        roundedSubjectClassMeans(subjectIndex, classIndex) = ...
            mean( ...
                dominantFrequencyRoundedColumn(currentMask) ...
            );

        theoreticalSubjectClassMeans(subjectIndex, classIndex) = ...
            mean( ...
                dominantFrequencyTheoreticalColumn(currentMask) ...
            );
    end
end

roundedDifferences = ...
    roundedSubjectClassMeans - articleGroupBMeans;

theoreticalDifferences = ...
    theoreticalSubjectClassMeans - articleGroupBMeans;

roundedMAD = mean(abs(roundedDifferences(:)));
theoreticalMAD = mean(abs(theoreticalDifferences(:)));

roundedRMSE = sqrt(mean(roundedDifferences(:) .^ 2));
theoreticalRMSE = sqrt(mean(theoreticalDifferences(:) .^ 2));

roundedMaximumDifference = max(abs(roundedDifferences(:)));
theoreticalMaximumDifference = max(abs(theoreticalDifferences(:)));

matchingTolerance = 0.051;

roundedMatchingPercentage = ...
    100 * sum( ...
        abs(roundedDifferences(:)) <= matchingTolerance ...
    ) / numel(roundedDifferences);

theoreticalMatchingPercentage = ...
    100 * sum( ...
        abs(theoreticalDifferences(:)) <= matchingTolerance ...
    ) / numel(theoreticalDifferences);

subjectClassComparisonTable = table( ...
    groupBSubjectIDs(:), ...
    roundedSubjectClassMeans(:, 1), ...
    roundedSubjectClassMeans(:, 2), ...
    roundedSubjectClassMeans(:, 3), ...
    roundedSubjectClassMeans(:, 4), ...
    theoreticalSubjectClassMeans(:, 1), ...
    theoreticalSubjectClassMeans(:, 2), ...
    theoreticalSubjectClassMeans(:, 3), ...
    theoreticalSubjectClassMeans(:, 4), ...
    articleGroupBMeans(:, 1), ...
    articleGroupBMeans(:, 2), ...
    articleGroupBMeans(:, 3), ...
    articleGroupBMeans(:, 4), ...
    'VariableNames', { ...
        'SubjectID', ...
        'RoundedMean9Hz', ...
        'RoundedMean10Hz', ...
        'RoundedMean11Hz', ...
        'RoundedMean12Hz', ...
        'TheoreticalMean9Hz', ...
        'TheoreticalMean10Hz', ...
        'TheoreticalMean11Hz', ...
        'TheoreticalMean12Hz', ...
        'ArticleMean9Hz', ...
        'ArticleMean10Hz', ...
        'ArticleMean11Hz', ...
        'ArticleMean12Hz' ...
    } ...
);

roundedClassificationTable = table( ...
    dominantFrequencyRoundedColumn, ...
    classLabelColumn, ...
    'VariableNames', { ...
        'DominantFrequencyHz', ...
        'ClassLabel' ...
    } ...
);

theoreticalClassificationTable = table( ...
    dominantFrequencyTheoreticalColumn, ...
    classLabelColumn, ...
    'VariableNames', { ...
        'DominantFrequencyHz', ...
        'ClassLabel' ...
    } ...
);

auditCsvFile = fullfile( ...
    outputDirectory, ...
    'B00_raw_dataset_audit.csv' ...
);

trialCsvFile = fullfile( ...
    outputDirectory, ...
    'B01_trial_features_and_top_peaks.csv' ...
);

comparisonCsvFile = fullfile( ...
    outputDirectory, ...
    'B02_subject_class_comparison.csv' ...
);

roundedClassificationFile = fullfile( ...
    outputDirectory, ...
    'GroupB_Rebuild_RoundedBand_ClassificationLearner.xlsx' ...
);

theoreticalClassificationFile = fullfile( ...
    outputDirectory, ...
    'GroupB_Rebuild_TheoreticalBand_ClassificationLearner.xlsx' ...
);

resultMatFile = fullfile( ...
    outputDirectory, ...
    'GroupB_Rebuild_AllIntermediateResults.mat' ...
);

writetable(auditTable, auditCsvFile);
writetable(trialTable, trialCsvFile);
writetable(subjectClassComparisonTable, comparisonCsvFile);

writetable( ...
    roundedClassificationTable, ...
    roundedClassificationFile ...
);

writetable( ...
    theoreticalClassificationTable, ...
    theoreticalClassificationFile ...
);

save( ...
    resultMatFile, ...
    'auditTable', ...
    'trialTable', ...
    'subjectClassComparisonTable', ...
    'roundedClassificationTable', ...
    'theoreticalClassificationTable', ...
    'rawStimulusMatrix', ...
    'd4CoefficientMatrix', ...
    'd4ReconstructedMatrix', ...
    'roundedSubjectClassMeans', ...
    'theoreticalSubjectClassMeans', ...
    'articleGroupBMeans', ...
    'roundedDifferences', ...
    'theoreticalDifferences', ...
    'roundedMAD', ...
    'theoreticalMAD', ...
    'roundedRMSE', ...
    'theoreticalRMSE', ...
    'roundedMaximumDifference', ...
    'theoreticalMaximumDifference', ...
    'roundedMatchingPercentage', ...
    'theoreticalMatchingPercentage', ...
    'groupBSubjectIDs', ...
    'targetFrequencies', ...
    'targetDatasetIndices', ...
    'samplingFrequency', ...
    'stimulusStartSample', ...
    'stimulusEndSample', ...
    'waveletName', ...
    'decompositionLevel', ...
    'boundaryMode', ...
    'roundedBandLowerHz', ...
    'roundedBandUpperHz', ...
    'theoreticalBandLowerHz', ...
    'theoreticalBandUpperHz', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('Group B rebuild completed\n');
fprintf('================================================\n\n');

fprintf('D4 coefficient length: %d\n', firstTrialD4Length);

fprintf('\nRounded article band %.1f-%.1f Hz:\n', ...
    roundedBandLowerHz, ...
    roundedBandUpperHz);

fprintf('Mean absolute difference: %.4f Hz\n', roundedMAD);
fprintf('Root mean squared difference: %.4f Hz\n', roundedRMSE);
fprintf('Maximum absolute difference: %.4f Hz\n', ...
    roundedMaximumDifference);
fprintf('Matching percentage: %.2f%%\n', ...
    roundedMatchingPercentage);

fprintf('\nTheoretical D4 band %.4f-%.4f Hz:\n', ...
    theoreticalBandLowerHz, ...
    theoreticalBandUpperHz);

fprintf('Mean absolute difference: %.4f Hz\n', theoreticalMAD);
fprintf('Root mean squared difference: %.4f Hz\n', theoreticalRMSE);
fprintf('Maximum absolute difference: %.4f Hz\n', ...
    theoreticalMaximumDifference);
fprintf('Matching percentage: %.2f%%\n\n', ...
    theoreticalMatchingPercentage);

fprintf('Subject-class comparison:\n');
disp(subjectClassComparisonTable);

fprintf('\nAudit CSV:\n%s\n', auditCsvFile);
fprintf('\nTrial features CSV:\n%s\n', trialCsvFile);
fprintf('\nSubject-class comparison CSV:\n%s\n', comparisonCsvFile);
fprintf('\nRounded-band Classification Learner file:\n%s\n', ...
    roundedClassificationFile);
fprintf('\nTheoretical-band Classification Learner file:\n%s\n', ...
    theoreticalClassificationFile);
fprintf('\nAll intermediate MAT file:\n%s\n', resultMatFile);

function [topFrequencies, topAmplitudes] = ...
    extractTopLocalPeaks(frequencies, amplitudes, numberOfPeaks)

    frequencies = double(frequencies(:));
    amplitudes = double(amplitudes(:));

    localPeakMask = false(size(amplitudes));

    if numel(amplitudes) == 1
        localPeakMask(1) = true;
    else
        localPeakMask(1) = amplitudes(1) >= amplitudes(2);

        localPeakMask(end) = ...
            amplitudes(end) >= amplitudes(end - 1);

        if numel(amplitudes) > 2
            localPeakMask(2:end - 1) = ...
                amplitudes(2:end - 1) >= amplitudes(1:end - 2) & ...
                amplitudes(2:end - 1) >= amplitudes(3:end);
        end
    end

    peakIndices = find(localPeakMask);

    [~, sortingOrder] = sort( ...
        amplitudes(peakIndices), ...
        'descend' ...
    );

    peakIndices = peakIndices(sortingOrder);

    if numel(peakIndices) < numberOfPeaks

        [~, allBinOrder] = sort(amplitudes, 'descend');

        for binIndex = 1:numel(allBinOrder)

            candidateIndex = allBinOrder(binIndex);

            if ~ismember(candidateIndex, peakIndices)
                peakIndices(end + 1, 1) = candidateIndex;
            end

            if numel(peakIndices) >= numberOfPeaks
                break;
            end
        end
    end

    selectedCount = min(numberOfPeaks, numel(peakIndices));

    topFrequencies = nan(1, numberOfPeaks);
    topAmplitudes = nan(1, numberOfPeaks);

    topFrequencies(1:selectedCount) = ...
        frequencies(peakIndices(1:selectedCount));

    topAmplitudes(1:selectedCount) = ...
        amplitudes(peakIndices(1:selectedCount));
end
