clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(fileparts(scriptDirectory));

inputMatFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'groupB_rebuild', ...
    'GroupB_Rebuild_AllIntermediateResults.mat' ...
);

if ~isfile(inputMatFile)
    error('Rebuild MAT file was not found:\n%s', inputMatFile);
end

loadedData = load(inputMatFile);

requiredVariables = {
    'trialTable'
    'articleGroupBMeans'
    'groupBSubjectIDs'
    'targetFrequencies'
};

for variableIndex = 1:numel(requiredVariables)

    variableName = requiredVariables{variableIndex};

    if ~isfield(loadedData, variableName)
        error('Required variable was not found: %s', variableName);
    end
end

trialTable = loadedData.trialTable;
articleGroupBMeans = loadedData.articleGroupBMeans;
groupBSubjectIDs = loadedData.groupBSubjectIDs(:);
targetFrequencies = loadedData.targetFrequencies(:)';

numberOfSubjects = numel(groupBSubjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = 6;
numberOfPeaks = 5;

peakFrequencyVariableNames = cell(1, numberOfPeaks);
peakAmplitudeVariableNames = cell(1, numberOfPeaks);

for peakIndex = 1:numberOfPeaks

    peakFrequencyVariableNames{peakIndex} = ...
        sprintf('Peak%dFrequencyHz', peakIndex);

    peakAmplitudeVariableNames{peakIndex} = ...
        sprintf('Peak%dAmplitude', peakIndex);

    if ~ismember( ...
            peakFrequencyVariableNames{peakIndex}, ...
            trialTable.Properties.VariableNames ...
        )

        error( ...
            'Variable was not found: %s', ...
            peakFrequencyVariableNames{peakIndex} ...
        );
    end

    if ~ismember( ...
            peakAmplitudeVariableNames{peakIndex}, ...
            trialTable.Properties.VariableNames ...
        )

        error( ...
            'Variable was not found: %s', ...
            peakAmplitudeVariableNames{peakIndex} ...
        );
    end
end

combinationGrids = cell(1, numberOfBlocks);

[combinationGrids{:}] = ndgrid(1:numberOfPeaks);

numberOfCombinations = numberOfPeaks ^ numberOfBlocks;
peakRankCombinations = zeros(numberOfCombinations, numberOfBlocks);

for blockIndex = 1:numberOfBlocks
    peakRankCombinations(:, blockIndex) = ...
        combinationGrids{blockIndex}(:);
end

numberOfRows = numberOfSubjects * numberOfClasses;

subjectIDColumn = zeros(numberOfRows, 1);
classLabelColumn = zeros(numberOfRows, 1);
targetFrequencyColumn = zeros(numberOfRows, 1);
articleMeanColumn = zeros(numberOfRows, 1);
primaryPeakMeanColumn = zeros(numberOfRows, 1);
primaryDifferenceColumn = zeros(numberOfRows, 1);

bestTop5MeanColumn = zeros(numberOfRows, 1);
bestTop5ResidualColumn = zeros(numberOfRows, 1);
reachableWithinTwoDecimalsColumn = false(numberOfRows, 1);
nonPrimarySelectionsColumn = zeros(numberOfRows, 1);

closestToTargetMeanColumn = zeros(numberOfRows, 1);
closestToTargetDifferenceColumn = zeros(numberOfRows, 1);

selectedRankColumns = zeros(numberOfRows, numberOfBlocks);
selectedFrequencyColumns = zeros(numberOfRows, numberOfBlocks);
selectedAmplitudeRatioColumns = zeros(numberOfRows, numberOfBlocks);

candidateTolerances = [0.2, 0.4, 0.6, 0.8, 1.0];
numberOfTolerances = numel(candidateTolerances);

toleranceRuleMeans = zeros(numberOfRows, numberOfTolerances);
toleranceRuleDifferences = zeros(numberOfRows, numberOfTolerances);

detailSubjectID = zeros(numberOfRows * numberOfBlocks, 1);
detailClassLabel = zeros(numberOfRows * numberOfBlocks, 1);
detailTargetFrequency = zeros(numberOfRows * numberOfBlocks, 1);
detailBlock = zeros(numberOfRows * numberOfBlocks, 1);
detailSelectedRank = zeros(numberOfRows * numberOfBlocks, 1);
detailSelectedFrequency = zeros(numberOfRows * numberOfBlocks, 1);
detailPrimaryFrequency = zeros(numberOfRows * numberOfBlocks, 1);
detailSelectedAmplitude = zeros(numberOfRows * numberOfBlocks, 1);
detailPrimaryAmplitude = zeros(numberOfRows * numberOfBlocks, 1);
detailAmplitudeRatio = zeros(numberOfRows * numberOfBlocks, 1);

summaryRow = 0;
detailRow = 0;

fprintf('================================================\n');
fprintf('B03: Trial-level peak-selection audit\n');
fprintf('================================================\n\n');

fprintf('Peak candidates per trial: %d\n', numberOfPeaks);
fprintf('Blocks per subject-class pair: %d\n', numberOfBlocks);
fprintf('Combinations tested per subject-class pair: %d\n', ...
    numberOfCombinations);
fprintf('Subject-class pairs: %d\n\n', numberOfRows);

for subjectIndex = 1:numberOfSubjects

    subjectID = groupBSubjectIDs(subjectIndex);

    for classIndex = 1:numberOfClasses

        summaryRow = summaryRow + 1;

        rowMask = ...
            trialTable.SubjectID == subjectID & ...
            trialTable.ClassLabel == classIndex;

        currentTrials = trialTable(rowMask, :);
        currentTrials = sortrows(currentTrials, 'Block');

        if height(currentTrials) ~= numberOfBlocks
            error( ...
                'Expected %d blocks for S%d class %d, found %d.', ...
                numberOfBlocks, ...
                subjectID, ...
                classIndex, ...
                height(currentTrials) ...
            );
        end

        peakFrequencies = zeros(numberOfBlocks, numberOfPeaks);
        peakAmplitudes = zeros(numberOfBlocks, numberOfPeaks);

        for peakIndex = 1:numberOfPeaks

            peakFrequencies(:, peakIndex) = ...
                currentTrials.( ...
                    peakFrequencyVariableNames{peakIndex} ...
                );

            peakAmplitudes(:, peakIndex) = ...
                currentTrials.( ...
                    peakAmplitudeVariableNames{peakIndex} ...
                );
        end

        articleMean = articleGroupBMeans( ...
            subjectIndex, ...
            classIndex ...
        );

        primaryPeakMean = mean(peakFrequencies(:, 1));

        selectedCombinationFrequencies = zeros( ...
            numberOfCombinations, ...
            numberOfBlocks ...
        );

        for blockIndex = 1:numberOfBlocks

            selectedCombinationFrequencies(:, blockIndex) = ...
                peakFrequencies( ...
                    blockIndex, ...
                    peakRankCombinations(:, blockIndex) ...
                )';
        end

        candidateMeans = mean( ...
            selectedCombinationFrequencies, ...
            2 ...
        );

        [bestResidual, bestCombinationIndex] = min( ...
            abs(candidateMeans - articleMean) ...
        );

        bestRanks = ...
            peakRankCombinations(bestCombinationIndex, :);

        bestFrequencies = zeros(1, numberOfBlocks);
        bestAmplitudeRatios = zeros(1, numberOfBlocks);

        for blockIndex = 1:numberOfBlocks

            selectedRank = bestRanks(blockIndex);

            bestFrequencies(blockIndex) = ...
                peakFrequencies(blockIndex, selectedRank);

            primaryAmplitude = peakAmplitudes(blockIndex, 1);
            selectedAmplitude = ...
                peakAmplitudes(blockIndex, selectedRank);

            if primaryAmplitude == 0
                bestAmplitudeRatios(blockIndex) = NaN;
            else
                bestAmplitudeRatios(blockIndex) = ...
                    selectedAmplitude / primaryAmplitude;
            end
        end

        closestToTargetFrequencies = zeros(numberOfBlocks, 1);

        for blockIndex = 1:numberOfBlocks

            frequencyDistances = abs( ...
                peakFrequencies(blockIndex, :) - ...
                targetFrequencies(classIndex) ...
            );

            minimumDistance = min(frequencyDistances);

            candidateRanks = find( ...
                abs(frequencyDistances - minimumDistance) < 1e-12 ...
            );

            if numel(candidateRanks) > 1

                [~, localMaximumIndex] = max( ...
                    peakAmplitudes( ...
                        blockIndex, ...
                        candidateRanks ...
                    ) ...
                );

                selectedRank = ...
                    candidateRanks(localMaximumIndex);

            else
                selectedRank = candidateRanks(1);
            end

            closestToTargetFrequencies(blockIndex) = ...
                peakFrequencies(blockIndex, selectedRank);
        end

        for toleranceIndex = 1:numberOfTolerances

            toleranceHz = candidateTolerances(toleranceIndex);
            selectedFrequenciesForRule = zeros(numberOfBlocks, 1);

            for blockIndex = 1:numberOfBlocks

                eligibleRanks = find( ...
                    abs( ...
                        peakFrequencies(blockIndex, :) - ...
                        targetFrequencies(classIndex) ...
                    ) <= toleranceHz + 1e-12 ...
                );

                if isempty(eligibleRanks)

                    selectedRank = 1;

                else

                    [~, localMaximumIndex] = max( ...
                        peakAmplitudes( ...
                            blockIndex, ...
                            eligibleRanks ...
                        ) ...
                    );

                    selectedRank = ...
                        eligibleRanks(localMaximumIndex);
                end

                selectedFrequenciesForRule(blockIndex) = ...
                    peakFrequencies(blockIndex, selectedRank);
            end

            currentToleranceMean = ...
                mean(selectedFrequenciesForRule);

            toleranceRuleMeans( ...
                summaryRow, ...
                toleranceIndex ...
            ) = currentToleranceMean;

            toleranceRuleDifferences( ...
                summaryRow, ...
                toleranceIndex ...
            ) = currentToleranceMean - articleMean;
        end

        subjectIDColumn(summaryRow) = subjectID;
        classLabelColumn(summaryRow) = classIndex;

        targetFrequencyColumn(summaryRow) = ...
            targetFrequencies(classIndex);

        articleMeanColumn(summaryRow) = articleMean;
        primaryPeakMeanColumn(summaryRow) = primaryPeakMean;

        primaryDifferenceColumn(summaryRow) = ...
            primaryPeakMean - articleMean;

        bestTop5MeanColumn(summaryRow) = ...
            candidateMeans(bestCombinationIndex);

        bestTop5ResidualColumn(summaryRow) = bestResidual;

        reachableWithinTwoDecimalsColumn(summaryRow) = ...
            bestResidual <= 0.02;

        nonPrimarySelectionsColumn(summaryRow) = ...
            sum(bestRanks > 1);

        closestToTargetMeanColumn(summaryRow) = ...
            mean(closestToTargetFrequencies);

        closestToTargetDifferenceColumn(summaryRow) = ...
            closestToTargetMeanColumn(summaryRow) - articleMean;

        selectedRankColumns(summaryRow, :) = bestRanks;
        selectedFrequencyColumns(summaryRow, :) = bestFrequencies;

        selectedAmplitudeRatioColumns(summaryRow, :) = ...
            bestAmplitudeRatios;

        for blockIndex = 1:numberOfBlocks

            detailRow = detailRow + 1;

            selectedRank = bestRanks(blockIndex);

            detailSubjectID(detailRow) = subjectID;
            detailClassLabel(detailRow) = classIndex;

            detailTargetFrequency(detailRow) = ...
                targetFrequencies(classIndex);

            detailBlock(detailRow) = blockIndex;
            detailSelectedRank(detailRow) = selectedRank;

            detailSelectedFrequency(detailRow) = ...
                peakFrequencies(blockIndex, selectedRank);

            detailPrimaryFrequency(detailRow) = ...
                peakFrequencies(blockIndex, 1);

            detailSelectedAmplitude(detailRow) = ...
                peakAmplitudes(blockIndex, selectedRank);

            detailPrimaryAmplitude(detailRow) = ...
                peakAmplitudes(blockIndex, 1);

            detailAmplitudeRatio(detailRow) = ...
                bestAmplitudeRatios(blockIndex);
        end
    end
end

summaryTable = table( ...
    subjectIDColumn, ...
    classLabelColumn, ...
    targetFrequencyColumn, ...
    articleMeanColumn, ...
    primaryPeakMeanColumn, ...
    primaryDifferenceColumn, ...
    bestTop5MeanColumn, ...
    bestTop5ResidualColumn, ...
    reachableWithinTwoDecimalsColumn, ...
    nonPrimarySelectionsColumn, ...
    closestToTargetMeanColumn, ...
    closestToTargetDifferenceColumn, ...
    'VariableNames', { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'ArticleMeanHz', ...
        'PrimaryPeakMeanHz', ...
        'PrimaryMinusArticleHz', ...
        'BestTop5CombinationMeanHz', ...
        'BestTop5ResidualHz', ...
        'ReachableWithinTwoDecimals', ...
        'NumberOfNonPrimarySelections', ...
        'ClosestTop5ToTargetMeanHz', ...
        'ClosestTop5ToTargetMinusArticleHz' ...
    } ...
);

for blockIndex = 1:numberOfBlocks

    summaryTable.( ...
        sprintf('SelectedRankBlock%d', blockIndex) ...
    ) = selectedRankColumns(:, blockIndex);

    summaryTable.( ...
        sprintf('SelectedFrequencyBlock%dHz', blockIndex) ...
    ) = selectedFrequencyColumns(:, blockIndex);

    summaryTable.( ...
        sprintf('SelectedAmplitudeRatioBlock%d', blockIndex) ...
    ) = selectedAmplitudeRatioColumns(:, blockIndex);
end

for toleranceIndex = 1:numberOfTolerances

    toleranceCode = round( ...
        10 * candidateTolerances(toleranceIndex) ...
    );

    summaryTable.( ...
        sprintf('StrongestWithin0p%dHzMean', toleranceCode) ...
    ) = toleranceRuleMeans(:, toleranceIndex);

    summaryTable.( ...
        sprintf('StrongestWithin0p%dHzMinusArticle', toleranceCode) ...
    ) = toleranceRuleDifferences(:, toleranceIndex);
end

detailTable = table( ...
    detailSubjectID, ...
    detailClassLabel, ...
    detailTargetFrequency, ...
    detailBlock, ...
    detailSelectedRank, ...
    detailSelectedFrequency, ...
    detailPrimaryFrequency, ...
    detailSelectedAmplitude, ...
    detailPrimaryAmplitude, ...
    detailAmplitudeRatio, ...
    'VariableNames', { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'Block', ...
        'SelectedPeakRank', ...
        'SelectedPeakFrequencyHz', ...
        'PrimaryPeakFrequencyHz', ...
        'SelectedPeakAmplitude', ...
        'PrimaryPeakAmplitude', ...
        'SelectedToPrimaryAmplitudeRatio' ...
    } ...
);

primaryMAD = mean(abs(primaryDifferenceColumn));
bestTop5MAD = mean(abs(bestTop5ResidualColumn));

closestTargetMAD = mean( ...
    abs(closestToTargetDifferenceColumn) ...
);

toleranceRuleMAD = zeros(numberOfTolerances, 1);

for toleranceIndex = 1:numberOfTolerances

    toleranceRuleMAD(toleranceIndex) = mean( ...
        abs( ...
            toleranceRuleDifferences(:, toleranceIndex) ...
        ) ...
    );
end

ruleName = strings( ...
    3 + numberOfTolerances, ...
    1 ...
);

meanAbsoluteDifferenceHz = zeros( ...
    3 + numberOfTolerances, ...
    1 ...
);

ruleName(1) = "Primary maximum-amplitude peak";
meanAbsoluteDifferenceHz(1) = primaryMAD;

ruleName(2) = "Best possible top-five combination";
meanAbsoluteDifferenceHz(2) = bestTop5MAD;

ruleName(3) = "Closest top-five peak to known target";
meanAbsoluteDifferenceHz(3) = closestTargetMAD;

for toleranceIndex = 1:numberOfTolerances

    ruleName(3 + toleranceIndex) = sprintf( ...
        'Strongest top-five peak within +/- %.1f Hz', ...
        candidateTolerances(toleranceIndex) ...
    );

    meanAbsoluteDifferenceHz(3 + toleranceIndex) = ...
        toleranceRuleMAD(toleranceIndex);
end

ruleSummaryTable = table( ...
    ruleName, ...
    meanAbsoluteDifferenceHz, ...
    'VariableNames', { ...
        'PeakSelectionRule', ...
        'MeanAbsoluteDifferenceHz' ...
    } ...
);

ruleSummaryTable = sortrows( ...
    ruleSummaryTable, ...
    'MeanAbsoluteDifferenceHz', ...
    'ascend' ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'groupB_rebuild' ...
);

summaryCsvFile = fullfile( ...
    outputDirectory, ...
    'B03_top5_peak_reachability.csv' ...
);

detailCsvFile = fullfile( ...
    outputDirectory, ...
    'B03_best_combination_trial_details.csv' ...
);

ruleSummaryCsvFile = fullfile( ...
    outputDirectory, ...
    'B03_peak_selection_rule_summary.csv' ...
);

resultMatFile = fullfile( ...
    outputDirectory, ...
    'B03_peak_selection_audit.mat' ...
);

writetable(summaryTable, summaryCsvFile);
writetable(detailTable, detailCsvFile);
writetable(ruleSummaryTable, ruleSummaryCsvFile);

save( ...
    resultMatFile, ...
    'summaryTable', ...
    'detailTable', ...
    'ruleSummaryTable', ...
    'peakRankCombinations', ...
    'candidateTolerances', ...
    'primaryMAD', ...
    'bestTop5MAD', ...
    'closestTargetMAD', ...
    'toleranceRuleMAD' ...
);

fprintf('\n================================================\n');
fprintf('B03 completed\n');
fprintf('================================================\n\n');

fprintf('Primary-peak MAD: %.4f Hz\n', primaryMAD);
fprintf('Best achievable MAD using top five peaks: %.4f Hz\n', ...
    bestTop5MAD);

fprintf('Closest-to-target top-five MAD: %.4f Hz\n', ...
    closestTargetMAD);

fprintf('Subject-class means reachable within 0.02 Hz: %d of %d\n\n', ...
    sum(reachableWithinTwoDecimalsColumn), ...
    numberOfRows);

fprintf('Peak-selection rule summary:\n');
disp(ruleSummaryTable);

fprintf('\nLargest primary-peak discrepancies:\n');

absolutePrimaryDifference = abs( ...
    summaryTable.PrimaryMinusArticleHz ...
);

[~, discrepancyOrder] = sort( ...
    absolutePrimaryDifference, ...
    'descend' ...
);

disp(summaryTable( ...
    discrepancyOrder(1:min(15, numberOfRows)), ...
    { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'ArticleMeanHz', ...
        'PrimaryPeakMeanHz', ...
        'PrimaryMinusArticleHz', ...
        'BestTop5CombinationMeanHz', ...
        'BestTop5ResidualHz', ...
        'NumberOfNonPrimarySelections' ...
    } ...
));

fprintf('\nSummary CSV:\n%s\n', summaryCsvFile);
fprintf('\nTrial-detail CSV:\n%s\n', detailCsvFile);
fprintf('\nRule-summary CSV:\n%s\n', ruleSummaryCsvFile);
fprintf('\nMAT results:\n%s\n', resultMatFile);
