clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(fileparts(scriptDirectory));

inputMatFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'groupB_rebuild', ...
    'GroupB_Rebuild_AllIntermediateResults.mat' ...
);

if ~isfile(inputMatFile)
    error('Input MAT file was not found:\n%s', inputMatFile);
end

loadedData = load(inputMatFile);

requiredVariables = {
    'trialTable'
    'articleGroupBMeans'
    'groupBSubjectIDs'
    'targetFrequencies'
};

for variableIndex = 1:numel(requiredVariables)

    variableName = requiredVariables{variableIndex};

    if ~isfield(loadedData, variableName)
        error('Required variable was not found: %s', variableName);
    end
end

trialTable = loadedData.trialTable;
articleGroupBMeans = loadedData.articleGroupBMeans;
groupBSubjectIDs = loadedData.groupBSubjectIDs(:);
targetFrequencies = loadedData.targetFrequencies(:)';

numberOfSubjects = numel(groupBSubjectIDs);
numberOfClasses = numel(targetFrequencies);
numberOfBlocks = 6;
numberOfPeaks = 5;

articleMeanToleranceHz = 0.02;
numericalTolerance = 1e-12;

peakFrequencyVariableNames = cell(1, numberOfPeaks);
peakAmplitudeVariableNames = cell(1, numberOfPeaks);

for peakIndex = 1:numberOfPeaks

    peakFrequencyVariableNames{peakIndex} = ...
        sprintf('Peak%dFrequencyHz', peakIndex);

    peakAmplitudeVariableNames{peakIndex} = ...
        sprintf('Peak%dAmplitude', peakIndex);

    if ~ismember( ...
            peakFrequencyVariableNames{peakIndex}, ...
            trialTable.Properties.VariableNames ...
        )

        error( ...
            'Required variable was not found: %s', ...
            peakFrequencyVariableNames{peakIndex} ...
        );
    end

    if ~ismember( ...
            peakAmplitudeVariableNames{peakIndex}, ...
            trialTable.Properties.VariableNames ...
        )

        error( ...
            'Required variable was not found: %s', ...
            peakAmplitudeVariableNames{peakIndex} ...
        );
    end
end

combinationGrids = cell(1, numberOfBlocks);
[combinationGrids{:}] = ndgrid(1:numberOfPeaks);

numberOfCombinations = numberOfPeaks ^ numberOfBlocks;
peakRankCombinations = zeros(numberOfCombinations, numberOfBlocks);

for blockIndex = 1:numberOfBlocks

    peakRankCombinations(:, blockIndex) = ...
        combinationGrids{blockIndex}(:);
end

numberOfPairs = numberOfSubjects * numberOfClasses;
numberOfBlockRows = numberOfPairs * numberOfBlocks;

pairSubjectID = zeros(numberOfPairs, 1);
pairClassLabel = zeros(numberOfPairs, 1);
pairTargetFrequency = zeros(numberOfPairs, 1);
pairArticleMean = zeros(numberOfPairs, 1);
pairPrimaryMean = zeros(numberOfPairs, 1);
pairPrimaryResidual = zeros(numberOfPairs, 1);
pairMinimumResidual = zeros(numberOfPairs, 1);
pairNumberAcceptableCombinations = zeros(numberOfPairs, 1);
pairNumberExactBestCombinations = zeros(numberOfPairs, 1);
pairMedianNonPrimarySelections = zeros(numberOfPairs, 1);
pairMinimumNonPrimarySelections = zeros(numberOfPairs, 1);
pairMaximumNonPrimarySelections = zeros(numberOfPairs, 1);

blockSubjectID = zeros(numberOfBlockRows, 1);
blockClassLabel = zeros(numberOfBlockRows, 1);
blockTargetFrequency = zeros(numberOfBlockRows, 1);
blockNumber = zeros(numberOfBlockRows, 1);
blockArticleMean = zeros(numberOfBlockRows, 1);
blockPrimaryFrequency = zeros(numberOfBlockRows, 1);
blockPrimaryAmplitude = zeros(numberOfBlockRows, 1);
blockPrimaryDistanceToTarget = zeros(numberOfBlockRows, 1);

blockPreferredRank = zeros(numberOfBlockRows, 1);
blockPreferredRankSupport = zeros(numberOfBlockRows, 1);
blockNumberSupportedRanks = zeros(numberOfBlockRows, 1);
blockPrimaryRankSupported = false(numberOfBlockRows, 1);
blockForcedNonPrimary = false(numberOfBlockRows, 1);
blockAmbiguous = false(numberOfBlockRows, 1);
blockExpectedAmplitudeRatio = zeros(numberOfBlockRows, 1);
blockExpectedDistanceToTarget = zeros(numberOfBlockRows, 1);

rankSupportMatrix = zeros(numberOfBlockRows, numberOfPeaks);
rankFrequencyMatrix = zeros(numberOfBlockRows, numberOfPeaks);
rankAmplitudeMatrix = zeros(numberOfBlockRows, numberOfPeaks);
rankAmplitudeRatioMatrix = zeros(numberOfBlockRows, numberOfPeaks);
rankDistanceToTargetMatrix = zeros(numberOfBlockRows, numberOfPeaks);

pairRow = 0;
blockRow = 0;

fprintf('================================================\n');
fprintf('B04: Rank and amplitude-pattern analysis\n');
fprintf('================================================\n\n');

fprintf('Subjects: %d\n', numberOfSubjects);
fprintf('Classes: %d\n', numberOfClasses);
fprintf('Subject-class pairs: %d\n', numberOfPairs);
fprintf('Blocks: %d\n', numberOfBlockRows);
fprintf('Peak ranks per trial: %d\n', numberOfPeaks);
fprintf('Combinations per pair: %d\n', numberOfCombinations);
fprintf('Article-mean tolerance: +/- %.3f Hz\n\n', ...
    articleMeanToleranceHz);

for subjectIndex = 1:numberOfSubjects

    subjectID = groupBSubjectIDs(subjectIndex);

    for classIndex = 1:numberOfClasses

        pairRow = pairRow + 1;

        currentMask = ...
            trialTable.SubjectID == subjectID & ...
            trialTable.ClassLabel == classIndex;

        currentTrials = sortrows( ...
            trialTable(currentMask, :), ...
            'Block' ...
        );

        if height(currentTrials) ~= numberOfBlocks
            error( ...
                'Expected %d trials for S%d class %d, found %d.', ...
                numberOfBlocks, ...
                subjectID, ...
                classIndex, ...
                height(currentTrials) ...
            );
        end

        peakFrequencies = zeros(numberOfBlocks, numberOfPeaks);
        peakAmplitudes = zeros(numberOfBlocks, numberOfPeaks);

        for peakIndex = 1:numberOfPeaks

            peakFrequencies(:, peakIndex) = ...
                currentTrials.( ...
                    peakFrequencyVariableNames{peakIndex} ...
                );

            peakAmplitudes(:, peakIndex) = ...
                currentTrials.( ...
                    peakAmplitudeVariableNames{peakIndex} ...
                );
        end

        articleMean = articleGroupBMeans( ...
            subjectIndex, ...
            classIndex ...
        );

        candidateSelectedFrequencies = zeros( ...
            numberOfCombinations, ...
            numberOfBlocks ...
        );

        for blockIndex = 1:numberOfBlocks

            candidateSelectedFrequencies(:, blockIndex) = ...
                peakFrequencies( ...
                    blockIndex, ...
                    peakRankCombinations(:, blockIndex) ...
                )';
        end

        candidateMeans = mean( ...
            candidateSelectedFrequencies, ...
            2 ...
        );

        candidateResiduals = abs( ...
            candidateMeans - articleMean ...
        );

        minimumResidual = min(candidateResiduals);

        exactBestMask = ...
            candidateResiduals <= ...
            minimumResidual + numericalTolerance;

        acceptableMask = ...
            candidateResiduals <= ...
            articleMeanToleranceHz + numericalTolerance;

        if ~any(acceptableMask)

            warning( ...
                ['No combination fell within the requested tolerance for ' ...
                 'S%d class %d. Exact-best combinations are used instead.'], ...
                subjectID, ...
                classIndex ...
            );

            acceptableMask = exactBestMask;
        end

        acceptableCombinations = ...
            peakRankCombinations(acceptableMask, :);

        numberOfAcceptableCombinations = ...
            size(acceptableCombinations, 1);

        nonPrimaryCounts = sum( ...
            acceptableCombinations > 1, ...
            2 ...
        );

        pairSubjectID(pairRow) = subjectID;
        pairClassLabel(pairRow) = classIndex;

        pairTargetFrequency(pairRow) = ...
            targetFrequencies(classIndex);

        pairArticleMean(pairRow) = articleMean;

        pairPrimaryMean(pairRow) = ...
            mean(peakFrequencies(:, 1));

        pairPrimaryResidual(pairRow) = ...
            pairPrimaryMean(pairRow) - articleMean;

        pairMinimumResidual(pairRow) = minimumResidual;

        pairNumberAcceptableCombinations(pairRow) = ...
            numberOfAcceptableCombinations;

        pairNumberExactBestCombinations(pairRow) = ...
            sum(exactBestMask);

        pairMedianNonPrimarySelections(pairRow) = ...
            median(nonPrimaryCounts);

        pairMinimumNonPrimarySelections(pairRow) = ...
            min(nonPrimaryCounts);

        pairMaximumNonPrimarySelections(pairRow) = ...
            max(nonPrimaryCounts);

        for blockIndex = 1:numberOfBlocks

            blockRow = blockRow + 1;

            rankCounts = zeros(1, numberOfPeaks);

            for peakIndex = 1:numberOfPeaks

                rankCounts(peakIndex) = sum( ...
                    acceptableCombinations(:, blockIndex) == ...
                    peakIndex ...
                );
            end

            rankSupport = ...
                rankCounts / numberOfAcceptableCombinations;

            [preferredSupport, preferredRank] = max(rankSupport);

            amplitudeRatios = ...
                peakAmplitudes(blockIndex, :) ./ ...
                peakAmplitudes(blockIndex, 1);

            distanceToTarget = abs( ...
                peakFrequencies(blockIndex, :) - ...
                targetFrequencies(classIndex) ...
            );

            blockSubjectID(blockRow) = subjectID;
            blockClassLabel(blockRow) = classIndex;

            blockTargetFrequency(blockRow) = ...
                targetFrequencies(classIndex);

            blockNumber(blockRow) = blockIndex;
            blockArticleMean(blockRow) = articleMean;

            blockPrimaryFrequency(blockRow) = ...
                peakFrequencies(blockIndex, 1);

            blockPrimaryAmplitude(blockRow) = ...
                peakAmplitudes(blockIndex, 1);

            blockPrimaryDistanceToTarget(blockRow) = ...
                distanceToTarget(1);

            blockPreferredRank(blockRow) = preferredRank;

            blockPreferredRankSupport(blockRow) = ...
                preferredSupport;

            blockNumberSupportedRanks(blockRow) = ...
                sum(rankSupport > 0);

            blockPrimaryRankSupported(blockRow) = ...
                rankSupport(1) > 0;

            blockForcedNonPrimary(blockRow) = ...
                rankSupport(1) == 0;

            blockAmbiguous(blockRow) = ...
                sum(rankSupport > 0) > 1;

            blockExpectedAmplitudeRatio(blockRow) = ...
                sum(rankSupport .* amplitudeRatios);

            blockExpectedDistanceToTarget(blockRow) = ...
                sum(rankSupport .* distanceToTarget);

            rankSupportMatrix(blockRow, :) = rankSupport;
            rankFrequencyMatrix(blockRow, :) = ...
                peakFrequencies(blockIndex, :);

            rankAmplitudeMatrix(blockRow, :) = ...
                peakAmplitudes(blockIndex, :);

            rankAmplitudeRatioMatrix(blockRow, :) = ...
                amplitudeRatios;

            rankDistanceToTargetMatrix(blockRow, :) = ...
                distanceToTarget;
        end
    end
end

pairSummaryTable = table( ...
    pairSubjectID, ...
    pairClassLabel, ...
    pairTargetFrequency, ...
    pairArticleMean, ...
    pairPrimaryMean, ...
    pairPrimaryResidual, ...
    pairMinimumResidual, ...
    pairNumberAcceptableCombinations, ...
    pairNumberExactBestCombinations, ...
    pairMedianNonPrimarySelections, ...
    pairMinimumNonPrimarySelections, ...
    pairMaximumNonPrimarySelections, ...
    'VariableNames', { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'ArticleMeanHz', ...
        'PrimaryPeakMeanHz', ...
        'PrimaryMinusArticleHz', ...
        'MinimumAchievableResidualHz', ...
        'NumberOfAcceptableCombinations', ...
        'NumberOfExactBestCombinations', ...
        'MedianNonPrimarySelections', ...
        'MinimumNonPrimarySelections', ...
        'MaximumNonPrimarySelections' ...
    } ...
);

blockSupportTable = table( ...
    blockSubjectID, ...
    blockClassLabel, ...
    blockTargetFrequency, ...
    blockNumber, ...
    blockArticleMean, ...
    blockPrimaryFrequency, ...
    blockPrimaryAmplitude, ...
    blockPrimaryDistanceToTarget, ...
    blockPreferredRank, ...
    blockPreferredRankSupport, ...
    blockNumberSupportedRanks, ...
    blockPrimaryRankSupported, ...
    blockForcedNonPrimary, ...
    blockAmbiguous, ...
    blockExpectedAmplitudeRatio, ...
    blockExpectedDistanceToTarget, ...
    'VariableNames', { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'Block', ...
        'ArticleMeanHz', ...
        'PrimaryPeakFrequencyHz', ...
        'PrimaryPeakAmplitude', ...
        'PrimaryPeakDistanceToTargetHz', ...
        'PreferredRank', ...
        'PreferredRankSupport', ...
        'NumberOfSupportedRanks', ...
        'PrimaryRankSupported', ...
        'ForcedNonPrimary', ...
        'AmbiguousRankChoice', ...
        'ExpectedSelectedToPrimaryAmplitudeRatio', ...
        'ExpectedSelectedDistanceToTargetHz' ...
    } ...
);

for peakIndex = 1:numberOfPeaks

    blockSupportTable.( ...
        sprintf('Rank%dSupport', peakIndex) ...
    ) = rankSupportMatrix(:, peakIndex);

    blockSupportTable.( ...
        sprintf('Rank%dFrequencyHz', peakIndex) ...
    ) = rankFrequencyMatrix(:, peakIndex);

    blockSupportTable.( ...
        sprintf('Rank%dAmplitudeRatio', peakIndex) ...
    ) = rankAmplitudeRatioMatrix(:, peakIndex);

    blockSupportTable.( ...
        sprintf('Rank%dDistanceToTargetHz', peakIndex) ...
    ) = rankDistanceToTargetMatrix(:, peakIndex);
end

rankColumn = (1:numberOfPeaks)';

meanSupport = mean(rankSupportMatrix, 1)';
medianSupport = median(rankSupportMatrix, 1)';
preferredRankCount = zeros(numberOfPeaks, 1);
preferredRankPercentage = zeros(numberOfPeaks, 1);

meanAmplitudeRatio = mean(rankAmplitudeRatioMatrix, 1)';
medianAmplitudeRatio = median(rankAmplitudeRatioMatrix, 1)';
minimumAmplitudeRatio = min(rankAmplitudeRatioMatrix, [], 1)';
maximumAmplitudeRatio = max(rankAmplitudeRatioMatrix, [], 1)';

meanDistanceToTarget = mean(rankDistanceToTargetMatrix, 1)';
medianDistanceToTarget = median(rankDistanceToTargetMatrix, 1)';

for peakIndex = 1:numberOfPeaks

    preferredRankCount(peakIndex) = sum( ...
        blockPreferredRank == peakIndex ...
    );

    preferredRankPercentage(peakIndex) = ...
        100 * preferredRankCount(peakIndex) / numberOfBlockRows;
end

overallRankSummaryTable = table( ...
    rankColumn, ...
    meanSupport, ...
    medianSupport, ...
    preferredRankCount, ...
    preferredRankPercentage, ...
    meanAmplitudeRatio, ...
    medianAmplitudeRatio, ...
    minimumAmplitudeRatio, ...
    maximumAmplitudeRatio, ...
    meanDistanceToTarget, ...
    medianDistanceToTarget, ...
    'VariableNames', { ...
        'PeakRank', ...
        'MeanArticleConsistentSupport', ...
        'MedianArticleConsistentSupport', ...
        'PreferredRankCount', ...
        'PreferredRankPercentage', ...
        'MeanAmplitudeRatioToPrimary', ...
        'MedianAmplitudeRatioToPrimary', ...
        'MinimumAmplitudeRatioToPrimary', ...
        'MaximumAmplitudeRatioToPrimary', ...
        'MeanDistanceToTargetHz', ...
        'MedianDistanceToTargetHz' ...
    } ...
);

classLabelForSummary = zeros( ...
    numberOfClasses * numberOfPeaks, ...
    1 ...
);

rankForClassSummary = zeros( ...
    numberOfClasses * numberOfPeaks, ...
    1 ...
);

classMeanSupport = zeros( ...
    numberOfClasses * numberOfPeaks, ...
    1 ...
);

classPreferredCount = zeros( ...
    numberOfClasses * numberOfPeaks, ...
    1 ...
);

classPreferredPercentage = zeros( ...
    numberOfClasses * numberOfPeaks, ...
    1 ...
);

classSummaryRow = 0;

for classIndex = 1:numberOfClasses

    classMask = blockClassLabel == classIndex;
    classBlockCount = sum(classMask);

    for peakIndex = 1:numberOfPeaks

        classSummaryRow = classSummaryRow + 1;

        classLabelForSummary(classSummaryRow) = classIndex;
        rankForClassSummary(classSummaryRow) = peakIndex;

        classMeanSupport(classSummaryRow) = mean( ...
            rankSupportMatrix(classMask, peakIndex) ...
        );

        classPreferredCount(classSummaryRow) = sum( ...
            blockPreferredRank(classMask) == peakIndex ...
        );

        classPreferredPercentage(classSummaryRow) = ...
            100 * classPreferredCount(classSummaryRow) / ...
            classBlockCount;
    end
end

classwiseRankSummaryTable = table( ...
    classLabelForSummary, ...
    rankForClassSummary, ...
    classMeanSupport, ...
    classPreferredCount, ...
    classPreferredPercentage, ...
    'VariableNames', { ...
        'ClassLabel', ...
        'PeakRank', ...
        'MeanArticleConsistentSupport', ...
        'PreferredRankCount', ...
        'PreferredRankPercentage' ...
    } ...
);

fixedRank = (1:numberOfPeaks)';
fixedRankMAD = zeros(numberOfPeaks, 1);
fixedRankRMSE = zeros(numberOfPeaks, 1);
fixedRankMaximumDifference = zeros(numberOfPeaks, 1);

fixedRankPairMeans = zeros(numberOfPairs, numberOfPeaks);

pairRow = 0;

for subjectIndex = 1:numberOfSubjects

    subjectID = groupBSubjectIDs(subjectIndex);

    for classIndex = 1:numberOfClasses

        pairRow = pairRow + 1;

        currentMask = ...
            trialTable.SubjectID == subjectID & ...
            trialTable.ClassLabel == classIndex;

        currentTrials = sortrows( ...
            trialTable(currentMask, :), ...
            'Block' ...
        );

        for peakIndex = 1:numberOfPeaks

            fixedRankPairMeans(pairRow, peakIndex) = mean( ...
                currentTrials.( ...
                    peakFrequencyVariableNames{peakIndex} ...
                ) ...
            );
        end
    end
end

articleMeanVector = pairArticleMean;

for peakIndex = 1:numberOfPeaks

    currentDifferences = ...
        fixedRankPairMeans(:, peakIndex) - ...
        articleMeanVector;

    fixedRankMAD(peakIndex) = ...
        mean(abs(currentDifferences));

    fixedRankRMSE(peakIndex) = ...
        sqrt(mean(currentDifferences .^ 2));

    fixedRankMaximumDifference(peakIndex) = ...
        max(abs(currentDifferences));
end

fixedRankRuleTable = table( ...
    fixedRank, ...
    fixedRankMAD, ...
    fixedRankRMSE, ...
    fixedRankMaximumDifference, ...
    'VariableNames', { ...
        'PeakRankUsedForEveryTrial', ...
        'MeanAbsoluteDifferenceHz', ...
        'RootMeanSquaredDifferenceHz', ...
        'MaximumAbsoluteDifferenceHz' ...
    } ...
);

fixedRankRuleTable = sortrows( ...
    fixedRankRuleTable, ...
    'MeanAbsoluteDifferenceHz', ...
    'ascend' ...
);

numberPrimarySupported = sum(blockPrimaryRankSupported);
numberForcedNonPrimary = sum(blockForcedNonPrimary);
numberAmbiguous = sum(blockAmbiguous);
numberSingleRank = sum(blockNumberSupportedRanks == 1);

diagnosticName = [
    "Total block-level decisions"
    "Primary rank supported"
    "Primary rank impossible within article tolerance"
    "Ambiguous: multiple ranks supported"
    "Only one rank supported"
];

diagnosticCount = [
    numberOfBlockRows
    numberPrimarySupported
    numberForcedNonPrimary
    numberAmbiguous
    numberSingleRank
];

diagnosticPercentage = ...
    100 * diagnosticCount / numberOfBlockRows;

diagnosticTable = table( ...
    diagnosticName, ...
    diagnosticCount, ...
    diagnosticPercentage, ...
    'VariableNames', { ...
        'Diagnostic', ...
        'Count', ...
        'Percentage' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'groupB_rebuild' ...
);

pairCsvFile = fullfile( ...
    outputDirectory, ...
    'B04_pair_combination_summary.csv' ...
);

blockCsvFile = fullfile( ...
    outputDirectory, ...
    'B04_block_rank_support.csv' ...
);

overallRankCsvFile = fullfile( ...
    outputDirectory, ...
    'B04_overall_rank_summary.csv' ...
);

classwiseRankCsvFile = fullfile( ...
    outputDirectory, ...
    'B04_classwise_rank_summary.csv' ...
);

fixedRankCsvFile = fullfile( ...
    outputDirectory, ...
    'B04_fixed_rank_rule_results.csv' ...
);

diagnosticCsvFile = fullfile( ...
    outputDirectory, ...
    'B04_structural_diagnostics.csv' ...
);

resultMatFile = fullfile( ...
    outputDirectory, ...
    'B04_rank_amplitude_pattern_results.mat' ...
);

writetable(pairSummaryTable, pairCsvFile);
writetable(blockSupportTable, blockCsvFile);
writetable(overallRankSummaryTable, overallRankCsvFile);
writetable(classwiseRankSummaryTable, classwiseRankCsvFile);
writetable(fixedRankRuleTable, fixedRankCsvFile);
writetable(diagnosticTable, diagnosticCsvFile);

save( ...
    resultMatFile, ...
    'pairSummaryTable', ...
    'blockSupportTable', ...
    'overallRankSummaryTable', ...
    'classwiseRankSummaryTable', ...
    'fixedRankRuleTable', ...
    'diagnosticTable', ...
    'rankSupportMatrix', ...
    'rankFrequencyMatrix', ...
    'rankAmplitudeMatrix', ...
    'rankAmplitudeRatioMatrix', ...
    'rankDistanceToTargetMatrix', ...
    'peakRankCombinations', ...
    'articleMeanToleranceHz', ...
    '-v7.3' ...
);

fprintf('\n================================================\n');
fprintf('B04 completed\n');
fprintf('================================================\n\n');

fprintf('Structural diagnostics:\n');
disp(diagnosticTable);

fprintf('\nOverall rank support and amplitude patterns:\n');
disp(overallRankSummaryTable);

fprintf('\nFixed-rank rules:\n');
disp(fixedRankRuleTable);

fprintf('\nClass-wise rank support:\n');
disp(classwiseRankSummaryTable);

fprintf('\nAcceptable combinations per subject-class pair:\n');
fprintf('Minimum: %d\n', ...
    min(pairNumberAcceptableCombinations));

fprintf('Median: %.1f\n', ...
    median(pairNumberAcceptableCombinations));

fprintf('Maximum: %d\n', ...
    max(pairNumberAcceptableCombinations));

fprintf('\nPairs with largest primary-peak discrepancies:\n');

[~, discrepancyOrder] = sort( ...
    abs(pairPrimaryResidual), ...
    'descend' ...
);

disp(pairSummaryTable( ...
    discrepancyOrder(1:min(15, numberOfPairs)), ...
    { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'ArticleMeanHz', ...
        'PrimaryPeakMeanHz', ...
        'PrimaryMinusArticleHz', ...
        'MinimumAchievableResidualHz', ...
        'NumberOfAcceptableCombinations', ...
        'MedianNonPrimarySelections', ...
        'MinimumNonPrimarySelections', ...
        'MaximumNonPrimarySelections' ...
    } ...
));

fprintf('\nPair summary CSV:\n%s\n', pairCsvFile);
fprintf('\nBlock-rank support CSV:\n%s\n', blockCsvFile);
fprintf('\nOverall-rank summary CSV:\n%s\n', overallRankCsvFile);
fprintf('\nClass-wise summary CSV:\n%s\n', classwiseRankCsvFile);
fprintf('\nFixed-rank rules CSV:\n%s\n', fixedRankCsvFile);
fprintf('\nDiagnostics CSV:\n%s\n', diagnosticCsvFile);
fprintf('\nMAT results:\n%s\n', resultMatFile);
