clear;
clc;
close all;

scriptDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(fileparts(scriptDirectory));

inputMatFile = fullfile( ...
    projectDirectory, ...
    'results', ...
    'groupB_rebuild', ...
    'B04_rank_amplitude_pattern_results.mat' ...
);

if ~isfile(inputMatFile)
    error('B04 MAT file was not found:\n%s', inputMatFile);
end

loadedData = load(inputMatFile, ...
    'blockSupportTable', ...
    'pairSummaryTable');

blockSupportTable = loadedData.blockSupportTable;
pairSummaryTable = loadedData.pairSummaryTable;

numberOfPeaks = 5;

requiredVariables = {
    'SubjectID'
    'ClassLabel'
    'TargetFrequencyHz'
    'Block'
    'ArticleMeanHz'
    'PrimaryPeakFrequencyHz'
    'PrimaryPeakAmplitude'
    'ForcedNonPrimary'
    'AmbiguousRankChoice'
};

for variableIndex = 1:numel(requiredVariables)

    variableName = requiredVariables{variableIndex};

    if ~ismember( ...
            variableName, ...
            blockSupportTable.Properties.VariableNames ...
        )

        error('Required variable was not found: %s', variableName);
    end
end

forcedMask = blockSupportTable.ForcedNonPrimary;
forcedTable = blockSupportTable(forcedMask, :);

numberOfForcedBlocks = height(forcedTable);

if numberOfForcedBlocks == 0
    error('No forced non-primary blocks were found.');
end

strongestSupportedRank = zeros(numberOfForcedBlocks, 1);
strongestSupportedFrequencyHz = zeros(numberOfForcedBlocks, 1);
strongestSupportedAmplitudeRatio = zeros(numberOfForcedBlocks, 1);
strongestSupportedRankSupport = zeros(numberOfForcedBlocks, 1);
strongestSupportedDistanceToTargetHz = zeros(numberOfForcedBlocks, 1);
amplitudeGapFromPrimary = zeros(numberOfForcedBlocks, 1);

preferredRank = forcedTable.PreferredRank;
preferredRankSupport = forcedTable.PreferredRankSupport;
preferredRankFrequencyHz = zeros(numberOfForcedBlocks, 1);
preferredRankAmplitudeRatio = zeros(numberOfForcedBlocks, 1);
preferredRankDistanceToTargetHz = zeros(numberOfForcedBlocks, 1);

numberOfSupportedNonPrimaryRanks = zeros(numberOfForcedBlocks, 1);

for rowIndex = 1:numberOfForcedBlocks

    supportedRanks = [];

    for peakRank = 2:numberOfPeaks

        supportVariable = sprintf('Rank%dSupport', peakRank);

        if forcedTable.(supportVariable)(rowIndex) > 0
            supportedRanks(end + 1) = peakRank;
        end
    end

    if isempty(supportedRanks)
        error( ...
            'No supported non-primary rank was found in forced row %d.', ...
            rowIndex ...
        );
    end

    numberOfSupportedNonPrimaryRanks(rowIndex) = ...
        numel(supportedRanks);

    currentStrongestRank = min(supportedRanks);

    strongestSupportedRank(rowIndex) = ...
        currentStrongestRank;

    strongestSupportedFrequencyHz(rowIndex) = ...
        forcedTable.( ...
            sprintf('Rank%dFrequencyHz', currentStrongestRank) ...
        )(rowIndex);

    strongestSupportedAmplitudeRatio(rowIndex) = ...
        forcedTable.( ...
            sprintf('Rank%dAmplitudeRatio', currentStrongestRank) ...
        )(rowIndex);

    strongestSupportedRankSupport(rowIndex) = ...
        forcedTable.( ...
            sprintf('Rank%dSupport', currentStrongestRank) ...
        )(rowIndex);

    strongestSupportedDistanceToTargetHz(rowIndex) = ...
        forcedTable.( ...
            sprintf('Rank%dDistanceToTargetHz', currentStrongestRank) ...
        )(rowIndex);

    amplitudeGapFromPrimary(rowIndex) = ...
        1 - strongestSupportedAmplitudeRatio(rowIndex);

    currentPreferredRank = preferredRank(rowIndex);

    preferredRankFrequencyHz(rowIndex) = ...
        forcedTable.( ...
            sprintf('Rank%dFrequencyHz', currentPreferredRank) ...
        )(rowIndex);

    preferredRankAmplitudeRatio(rowIndex) = ...
        forcedTable.( ...
            sprintf('Rank%dAmplitudeRatio', currentPreferredRank) ...
        )(rowIndex);

    preferredRankDistanceToTargetHz(rowIndex) = ...
        forcedTable.( ...
            sprintf('Rank%dDistanceToTargetHz', currentPreferredRank) ...
        )(rowIndex);
end

nearTie95 = strongestSupportedAmplitudeRatio >= 0.95;
nearTie90 = strongestSupportedAmplitudeRatio >= 0.90;
nearTie80 = strongestSupportedAmplitudeRatio >= 0.80;
nearTie70 = strongestSupportedAmplitudeRatio >= 0.70;

forcedAnalysisTable = table( ...
    forcedTable.SubjectID, ...
    forcedTable.ClassLabel, ...
    forcedTable.TargetFrequencyHz, ...
    forcedTable.Block, ...
    forcedTable.ArticleMeanHz, ...
    forcedTable.PrimaryPeakFrequencyHz, ...
    forcedTable.PrimaryPeakDistanceToTargetHz, ...
    strongestSupportedRank, ...
    strongestSupportedFrequencyHz, ...
    strongestSupportedAmplitudeRatio, ...
    amplitudeGapFromPrimary, ...
    strongestSupportedRankSupport, ...
    strongestSupportedDistanceToTargetHz, ...
    preferredRank, ...
    preferredRankSupport, ...
    preferredRankFrequencyHz, ...
    preferredRankAmplitudeRatio, ...
    preferredRankDistanceToTargetHz, ...
    numberOfSupportedNonPrimaryRanks, ...
    nearTie95, ...
    nearTie90, ...
    nearTie80, ...
    nearTie70, ...
    'VariableNames', { ...
        'SubjectID', ...
        'ClassLabel', ...
        'TargetFrequencyHz', ...
        'Block', ...
        'ArticleMeanHz', ...
        'PrimaryPeakFrequencyHz', ...
        'PrimaryPeakDistanceToTargetHz', ...
        'StrongestArticleConsistentRank', ...
        'StrongestArticleConsistentFrequencyHz', ...
        'StrongestArticleConsistentAmplitudeRatio', ...
        'AmplitudeGapFromPrimary', ...
        'StrongestArticleConsistentRankSupport', ...
        'StrongestArticleConsistentDistanceToTargetHz', ...
        'PreferredRank', ...
        'PreferredRankSupport', ...
        'PreferredRankFrequencyHz', ...
        'PreferredRankAmplitudeRatio', ...
        'PreferredRankDistanceToTargetHz', ...
        'NumberOfSupportedNonPrimaryRanks', ...
        'NearTieAt95Percent', ...
        'NearTieAt90Percent', ...
        'NearTieAt80Percent', ...
        'NearTieAt70Percent' ...
    } ...
);

forcedAnalysisTable = sortrows( ...
    forcedAnalysisTable, ...
    'StrongestArticleConsistentAmplitudeRatio', ...
    'descend' ...
);

thresholdLabel = [
    "Amplitude ratio >= 0.95"
    "Amplitude ratio >= 0.90"
    "Amplitude ratio >= 0.80"
    "Amplitude ratio >= 0.70"
    "Amplitude ratio < 0.70"
];

thresholdCount = [
    sum(nearTie95)
    sum(nearTie90)
    sum(nearTie80)
    sum(nearTie70)
    sum(~nearTie70)
];

thresholdPercentage = ...
    100 * thresholdCount / numberOfForcedBlocks;

nearTieSummaryTable = table( ...
    thresholdLabel, ...
    thresholdCount, ...
    thresholdPercentage, ...
    'VariableNames', { ...
        'Criterion', ...
        'Count', ...
        'PercentageOfForcedBlocks' ...
    } ...
);

rank = (2:numberOfPeaks)';
forcedRankCount = zeros(numberOfPeaks - 1, 1);
forcedRankPercentage = zeros(numberOfPeaks - 1, 1);

for index = 1:numel(rank)

    forcedRankCount(index) = sum( ...
        strongestSupportedRank == rank(index) ...
    );

    forcedRankPercentage(index) = ...
        100 * forcedRankCount(index) / numberOfForcedBlocks;
end

forcedRankSummaryTable = table( ...
    rank, ...
    forcedRankCount, ...
    forcedRankPercentage, ...
    'VariableNames', { ...
        'StrongestSupportedPeakRank', ...
        'Count', ...
        'PercentageOfForcedBlocks' ...
    } ...
);

pairKeyForced = strcat( ...
    "S", ...
    string(forcedAnalysisTable.SubjectID), ...
    "_C", ...
    string(forcedAnalysisTable.ClassLabel) ...
);

uniquePairKeys = unique(pairKeyForced);
numberOfForcedPairs = numel(uniquePairKeys);

forcedPairSubjectID = zeros(numberOfForcedPairs, 1);
forcedPairClassLabel = zeros(numberOfForcedPairs, 1);
forcedBlocksInPair = zeros(numberOfForcedPairs, 1);
meanStrongestAmplitudeRatio = zeros(numberOfForcedPairs, 1);
minimumStrongestAmplitudeRatio = zeros(numberOfForcedPairs, 1);
maximumStrongestAmplitudeRatio = zeros(numberOfForcedPairs, 1);

for pairIndex = 1:numberOfForcedPairs

    currentMask = pairKeyForced == uniquePairKeys(pairIndex);
    currentRows = forcedAnalysisTable(currentMask, :);

    forcedPairSubjectID(pairIndex) = ...
        currentRows.SubjectID(1);

    forcedPairClassLabel(pairIndex) = ...
        currentRows.ClassLabel(1);

    forcedBlocksInPair(pairIndex) = ...
        height(currentRows);

    meanStrongestAmplitudeRatio(pairIndex) = mean( ...
        currentRows.StrongestArticleConsistentAmplitudeRatio ...
    );

    minimumStrongestAmplitudeRatio(pairIndex) = min( ...
        currentRows.StrongestArticleConsistentAmplitudeRatio ...
    );

    maximumStrongestAmplitudeRatio(pairIndex) = max( ...
        currentRows.StrongestArticleConsistentAmplitudeRatio ...
    );
end

forcedPairSummaryTable = table( ...
    forcedPairSubjectID, ...
    forcedPairClassLabel, ...
    forcedBlocksInPair, ...
    meanStrongestAmplitudeRatio, ...
    minimumStrongestAmplitudeRatio, ...
    maximumStrongestAmplitudeRatio, ...
    'VariableNames', { ...
        'SubjectID', ...
        'ClassLabel', ...
        'ForcedBlocks', ...
        'MeanStrongestConsistentAmplitudeRatio', ...
        'MinimumStrongestConsistentAmplitudeRatio', ...
        'MaximumStrongestConsistentAmplitudeRatio' ...
    } ...
);

forcedPairSummaryTable = sortrows( ...
    forcedPairSummaryTable, ...
    {'ForcedBlocks', 'MeanStrongestConsistentAmplitudeRatio'}, ...
    {'descend', 'ascend'} ...
);

meanRatio = mean(strongestSupportedAmplitudeRatio);
medianRatio = median(strongestSupportedAmplitudeRatio);
minimumRatio = min(strongestSupportedAmplitudeRatio);
maximumRatio = max(strongestSupportedAmplitudeRatio);

meanFrequencyDistance = mean( ...
    abs( ...
        strongestSupportedFrequencyHz - ...
        forcedAnalysisTable.PrimaryPeakFrequencyHz ...
    ) ...
);

medianFrequencyDistance = median( ...
    abs( ...
        strongestSupportedFrequencyHz - ...
        forcedAnalysisTable.PrimaryPeakFrequencyHz ...
    ) ...
);

statistic = [
    "Number of forced non-primary blocks"
    "Mean amplitude ratio"
    "Median amplitude ratio"
    "Minimum amplitude ratio"
    "Maximum amplitude ratio"
    "Mean frequency distance from primary peak (Hz)"
    "Median frequency distance from primary peak (Hz)"
];

value = [
    numberOfForcedBlocks
    meanRatio
    medianRatio
    minimumRatio
    maximumRatio
    meanFrequencyDistance
    medianFrequencyDistance
];

overallSummaryTable = table( ...
    statistic, ...
    value, ...
    'VariableNames', { ...
        'Statistic', ...
        'Value' ...
    } ...
);

outputDirectory = fullfile( ...
    projectDirectory, ...
    'results', ...
    'groupB_rebuild' ...
);

detailCsvFile = fullfile( ...
    outputDirectory, ...
    'B05_forced_nonprimary_block_details.csv' ...
);

nearTieCsvFile = fullfile( ...
    outputDirectory, ...
    'B05_near_tie_summary.csv' ...
);

rankCsvFile = fullfile( ...
    outputDirectory, ...
    'B05_forced_rank_summary.csv' ...
);

pairCsvFile = fullfile( ...
    outputDirectory, ...
    'B05_forced_pair_summary.csv' ...
);

overallCsvFile = fullfile( ...
    outputDirectory, ...
    'B05_overall_forced_peak_summary.csv' ...
);

resultMatFile = fullfile( ...
    outputDirectory, ...
    'B05_forced_nonprimary_analysis.mat' ...
);

writetable(forcedAnalysisTable, detailCsvFile);
writetable(nearTieSummaryTable, nearTieCsvFile);
writetable(forcedRankSummaryTable, rankCsvFile);
writetable(forcedPairSummaryTable, pairCsvFile);
writetable(overallSummaryTable, overallCsvFile);

save( ...
    resultMatFile, ...
    'forcedAnalysisTable', ...
    'nearTieSummaryTable', ...
    'forcedRankSummaryTable', ...
    'forcedPairSummaryTable', ...
    'overallSummaryTable' ...
);

fprintf('================================================\n');
fprintf('B05: Forced non-primary peak analysis\n');
fprintf('================================================\n\n');

fprintf('Overall forced-peak summary:\n');
disp(overallSummaryTable);

fprintf('\nNear-tie summary:\n');
disp(nearTieSummaryTable);

fprintf('\nStrongest supported non-primary ranks:\n');
disp(forcedRankSummaryTable);

fprintf('\nForced subject-class pairs:\n');
disp(forcedPairSummaryTable);

fprintf('\nForced block details:\n');
disp(forcedAnalysisTable(:, { ...
    'SubjectID', ...
    'ClassLabel', ...
    'TargetFrequencyHz', ...
    'Block', ...
    'ArticleMeanHz', ...
    'PrimaryPeakFrequencyHz', ...
    'StrongestArticleConsistentRank', ...
    'StrongestArticleConsistentFrequencyHz', ...
    'StrongestArticleConsistentAmplitudeRatio', ...
    'AmplitudeGapFromPrimary', ...
    'StrongestArticleConsistentRankSupport', ...
    'PreferredRank', ...
    'PreferredRankAmplitudeRatio' ...
}));

fprintf('\nDetail CSV:\n%s\n', detailCsvFile);
fprintf('\nNear-tie CSV:\n%s\n', nearTieCsvFile);
fprintf('\nRank summary CSV:\n%s\n', rankCsvFile);
fprintf('\nPair summary CSV:\n%s\n', pairCsvFile);
fprintf('\nOverall summary CSV:\n%s\n', overallCsvFile);
fprintf('\nMAT results:\n%s\n', resultMatFile);
